import { describe, it, expect } from "vitest";
import * as path from "node:path";
import * as fs from "node:fs";
import * as os from "node:os";
import {
  loadFixture,
  runBehaviorCheck,
} from "../src/laws/behavior-checker.js";

// Smoke-test the v0 behaviour-axis checker end-to-end against the
// project's REAL source files. Validates two paths the unit tests
// in behavior-checker.test.ts cannot reach:
//   1. Loading a `.fixture.ts` file from the shipped
//      tests/behavior-fixtures/ directory (the production extension).
//   2. Loading a real TS module from the project tree via dynamic
//      import, on both sides of the comparison.
//
// Why this is a SMOKE test, not a full integration test: Arm A's
// regenerated artefacts under `.ontology/verify/` are not preserved
// across runs, so we cannot point the checker at a real regen here.
// We use identity (src and regen both point to the same on-disk
// source) to confirm the runner accepts real TS, runs the fixture,
// and yields `pass`. Real regen-vs-source measurement requires
// re-running `verify-homeomorphism` with `--matrix --behavior-check`
// against a live arm.
//
// Vitest caveat: the project's `.ts` files are inside Vite's
// resolver root, so dynamic `import()` of a `file://` URL pointing
// at them works. The unit tests sit in `/tmp/...` (outside the
// root) and have to use `.mjs`; this smoke test deliberately runs
// against the real tree.

const FIXTURES_DIR = path.resolve(__dirname, "behavior-fixtures");
const PROJECT_ROOT = path.resolve(__dirname, "..");

interface IdentityCase {
  nodeId: string;
  sourceRelative: string;
}

// EVERY shipped fixture, with the source module its cases exercise
// (per the fixture's own header — node_0091/0092 are second fixtures
// for poset/traversal, not commands/graph/*). The runner reads
// src + regen from the same path → fixture must report `pass` if the
// plumbing works. A `fail` or `untested` here means: fixture
// signature drifted from the source's export, or vitest's resolver
// rejected the `.ts` import, or the runner has a bug. The
// completeness guard below fails if a fixture lands in the directory
// without being registered here.
const CASES: readonly IdentityCase[] = [
  { nodeId: "node_0005", sourceRelative: "src/forward/compile/post/extract-code-fence.ts" },
  { nodeId: "node_0006", sourceRelative: "src/forward/compile/post/runtime-check.ts" },
  { nodeId: "node_0007", sourceRelative: "src/forward/compile/post/validate-language.ts" },
  { nodeId: "node_0008", sourceRelative: "src/forward/compile/upstream-context.ts" },
  { nodeId: "node_0011", sourceRelative: "src/forward/context/gluing.ts" },
  { nodeId: "node_0019", sourceRelative: "src/laws/effects/result.ts" },
  { nodeId: "node_0024", sourceRelative: "src/kernel/graph/compile-plan.ts" },
  { nodeId: "node_0026", sourceRelative: "src/kernel/graph/poset.ts" },
  { nodeId: "node_0027", sourceRelative: "src/kernel/graph/traversal.ts" },
  { nodeId: "node_0028", sourceRelative: "src/inverse/frontier-tagger.ts" },
  { nodeId: "node_0029", sourceRelative: "src/laws/matrix-intersections.ts" },
  { nodeId: "node_0030", sourceRelative: "src/laws/matrix.ts" },
  { nodeId: "node_0031", sourceRelative: "src/laws/pareto.ts" },
  { nodeId: "node_0033", sourceRelative: "src/laws/render-ascii.ts" },
  { nodeId: "node_0034", sourceRelative: "src/inverse/static-summary.ts" },
  { nodeId: "node_0035", sourceRelative: "src/inverse/structural-classifier.ts" },
  { nodeId: "node_0036", sourceRelative: "src/inverse/translator.ts" },
  { nodeId: "node_0038", sourceRelative: "src/laws/vocab-gap.ts" },
  { nodeId: "node_0044", sourceRelative: "src/runtime/llm/registry.ts" },
  { nodeId: "node_0047", sourceRelative: "src/forward/prompt/parse.ts" },
  { nodeId: "node_0053", sourceRelative: "src/inverse/static/typescript.ts" },
  { nodeId: "node_0055", sourceRelative: "src/laws/topos/omega.ts" },
  { nodeId: "node_0056", sourceRelative: "src/laws/topos/predicate.ts" },
  { nodeId: "node_0057", sourceRelative: "src/laws/topos/rule-compiler.ts" },
  { nodeId: "node_0062", sourceRelative: "src/kernel/core/errors.ts" },
  { nodeId: "node_0065", sourceRelative: "src/kernel/core/integrity/hash.ts" },
  { nodeId: "node_0067", sourceRelative: "src/kernel/core/nodes/node-id.ts" },
  { nodeId: "node_0074", sourceRelative: "src/kernel/core/render/box.ts" },
  { nodeId: "node_0075", sourceRelative: "src/kernel/core/render/style.ts" },
  { nodeId: "node_0076", sourceRelative: "src/kernel/core/render/table.ts" },
  { nodeId: "node_0091", sourceRelative: "src/kernel/graph/poset.ts" },
  { nodeId: "node_0092", sourceRelative: "src/kernel/graph/traversal.ts" },
  { nodeId: "node_0093", sourceRelative: "src/surfaces/commands/ingest/cost-estimate.ts" },
  { nodeId: "node_0095", sourceRelative: "src/surfaces/commands/ingest/static-classifier-policy.ts" },
  // Auto-generated by `onto probe` over the LIVE-graph kernel cohort
  // (ROUNDTRIP_BILATERAL_2026-06-12 → behavioural-T2 lift, 2026-06-13).
  // These node ids are in the live 2026-06-11 graph's id-space (distinct
  // from the May-era hand fixtures above); registered here so the
  // completeness guard stays meaningful and they get identity-check
  // coverage. Each was self-validated source-vs-source at generation.
  { nodeId: "node_0017", sourceRelative: "src/kernel/core/nodes/node-id.ts" },
  { nodeId: "node_0022", sourceRelative: "src/kernel/core/project/paths.ts" },
  { nodeId: "node_0109", sourceRelative: "src/laws/effects/io.ts" },
  { nodeId: "node_0131", sourceRelative: "src/inverse/frontier-tagger.ts" },
  { nodeId: "node_0146", sourceRelative: "src/runtime/llm/dispatcher.ts" },
  { nodeId: "node_0176", sourceRelative: "src/runtime/workflow/graph-load.ts" },
  { nodeId: "node_0186", sourceRelative: "src/surfaces/walker/actions/proposals-from-walker.ts" },
  { nodeId: "node_0217", sourceRelative: "src/surfaces/walker/state/shadow-status.ts" },
  { nodeId: "node_0223", sourceRelative: "src/runtime/llm/ensemble.ts" },
  { nodeId: "node_0225", sourceRelative: "src/laws/reps-aggregator.ts" },
  { nodeId: "node_0227", sourceRelative: "src/kernel/schemas/workflow.ts" },
];

describe("behavior-checker / E2E smoke against real source files (identity)", () => {
  it("completeness guard: every fixture in the directory is registered above", () => {
    const onDisk = fs
      .readdirSync(FIXTURES_DIR)
      .filter((f) => f.endsWith(".fixture.ts"))
      .map((f) => f.replace(/\.fixture\.ts$/, ""))
      .sort();
    const registered = CASES.map((c) => c.nodeId).sort();
    expect(onDisk).toEqual(registered);
  });

  for (const c of CASES) {
    it(`${c.nodeId} (${c.sourceRelative}) — identity check passes`, async () => {
      const sourceAbs = path.resolve(PROJECT_ROOT, c.sourceRelative);
      expect(fs.existsSync(sourceAbs)).toBe(true);
      const fixtureLoad = await loadFixture(FIXTURES_DIR, c.nodeId);
      expect(fixtureLoad).not.toBeNull();
      if (!fixtureLoad) return;
      const result = await runBehaviorCheck({
        nodeId: c.nodeId,
        sourcePath: sourceAbs,
        regenPath: sourceAbs, // identity — same file on both sides
        fixture: fixtureLoad.fixture,
      });
      // Identity must produce a pass. A fail would mean the fixture
      // mis-models the function under test.
      expect(result.verdict).toBe("pass");
      expect(result.cases?.every((cc) => cc.outcome === "match")).toBe(true);
    });
  }

  it("detects a deliberate divergence — fixture against a mutated regen", async () => {
    // Build a regen file that re-exports errorMessage with INVERTED
    // semantics: return "WRONG" no matter what. The shipped
    // node_0062 fixture asserts errorMessage(new Error("permission
    // denied")) === "permission denied"; the regen returns "WRONG",
    // so the runner must fold to `fail` with a divergent outcome.
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "bc-smoke-div-"));
    try {
      const regen = path.join(dir, "errors.mjs");
      fs.writeFileSync(
        regen,
        `export function errorMessage(_e) { return "WRONG"; }\n`,
      );
      const sourceAbs = path.resolve(PROJECT_ROOT, "src/kernel/core/errors.ts");
      const fixtureLoad = await loadFixture(FIXTURES_DIR, "node_0062");
      expect(fixtureLoad).not.toBeNull();
      if (!fixtureLoad) return;
      const result = await runBehaviorCheck({
        nodeId: "node_0062",
        sourcePath: sourceAbs,
        regenPath: regen,
        fixture: fixtureLoad.fixture,
      });
      expect(result.verdict).toBe("fail");
      // At least one case diverged or the assert returned false on
      // the regen side.
      expect(
        result.cases?.some(
          (cc) => cc.outcome === "divergent" || cc.outcome === "errored",
        ),
      ).toBe(true);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
