import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { createTempProject, cleanupTempProject } from "./helpers/temp-project.js";
import { runCli } from "./helpers/run-cli.js";
import {
  extractFixtureSource,
  renderValidatedFixture,
  isGeneratedFixture,
  selfValidateFixture,
} from "../src/inverse/probe-generator.js";

// Coverage for `onto probe` — the generator that produces SELF-VALIDATED
// behavioural fixtures. The LLM dispatch is the non-deterministic seam, so the
// unit tests target (1) the deterministic self-validation core — the heart of
// the honesty guarantee — and (2) the command's governance guards. Full
// generation is exercised by the live run.

describe("probe-generator — pure helpers", () => {
  it("extractFixtureSource strips a ```ts fence and leading prose", () => {
    const raw = 'Here is the fixture:\n```ts\nimport type { BehaviorCase } from "x";\nexport const cases = [];\n```\nDone.';
    const out = extractFixtureSource(raw);
    expect(out.startsWith("import type { BehaviorCase }")).toBe(true);
    expect(out).toContain("export const cases = []");
    expect(out).not.toContain("```");
  });

  it("renderValidatedFixture renames the export and re-exports only kept indices", () => {
    const candidate = 'import type { BehaviorCase } from "x";\nexport const cases: BehaviorCase[] = [a, b, c];';
    const out = renderValidatedFixture(candidate, "node_0042", "src/x.ts", [0, 2], "qwen2.5-coder:7b");
    expect(out).toContain("const __generatedCases");
    expect(out).not.toMatch(/export\s+const\s+cases\s*:/); // original export was renamed
    expect(out).toContain("export const cases = __generatedCases.filter((_, i) => new Set([0, 2]).has(i));");
    expect(out).toContain("GENERATED by `onto probe node_0042`");
  });

  it("isGeneratedFixture distinguishes generated from hand-written", () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "probe-gen-"));
    const gen = path.join(dir, "g.fixture.ts");
    const hand = path.join(dir, "h.fixture.ts");
    fs.writeFileSync(gen, "// GENERATED by `onto probe node_0001` (model: x)\nexport const cases = [];");
    fs.writeFileSync(hand, "// hand-written fixture\nexport const cases = [];");
    expect(isGeneratedFixture(gen)).toBe(true);
    expect(isGeneratedFixture(hand)).toBe(false);
    fs.rmSync(dir, { recursive: true, force: true });
  });
});

describe("probe-generator — self-validation keeps only cases that match the source", () => {
  let dir: string;
  let sourcePath: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "probe-val-"));
    // A tiny pure source module + one throwing export.
    sourcePath = path.join(dir, "source.mjs");
    fs.writeFileSync(sourcePath, "export function addOne(n){ return n + 1; }\nexport function boom(){ throw new Error('io'); }\n");
    // Candidate fixture (.mjs — plain JS, no type import) with 4 cases:
    //   good                — returns 3, asserts 3 → match → KEPT
    //   throws-consistently — boom() throws identically on both sides → match
    //                         → KEPT (a deterministic throw is a valid locked
    //                         characterization; a regen that didn't throw would
    //                         diverge)
    //   wrong-assert        — returns 3 but asserts 999 → assert false → DROPPED
    //   nondeterministic    — Math.random() differs per side → divergent → DROPPED
    const candidate = `export const cases = [
      { name: "good", setup: () => 2, invoke: (api, ctx) => api.addOne(ctx), assert: (r) => r === 3 },
      { name: "throws-consistently", setup: () => null, invoke: (api) => api.boom(), assert: () => true },
      { name: "wrong-assert", setup: () => 2, invoke: (api, ctx) => api.addOne(ctx), assert: (r) => r === 999 },
      { name: "nondeterministic", setup: () => 0, invoke: () => Math.random(), assert: () => true },
    ];`;
    fs.writeFileSync(path.join(dir, "node_0001.fixture.mjs"), candidate);
  });

  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

  it("keeps deterministic-true cases (incl. consistent throws) and drops false-assert / non-deterministic ones", async () => {
    const result = await selfValidateFixture("node_0001", sourcePath, path.join(dir, "node_0001.fixture.mjs"), dir);
    expect(result.totalCases).toBe(4);
    expect(result.kept).toEqual([0, 1]);
    const byName = Object.fromEntries(result.caseResults.map((c) => [c.name, c.kept]));
    expect(byName["good"]).toBe(true);
    expect(byName["throws-consistently"]).toBe(true);
    expect(byName["wrong-assert"]).toBe(false);
    expect(byName["nondeterministic"]).toBe(false);
  });
});

describe("onto probe — governance guards (mock provider, no real generation)", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = createTempProject();
    expect(runCli(tempDir, ["init"]).status).toBe(0);
  });

  afterEach(() => cleanupTempProject(tempDir));

  it("errors on an unknown node", () => {
    const r = runCli(tempDir, ["probe", "node_9999", "--provider", "mock", "--json"]);
    expect(r.status).toBe(1);
    expect(JSON.parse(r.stdout).failure).toContain("not found");
  });

  it("refuses a node with no shadow", () => {
    expect(runCli(tempDir, ["node", "create", "--level", "domain", "--kind", "entity", "--prompt", "no shadow"]).status).toBe(0);
    const r = runCli(tempDir, ["probe", "node_0001", "--provider", "mock", "--json"]);
    expect(r.status).toBe(1);
    expect(JSON.parse(r.stdout).failure).toContain("nothing to probe");
  });

  it("protects a hand-written fixture without --force (guard fires before dispatch)", () => {
    // Build a shadow node.
    expect(runCli(tempDir, ["node", "create", "--level", "domain", "--kind", "entity", "--prompt", "domain"]).status).toBe(0);
    expect(
      runCli(tempDir, ["node", "create", "--level", "artifact", "--kind", "artifact", "--manifestation", "code", "--language", "python", "--prompt", "x"]).status,
    ).toBe(0);
    const shadowAbs = path.join(tempDir, "src/x.py");
    fs.mkdirSync(path.dirname(shadowAbs), { recursive: true });
    fs.writeFileSync(shadowAbs, "x = 1\n");
    const nodePath = path.join(tempDir, ".ontology/nodes/node_0002.json");
    const node = JSON.parse(fs.readFileSync(nodePath, "utf-8"));
    node.outputs = { ...(node.outputs ?? {}), files: ["src/x.py"] };
    fs.writeFileSync(nodePath, JSON.stringify(node, null, 2));
    // Plant a hand-written fixture.
    const fxDir = path.join(tempDir, "tests/behavior-fixtures");
    fs.mkdirSync(fxDir, { recursive: true });
    fs.writeFileSync(path.join(fxDir, "node_0002.fixture.ts"), "// hand-written\nexport const cases = [];\n");

    const r = runCli(tempDir, ["probe", "node_0002", "--provider", "mock", "--fixtures-dir", "tests/behavior-fixtures", "--json"]);
    expect(r.status).toBe(1);
    expect(JSON.parse(r.stdout).failure).toContain("hand-written");
    // The hand fixture is untouched.
    expect(fs.readFileSync(path.join(fxDir, "node_0002.fixture.ts"), "utf-8")).toContain("hand-written");
  });
});

describe("probe rule-targeting — the executable enforcement layer", () => {
  it("buildProbeUserPrompt embeds numbered behavioural rules as targets", async () => {
    const { buildProbeUserPrompt } = await import("../src/inverse/probe-generator.js");
    const node = { outputs: { files: ["src/x.ts"] }, prompt: { raw: "x" }, context: { provides: [] } } as any;
    const prompt = buildProbeUserPrompt(node, "export const x = 1;", ["returns undefined when empty", "throws on negative"]);
    expect(prompt).toContain("Behavioural rules to verify");
    expect(prompt).toContain("1. returns undefined when empty");
    expect(prompt).toContain("2. throws on negative");
  });

  it("ruleCoverage maps rule:N cases to enforced / violated / uncovered", async () => {
    const { ruleCoverage } = await import("../src/inverse/probe-generator.js");
    const rules = ["returns undefined when empty", "throws on negative", "is monotonic"];
    const caseResults = [
      { index: 0, name: "rule:1 — empty -> undefined", kept: true, outcome: "match" },
      { index: 1, name: "rule:2 — negative throws", kept: false, outcome: "divergent" },
      // rule 3 untargeted
    ];
    const cov = ruleCoverage(rules, caseResults as any);
    expect(cov[0].status).toBe("enforced");
    expect(cov[1].status).toBe("violated_or_unassertable");
    expect(cov[2].status).toBe("uncovered");
  });
});
