// GENERATED by `onto probe node_0184` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/surfaces/walker/actions/link-from-walker.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns error when focal node links to itself",
    setup: () => ({
      options: {
        focal: {
          id: "node1",
          coordinates: { abstraction: "concept" },
          integrity: { hash: "hash1" },
        } as any,
        to: "node1",
        type: "related_to",
      },
    }),
    invoke: (api, ctx) => api.linkFromWalker(ctx.options),
    assert: (r: any) => r.ok === false && r.message.includes("cannot link a node to itself"),
  },
  {
    name: "rule:2 — returns error when edge type is invalid",
    setup: () => ({
      options: {
        focal: {
          id: "node1",
          coordinates: { abstraction: "concept" },
          integrity: { hash: "hash1" },
        } as any,
        to: "node2",
        type: "invalid_type",
      },
    }),
    invoke: (api, ctx) => api.linkFromWalker(ctx.options),
    assert: (r: any) => r.ok === false && r.message.includes("invalid edge type"),
  },
  {
    name: "rule:3 — returns error when target node is not found",
    setup: () => ({
      options: {
        focal: {
          id: "node1",
          coordinates: { abstraction: "concept" },
          integrity: { hash: "hash1" },
        } as any,
        to: "nonexistent",
        type: "related_to",
      },
    }),
    invoke: (api, ctx) => api.linkFromWalker(ctx.options),
    assert: (r: any) => r.ok === false && r.message.includes("target node not found"),
  },
  {
    name: "rule:4 — returns error when edge direction is invalid",
    setup: () => ({
      options: {
        focal: {
          id: "node1",
          coordinates: { abstraction: "implementation" },
          integrity: { hash: "hash1" },
        } as any,
        to: "node2",
        type: "related_to",
      },
    }),
    invoke: (api, ctx) => api.linkFromWalker(ctx.options),
    assert: (r: any) => r.ok === false && typeof r.message === "string",
  },
  {
    name: "rule:5 — returns success with proposal when all validations pass",
    setup: () => ({
      options: {
        focal: {
          id: "node1",
          coordinates: { abstraction: "concept" },
          integrity: { hash: "hash1" },
        } as any,
        to: "node2",
        type: "related_to",
      },
    }),
    invoke: (api, ctx) => api.linkFromWalker(ctx.options),
    assert: (r: any) => r.ok === true && typeof r.proposalId === "string",
  },
  {
    name: "typical case with rationale",
    setup: () => ({
      options: {
        focal: {
          id: "node1",
          coordinates: { abstraction: "concept" },
          integrity: { hash: "hash1" },
        } as any,
        to: "node2",
        type: "related_to",
        rationale: "Custom rationale",
      },
    }),
    invoke: (api, ctx) => api.linkFromWalker(ctx.options),
    assert: (r: any) => r.ok === true || (r.ok === false && typeof r.message === "string"),
  },
  {
    name: "case with cwd provided",
    setup: () => ({
      options: {
        focal: {
          id: "node1",
          coordinates: { abstraction: "concept" },
          integrity: { hash: "hash1" },
        } as any,
        to: "node2",
        type: "related_to",
        cwd: "/custom/path",
      },
    }),
    invoke: (api, ctx) => api.linkFromWalker(ctx.options),
    assert: (r: any) => r.ok === true || (r.ok === false && typeof r.message === "string"),
  },
  {
    name: "edge case with minimal valid input",
    setup: () => ({
      options: {
        focal: {
          id: "a",
          coordinates: { abstraction: "concept" },
          integrity: { hash: "hash-a" },
        } as any,
        to: "b",
        type: "related_to",
      },
    }),
    invoke: (api, ctx) => api.linkFromWalker(ctx.options),
    assert: (r: any) => r.ok === true || (r.ok === false && typeof r.message === "string"),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 3, 5, 6, 7]).has(i));
