// GENERATED by `onto probe node_0169` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/forward/templates/load.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — templatesDir returns absolute path",
    setup: () => ({}),
    invoke: (api) => api.templatesDir(),
    assert: (r) => typeof r === "string" && path.isAbsolute(r),
  },
  {
    name: "rule:2 — listTemplates returns summaries of valid templates",
    setup: () => ({}),
    invoke: (api) => api.listTemplates(),
    assert: (r) => Array.isArray(r) && r.every((t) => typeof t.name === "string" && typeof t.description === "string"),
  },
  {
    name: "rule:3 — availableNames returns comma-separated names or fallback",
    setup: () => ({}),
    invoke: (api) => (api as any).availableNames(),
    assert: (r) => typeof r === "string" && (r.includes(", ") || r === "(none found)"),
  },
  {
    name: "rule:4 — loadTemplate throws on missing template",
    setup: () => ({ name: "nonexistent-template" }),
    invoke: (api, ctx) => {
      try {
        return api.loadTemplate(ctx.name);
      } catch (e) {
        return e instanceof Error ? e.message : String(e);
      }
    },
    assert: (r) => typeof r === "string" && r.includes("Unknown template"),
  },
  {
    name: "rule:5 — validateTemplateIntegrity throws on duplicate keys",
    setup: () => ({
      template: {
        name: "test-template",
        description: "A test template",
        nodes: [
          { key: "a", level: "domain", parent: undefined },
          { key: "a", level: "domain", parent: undefined }, // duplicate key
        ],
        edges: [],
      },
    }),
    invoke: (api, ctx) => {
      try {
        api.validateTemplateIntegrity(ctx.template);
        return "no error";
      } catch (e) {
        return e instanceof Error ? e.message : String(e);
      }
    },
    assert: (r) => typeof r === "string" && r.includes("duplicate node key"),
  },
  {
    name: "rule:6 — validateTemplateIntegrity throws on parent not defined earlier",
    setup: () => ({
      template: {
        name: "test-template",
        description: "A test template",
        nodes: [
          { key: "child", level: "domain", parent: "parent" }, // parent not defined earlier
          { key: "parent", level: "domain", parent: undefined },
        ],
        edges: [],
      },
    }),
    invoke: (api, ctx) => {
      try {
        api.validateTemplateIntegrity(ctx.template);
        return "no error";
      } catch (e) {
        return e instanceof Error ? e.message : String(e);
      }
    },
    assert: (r) => typeof r === "string" && r.includes("references parent") && r.includes("not defined earlier"),
  },
  {
    name: "rule:7 — validateTemplateIntegrity throws on invalid edge endpoint",
    setup: () => ({
      template: {
        name: "test-template",
        description: "A test template",
        nodes: [{ key: "node1", level: "domain", parent: undefined }],
        edges: [{ from: "node1", to: "unknown-node", type: "refers" }],
      },
    }),
    invoke: (api, ctx) => {
      try {
        api.validateTemplateIntegrity(ctx.template);
        return "no error";
      } catch (e) {
        return e instanceof Error ? e.message : String(e);
      }
    },
    assert: (r) => typeof r === "string" && r.includes("edge endpoint") && r.includes("is not a known node key"),
  },
  {
    name: "rule:8 — validateTemplateIntegrity throws on invalid edge direction",
    setup: () => ({
      template: {
        name: "test-template",
        description: "A test template",
        nodes: [
          { key: "high", level: "domain", parent: undefined },
          { key: "low", level: "mechanism", parent: undefined },
        ],
        edges: [{ from: "low", to: "high", type: "refers" }], // invalid direction
      },
    }),
    invoke: (api, ctx) => {
      try {
        api.validateTemplateIntegrity(ctx.template);
        return "no error";
      } catch (e) {
        return e instanceof Error ? e.message : String(e);
      }
    },
    assert: (r) => typeof r === "string" && r.includes("edge") && r.includes("is invalid"),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([1, 2, 3, 4, 5, 6]).has(i));
