// GENERATED by `onto probe node_0211` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/surfaces/walker/state/neighborhood.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns focal node and its relationships when node exists",
    setup: () => ({
      focalId: "node-1",
      cwd: "/project",
      nodes: [
        { id: "node-1", graph: { parentId: "node-2" } },
        { id: "node-2", graph: { parentId: null } },
        { id: "node-3", graph: { parentId: "node-1" } },
        { id: "node-4", graph: { parentId: "node-2" } }
      ],
      edges: [
        { from: "node-1", to: "node-3" },
        { from: "node-4", to: "node-1" }
      ]
    }),
    invoke: (api, ctx) => {
      const { cwd, nodes, edges } = ctx as any;
      jest.spyOn(api, 'loadNodeById').mockReturnValue(nodes.find(n => n.id === "node-1"));
      jest.spyOn(api, 'loadNodes').mockReturnValue(nodes);
      jest.spyOn(api, 'loadEdges').mockReturnValue(edges);
      return api.loadFocalNeighborhood("node-1", cwd);
    },
    assert: (r) => r.focal.id === "node-1" && 
                  r.parent?.id === "node-2" && 
                  r.children.length === 1 && 
                  r.children[0].id === "node-3" && 
                  r.siblings.length === 1 && 
                  r.siblings[0].id === "node-4" &&
                  r.edgesOut.length === 1 && 
                  r.edgesIn.length === 1 &&
                  r.edgeNeighbors.length === 2
  },
  {
    name: "rule:2 — throws error when focal node does not exist",
    setup: () => ({
      focalId: "missing-node",
      cwd: "/project"
    }),
    invoke: (api, ctx) => {
      jest.spyOn(api, 'loadNodeById').mockImplementation(() => {
        throw new Error("Node not found: missing-node");
      });
      return () => api.loadFocalNeighborhood("missing-node", "/project");
    },
    assert: (r) => {
      try {
        r();
        return false;
      } catch (e) {
        return e.message === "Node not found: missing-node";
      }
    }
  },
  {
    name: "rule:3 — returns empty arrays for children and siblings when focal has none",
    setup: () => ({
      focalId: "orphan",
      cwd: "/project",
      nodes: [
        { id: "orphan", graph: { parentId: null } }
      ],
      edges: []
    }),
    invoke: (api, ctx) => {
      const { cwd, nodes, edges } = ctx as any;
      jest.spyOn(api, 'loadNodeById').mockReturnValue(nodes[0]);
      jest.spyOn(api, 'loadNodes').mockReturnValue(nodes);
      jest.spyOn(api, 'loadEdges').mockReturnValue(edges);
      return api.loadFocalNeighborhood("orphan", cwd);
    },
    assert: (r) => r.focal.id === "orphan" && 
                  r.parent === null && 
                  r.children.length === 0 && 
                  r.siblings.length === 0
  },
  {
    name: "rule:4 — handles missing edges file gracefully",
    setup: () => ({
      focalId: "node-1",
      cwd: "/project",
      nodes: [
        { id: "node-1", graph: { parentId: null } }
      ]
    }),
    invoke: (api, ctx) => {
      const { cwd, nodes } = ctx as any;
      jest.spyOn(api, 'loadNodeById').mockReturnValue(nodes[0]);
      jest.spyOn(api, 'loadNodes').mockReturnValue(nodes);
      jest.spyOn(api, 'loadEdges').mockImplementation(() => {
        throw new Error("File not found");
      });
      return api.loadFocalNeighborhood("node-1", cwd);
    },
    assert: (r) => r.focal.id === "node-1" && 
                  r.edgesOut.length === 0 && 
                  r.edgesIn.length === 0 && 
                  r.edgeNeighbors.length === 0
  },
  {
    name: "rule:5 — constructs correct path to canon including focal node",
    setup: () => ({
      focalId: "child",
      cwd: "/project",
      nodes: [
        { id: "child", graph: { parentId: "parent" } },
        { id: "parent", graph: { parentId: "grandparent" } },
        { id: "grandparent", graph: { parentId: null } }
      ],
      edges: []
    }),
    invoke: (api, ctx) => {
      const { cwd, nodes, edges } = ctx as any;
      jest.spyOn(api, 'loadNodeById').mockReturnValue(nodes.find(n => n.id === "child"));
      jest.spyOn(api, 'loadNodes').mockReturnValue(nodes);
      jest.spyOn(api, 'loadEdges').mockReturnValue(edges);
      return api.loadFocalNeighborhood("child", cwd);
    },
    assert: (r) => r.pathToCanon.length === 3 && 
                  r.pathToCanon[0].id === "grandparent" && 
                  r.pathToCanon[1].id === "parent" && 
                  r.pathToCanon[2].id === "child"
  },
  {
    name: "rule:6 — detects and stops on cycles in parent chain",
    setup: () => ({
      focalId: "node-1",
      cwd: "/project",
      nodes: [
        { id: "node-1", graph: { parentId: "node-2" } },
        { id: "node-2", graph: { parentId: "node-1" } } // cycle
      ],
      edges: []
    }),
    invoke: (api, ctx) => {
      const { cwd, nodes, edges } = ctx as any;
      jest.spyOn(api, 'loadNodeById').mockReturnValue(nodes[0]);
      jest.spyOn(api, 'loadNodes').mockReturnValue(nodes);
      jest.spyOn(api, 'loadEdges').mockReturnValue(edges);
      return api.loadFocalNeighborhood("node-1", cwd);
    },
    assert: (r) => r.pathToCanon.length === 2 && 
                  r.pathToCanon[0].id === "node-2" && 
                  r.pathToCanon[1].id === "node-1"
  },
  {
    name: "rule:7 — deduplicates edge neighbors correctly",
    setup: () => ({
      focalId: "node-1",
      cwd: "/project",
      nodes: [
        { id: "node-1", graph: { parentId: null } },
        { id: "node-2", graph: { parentId: null } },
        { id: "node-3", graph: { parentId: null } }
      ],
      edges: [
        { from: "node-1", to: "node-2" },
        { from: "node-3", to: "node-1" },
        { from: "node-1", to: "node-2" } // duplicate
      ]
    }),
    invoke: (api, ctx) => {
      const { cwd, nodes, edges } = ctx as any;
      jest.spyOn(api, 'loadNodeById').mockReturnValue(nodes[0]);
      jest.spyOn(api, 'loadNodes').mockReturnValue(nodes);
      jest.spyOn(api, 'loadEdges').mockReturnValue(edges);
      return api.loadFocalNeighborhood("node-1", cwd);
    },
    assert: (r) => r.edgeNeighbors.length === 2 && 
                  r.edgesOut.length === 2 && // includes duplicate
                  r.edgesIn.length === 1
  },
  {
    name: "rule:8 — returns null parent when focal node has no parent",
    setup: () => ({
      focalId: "root",
      cwd: "/project",
      nodes: [
        { id: "root", graph: { parentId: null } },
        { id: "child", graph: { parentId: "root" } }
      ],
      edges: []
    }),
    invoke: (api, ctx) => {
      const { cwd, nodes, edges } = ctx as any;
      jest.spyOn(api, 'loadNodeById').mockReturnValue(nodes[0]);
      jest.spyOn(api, 'loadNodes').mockReturnValue(nodes);
      jest.spyOn(api, 'loadEdges').mockReturnValue(edges);
      return api.loadFocalNeighborhood("root", cwd);
    },
    assert: (r) => r.focal.id === "root" && 
                  r.parent === null && 
                  r.children.length === 1 &&
                  r.siblings.length === 0
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
