// GENERATED by `onto probe node_0142` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 5 self-validated case(s)
// (each matched the source src/laws/verdict-variance.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type {
  RegenSample,
  NodeVarianceReport,
  AggregateVarianceReport,
  HomeomorphismVerdict,
} from "./verdict-variance.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — measureNodeVariance with empty samples returns zero counts and metrics",
    setup: () => ({
      nodeId: "node1",
      original: "function test() { return 42; }",
      samples: [] as RegenSample[],
      language: "typescript",
      thresholds: undefined,
    }),
    invoke: (api, ctx) =>
      api.measureNodeVariance(ctx.nodeId, ctx.original, ctx.samples, ctx.language, ctx.thresholds),
    assert: (r: NodeVarianceReport) =>
      r.n === 0 &&
      r.verdictCounts.unrecoverable === 0 &&
      r.agreementRate === 0 &&
      r.verdictEntropyBits === 0 &&
      r.jaccardMean === 0 &&
      r.jaccardStdev === 0 &&
      r.locMean === 0 &&
      r.locStdev === 0 &&
      r.recoverable === 0,
  },
  {
    name: "rule:2 — measureNodeVariance with identical samples yields agreement rate 1 and entropy 0",
    setup: () => ({
      nodeId: "node2",
      original: "const x = 1;",
      samples: ["const x = 1;", "const x = 1;", "const x = 1;"] as RegenSample[],
      language: "javascript",
    }),
    invoke: (api, ctx) =>
      api.measureNodeVariance(ctx.nodeId, ctx.original, ctx.samples, ctx.language),
    assert: (r: NodeVarianceReport) =>
      r.n === 3 &&
      r.agreementRate === 1 &&
      r.verdictEntropyBits === 0 &&
      r.modalVerdict === "identical",
  },
  {
    name: "rule:3 — measureNodeVariance handles null samples as unrecoverable verdicts",
    setup: () => ({
      nodeId: "node3",
      original: "let y = 2;",
      samples: [null, null] as RegenSample[],
      language: "javascript",
    }),
    invoke: (api, ctx) =>
      api.measureNodeVariance(ctx.nodeId, ctx.original, ctx.samples, ctx.language),
    assert: (r: NodeVarianceReport) =>
      r.n === 2 &&
      r.verdictCounts.unrecoverable === 2 &&
      r.agreementRate === 1 &&
      r.modalVerdict === "unrecoverable" &&
      r.recoverable === 0,
  },
  {
    name: "rule:4 — aggregateVariance with empty input returns zero summary",
    setup: () => ({
      perNode: [] as NodeVarianceReport[],
    }),
    invoke: (api, ctx) => api.aggregateVariance(ctx.perNode),
    assert: (r: AggregateVarianceReport) =>
      r.nodeCount === 0 &&
      r.meanAgreementRate === 0 &&
      r.meanVerdictEntropyBits === 0 &&
      r.fullyDeterministicFraction === 0 &&
      r.meanJaccardStdev === 0 &&
      r.perNode.length === 0,
  },
  {
    name: "rule:5 — aggregateVariance computes correct means and fraction for deterministic nodes",
    setup: () => {
      const mockReport1: NodeVarianceReport = {
        nodeId: "n1",
        n: 3,
        verdictCounts: {
          identical: 3,
          equivalent: 0,
          divergent: 0,
          unrecoverable: 0,
        },
        modalVerdict: "identical",
        agreementRate: 1,
        verdictEntropyBits: 0,
        jaccardMean: 0.9,
        jaccardStdev: 0,
        locMean: 0,
        locStdev: 0,
        recoverable: 3,
      };
      const mockReport2: NodeVarianceReport = {
        nodeId: "n2",
        n: 2,
        verdictCounts: {
          identical: 1,
          equivalent: 1,
          divergent: 0,
          unrecoverable: 0,
        },
        modalVerdict: "identical",
        agreementRate: 0.5,
        verdictEntropyBits: 1,
        jaccardMean: 0.8,
        jaccardStdev: 0.1,
        locMean: 0,
        locStdev: 0,
        recoverable: 2,
      };
      return { perNode: [mockReport1, mockReport2] };
    },
    invoke: (api, ctx) => api.aggregateVariance(ctx.perNode),
    assert: (r: AggregateVarianceReport) =>
      r.nodeCount === 2 &&
      r.meanAgreementRate === 0.75 &&
      r.meanVerdictEntropyBits === 0.5 &&
      r.fullyDeterministicFraction === 0.5 &&
      r.meanJaccardStdev === 0.05,
  },
  {
    name: "typical — measureNodeVariance with mixed verdicts produces correct entropy and agreement",
    setup: () => ({
      nodeId: "node4",
      original: "function add(a,b){return a+b;}",
      samples: [
        "function add(a,b){return a+b;}", // identical
        "function add(x,y){return x+y;}", // equivalent
        "function add(a,b){return a-b;}", // divergent
        null, // unrecoverable
      ] as RegenSample[],
      language: "javascript",
    }),
    invoke: (api, ctx) =>
      api.measureNodeVariance(ctx.nodeId, ctx.original, ctx.samples, ctx.language),
    assert: (r: NodeVarianceReport) =>
      r.n === 4 &&
      r.verdictCounts.identical === 1 &&
      r.verdictCounts.equivalent === 1 &&
      r.verdictCounts.divergent === 1 &&
      r.verdictCounts.unrecoverable === 1 &&
      r.agreementRate === 0.25 &&
      r.recoverable === 3,
  },
  {
    name: "edge — measureNodeVariance with single sample has agreement 1 and entropy 0",
    setup: () => ({
      nodeId: "node5",
      original: "var z = 3;",
      samples: ["var z = 3;"] as RegenSample[],
      language: "javascript",
    }),
    invoke: (api, ctx) =>
      api.measureNodeVariance(ctx.nodeId, ctx.original, ctx.samples, ctx.language),
    assert: (r: NodeVarianceReport) =>
      r.n === 1 &&
      r.agreementRate === 1 &&
      r.verdictEntropyBits === 0 &&
      r.modalVerdict === "identical",
  },
  {
    name: "aggregate — aggregateVariance includes full perNode array in result",
    setup: () => {
      const report: NodeVarianceReport = {
        nodeId: "n1",
        n: 1,
        verdictCounts: {
          identical: 1,
          equivalent: 0,
          divergent: 0,
          unrecoverable: 0,
        },
        modalVerdict: "identical",
        agreementRate: 1,
        verdictEntropyBits: 0,
        jaccardMean: 1,
        jaccardStdev: 0,
        locMean: 0,
        locStdev: 0,
        recoverable: 1,
      };
      return { perNode: [report] };
    },
    invoke: (api, ctx) => api.aggregateVariance(ctx.perNode),
    assert: (r: AggregateVarianceReport) =>
      r.perNode.length === 1 && r.perNode[0].nodeId === "n1",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 2, 3, 4, 7]).has(i));
