// GENERATED by `onto probe node_0010` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 1 self-validated case(s)
// (each matched the source src/kernel/core/edges/update-edge.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — throws when edgeId is missing",
    setup: () => ({ edgeId: undefined as any, type: "newType" }),
    invoke: (api, ctx) => {
      try {
        (api as any).updateEdge(ctx);
        return "did not throw";
      } catch (e) {
        return e instanceof Error ? e.message : "threw non-error";
      }
    },
    assert: (r) => r === "updateEdge requires at least one mutating field (today: --type)",
  },
  {
    name: "rule:2 — throws when type is undefined",
    setup: () => ({ edgeId: "test-edge-id", type: undefined }),
    invoke: (api, ctx) => {
      try {
        (api as any).updateEdge(ctx);
        return "did not throw";
      } catch (e) {
        return e instanceof Error ? e.message : "threw non-error";
      }
    },
    assert: (r) => r === "updateEdge requires at least one mutating field (today: --type)",
  },
  {
    name: "typical case with valid inputs",
    setup: () => ({
      edgeId: "edge-123",
      type: "updated-type",
      cwd: "/mock/cwd",
      eventMetadata: { source: "test" }
    }),
    invoke: (api, ctx) => {
      try {
        return (api as any).updateEdge(ctx);
      } catch (e) {
        return e instanceof Error ? `Error: ${e.message}` : "Non-error thrown";
      }
    },
    assert: (r) => typeof r === "object" && r !== null && "event" in r && "edge" in r,
  },
  {
    name: "edge not found scenario",
    setup: () => ({ edgeId: "nonexistent", type: "some-type", cwd: "/empty/project" }),
    invoke: (api, ctx) => {
      try {
        return (api as any).updateEdge(ctx);
      } catch (e) {
        return e instanceof Error ? `Error: ${e.message}` : "Non-error thrown";
      }
    },
    assert: (r) => typeof r === "string" && r.startsWith("Error: Edge not found:"),
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([1]).has(i));
