// GENERATED by `onto probe node_0167` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 1 self-validated case(s)
// (each matched the source src/inverse/static/typescript-resolved.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns empty map for no file paths",
    setup: () => [],
    invoke: (api, ctx) => api.extractResolvedSignatures(ctx),
    assert: (r) => r instanceof Map && r.size === 0,
  },
  {
    name: "rule:2 — preserves order of exports by name",
    setup: () => ["./test1.ts"],
    invoke: (api, ctx) => {
      // Mocking a program that returns exports in reverse order
      const mockProgram = {
        getSourceFile: () => ({}) as any,
        getTypeChecker: () => ({
          getSymbolAtLocation: () => ({}) as any,
          getExportsOfModule: () => [
            { getName: () => "zExport" },
            { getName: () => "aExport" },
          ],
          getTypeOfSymbolAtLocation: () => ({ flags: 0 }) as any,
          typeToString: () => "string",
        }),
      };
      (globalThis as any).ts = {
        createProgram: () => mockProgram,
        ScriptTarget: { ES2022: 9 },
        ModuleKind: { NodeNext: 199 },
        ModuleResolutionKind: { NodeNext: 3 },
        TypeFormatFlags: { NoTruncation: 2, UseSingleQuotesForStringLiteralType: 131072 },
        SymbolFlags: { Alias: 1024 },
        TypeFlags: { Any: 1 },
        forEachChild: () => {},
      };
      return api.extractResolvedSignatures(ctx);
    },
    assert: (r) => {
      const arr = r.get("./test1.ts") ?? [];
      return arr[0].name === "aExport" && arr[1].name === "zExport";
    },
  },
  {
    name: "rule:3 — skips default exports",
    setup: () => ["./test2.ts"],
    invoke: (api, ctx) => {
      const mockProgram = {
        getSourceFile: () => ({}) as any,
        getTypeChecker: () => ({
          getSymbolAtLocation: () => ({}) as any,
          getExportsOfModule: () => [
            { getName: () => "default" },
            { getName: () => "namedExport" },
          ],
          getTypeOfSymbolAtLocation: () => ({ flags: 0 }) as any,
          typeToString: () => "string",
        }),
      };
      (globalThis as any).ts = {
        createProgram: () => mockProgram,
        ScriptTarget: { ES2022: 9 },
        ModuleKind: { NodeNext: 199 },
        ModuleResolutionKind: { NodeNext: 3 },
        TypeFormatFlags: { NoTruncation: 2, UseSingleQuotesForStringLiteralType: 131072 },
        SymbolFlags: { Alias: 1024 },
        TypeFlags: { Any: 1 },
        forEachChild: () => {},
      };
      return api.extractResolvedSignatures(ctx);
    },
    assert: (r) => {
      const arr = r.get("./test2.ts") ?? [];
      return arr.length === 1 && arr[0].name === "namedExport";
    },
  },
  {
    name: "rule:4 — skips export= exports",
    setup: () => ["./test3.ts"],
    invoke: (api, ctx) => {
      const mockProgram = {
        getSourceFile: () => ({}) as any,
        getTypeChecker: () => ({
          getSymbolAtLocation: () => ({}) as any,
          getExportsOfModule: () => [
            { getName: () => "export=" },
            { getName: () => "validExport" },
          ],
          getTypeOfSymbolAtLocation: () => ({ flags: 0 }) as any,
          typeToString: () => "string",
        }),
      };
      (globalThis as any).ts = {
        createProgram: () => mockProgram,
        ScriptTarget: { ES2022: 9 },
        ModuleKind: { NodeNext: 199 },
        ModuleResolutionKind: { NodeNext: 3 },
        TypeFormatFlags: { NoTruncation: 2, UseSingleQuotesForStringLiteralType: 131072 },
        SymbolFlags: { Alias: 1024 },
        TypeFlags: { Any: 1 },
        forEachChild: () => {},
      };
      return api.extractResolvedSignatures(ctx);
    },
    assert: (r) => {
      const arr = r.get("./test3.ts") ?? [];
      return arr.length === 1 && arr[0].name === "validExport";
    },
  },
  {
    name: "rule:5 — skips symbols without declarations",
    setup: () => ["./test4.ts"],
    invoke: (api, ctx) => {
      const mockProgram = {
        getSourceFile: () => ({}) as any,
        getTypeChecker: () => ({
          getSymbolAtLocation: () => ({}) as any,
          getExportsOfModule: () => [
            { getName: () => "noDeclExport", valueDeclaration: undefined, declarations: [] },
            { getName: () => "validExport", valueDeclaration: {} },
          ],
          getTypeOfSymbolAtLocation: () => ({ flags: 0 }) as any,
          typeToString: () => "string",
        }),
      };
      (globalThis as any).ts = {
        createProgram: () => mockProgram,
        ScriptTarget: { ES2022: 9 },
        ModuleKind: { NodeNext: 199 },
        ModuleResolutionKind: { NodeNext: 3 },
        TypeFormatFlags: { NoTruncation: 2, UseSingleQuotesForStringLiteralType: 131072 },
        SymbolFlags: { Alias: 1024 },
        TypeFlags: { Any: 1 },
        forEachChild: () => {},
      };
      return api.extractResolvedSignatures(ctx);
    },
    assert: (r) => {
      const arr = r.get("./test4.ts") ?? [];
      return arr.length === 1 && arr[0].name === "validExport";
    },
  },
  {
    name: "rule:6 — skips type-only exports without valueDeclaration",
    setup: () => ["./test5.ts"],
    invoke: (api, ctx) => {
      const mockProgram = {
        getSourceFile: () => ({}) as any,
        getTypeChecker: () => ({
          getSymbolAtLocation: () => ({}) as any,
          getExportsOfModule: () => [
            {
              getName: () => "typeOnlyExport",
              valueDeclaration: undefined,
              flags: 0,
            },
            {
              getName: () => "validExport",
              valueDeclaration: {},
            },
          ],
          getTypeOfSymbolAtLocation: (sym: any) =>
            sym.getName() === "typeOnlyExport"
              ? ({ flags: 0 } as any)
              : ({ flags: 0 } as any),
          typeToString: () => "string",
          getAliasedSymbol: (s: any) => s,
        }),
      };
      (globalThis as any).ts = {
        createProgram: () => mockProgram,
        ScriptTarget: { ES2022: 9 },
        ModuleKind: { NodeNext: 199 },
        ModuleResolutionKind: { NodeNext: 3 },
        TypeFormatFlags: { NoTruncation: 2, UseSingleQuotesForStringLiteralType: 131072 },
        SymbolFlags: { Alias: 1024 },
        TypeFlags: { Any: 1 },
        forEachChild: () => {},
      };
      return api.extractResolvedSignatures(ctx);
    },
    assert: (r) => {
      const arr = r.get("./test5.ts") ?? [];
      return arr.length === 1 && arr[0].name === "validExport";
    },
  },
  {
    name: "rule:7 — skips exports resolving to 'any' type",
    setup: () => ["./test6.ts"],
    invoke: (api, ctx) => {
      const mockProgram = {
        getSourceFile: () => ({}) as any,
        getTypeChecker: () => ({
          getSymbolAtLocation: () => ({}) as any,
          getExportsOfModule: () => [
            { getName: () => "anyExport", valueDeclaration: {} },
            { getName: () => "validExport", valueDeclaration: {} },
          ],
          getTypeOfSymbolAtLocation: (sym: any) =>
            sym.getName() === "anyExport"
              ? ({ flags: 1 } as any) // TypeFlags.Any
              : ({ flags: 0 } as any),
          typeToString: () => "any",
        }),
      };
      (globalThis as any).ts = {
        createProgram: () => mockProgram,
        ScriptTarget: { ES2022: 9 },
        ModuleKind: { NodeNext: 199 },
        ModuleResolutionKind: { NodeNext: 3 },
        TypeFormatFlags: { NoTruncation: 2, UseSingleQuotesForStringLiteralType: 131072 },
        SymbolFlags: { Alias: 1024 },
        TypeFlags: { Any: 1 },
        forEachChild: () => {},
      };
      return api.extractResolvedSignatures(ctx);
    },
    assert: (r) => {
      const arr = r.get("./test6.ts") ?? [];
      return arr.length === 1 && arr[0].name === "validExport";
    },
  },
  {
    name: "rule:8 — prefixes resolved signatures with RESOLVED_SIGNATURE_PREFIX",
    setup: () => ["./test7.ts"],
    invoke: (api, ctx) => {
      const mockProgram = {
        getSourceFile: () => ({}) as any,
        getTypeChecker: () => ({
          getSymbolAtLocation: () => ({}) as any,
          getExportsOfModule: () => [{ getName: () => "testExport", valueDeclaration: {} }],
          getTypeOfSymbolAtLocation: () => ({ flags: 0 }) as any,
          typeToString: () => "string",
        }),
      };
      (globalThis as any).ts = {
        createProgram: () => mockProgram,
        ScriptTarget: { ES2022: 9 },
        ModuleKind: { NodeNext: 199 },
        ModuleResolutionKind: { NodeNext: 3 },
        TypeFormatFlags: { NoTruncation: 2, UseSingleQuotesForStringLiteralType: 131072 },
        SymbolFlags: { Alias: 1024 },
        TypeFlags: { Any: 1 },
        forEachChild: () => {},
      };
      return api.extractResolvedSignatures(ctx);
    },
    assert: (r) => {
      const arr = r.get("./test7.ts") ?? [];
      return (
        arr.length === 1 &&
        arr[0].name === "testExport" &&
        arr[0].signature.startsWith("resolved:")
      );
    },
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0]).has(i));
