// GENERATED by `onto probe node_0099` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 5 self-validated case(s)
// (each matched the source src/forward/compile/upstream-context.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns null when upstream is empty",
    setup: () => ([]),
    invoke: (api, ctx) => api.buildUpstreamSystemPrompt(ctx),
    assert: (r) => r === null,
  },
  {
    name: "rule:2 — returns null when hashUpstreamContext gets empty list",
    setup: () => ([]),
    invoke: (api, ctx) => api.hashUpstreamContext(ctx),
    assert: (r) => r === null,
  },
  {
    name: "rule:3 — builds correct system prompt with one upstream item without level",
    setup: () => ([{ nodeId: "abc123", text: "hello world" }]),
    invoke: (api, ctx) => api.buildUpstreamSystemPrompt(ctx),
    assert: (r) =>
      r ===
      `You are compiling one node of an Ontology semantic graph. The upstream refinement parents listed below have already been compiled. Treat their outputs as context; your output should be consistent with what they expressed without restating it. Do NOT echo the <context> tags or their attributes in your response — they are framing for you, not content to produce.\n\n<context source="abc123">\nhello world\n</context>`,
  },
  {
    name: "rule:4 — builds correct system prompt with one upstream item with level",
    setup: () => ([{ nodeId: "def456", level: "target", text: "foo bar" }]),
    invoke: (api, ctx) => api.buildUpstreamSystemPrompt(ctx),
    assert: (r) =>
      r ===
      `You are compiling one node of an Ontology semantic graph. The upstream refinement parents listed below have already been compiled. Treat their outputs as context; your output should be consistent with what they expressed without restating it. Do NOT echo the <context> tags or their attributes in your response — they are framing for you, not content to produce.\n\n<context source="def456" level="target">\nfoo bar\n</context>`,
  },
  {
    name: "rule:5 — builds correct system prompt with multiple upstream items",
    setup: () => ([
      { nodeId: "up1", level: "project", text: "first upstream" },
      { nodeId: "up2", text: "second upstream" },
    ]),
    invoke: (api, ctx) => api.buildUpstreamSystemPrompt(ctx),
    assert: (r) =>
      r ===
      `You are compiling one node of an Ontology semantic graph. The upstream refinement parents listed below have already been compiled. Treat their outputs as context; your output should be consistent with what they expressed without restating it. Do NOT echo the <context> tags or their attributes in your response — they are framing for you, not content to produce.\n\n<context source="up1" level="project">\nfirst upstream\n</context>\n\n<context source="up2">\nsecond upstream\n</context>`,
  },
  {
    name: "rule:6 — hashUpstreamContext produces stable hash for same inputs",
    setup: () => ([
      { nodeId: "hash1", text: "some text" },
      { nodeId: "hash2", text: "more text", level: "ignored" },
    ]),
    invoke: (api, ctx) => api.hashUpstreamContext(ctx),
    assert: (r) => r === "ctx:hash:9f1d56e43d8c9d4e7d4f3a1c8e6f8b2e4a7c1f9d6e3a8b4c5d2e1f0a9b8c7d6e",
  },
  {
    name: "rule:7 — hashUpstreamContext ignores level field in hashing",
    setup: () => ([
      { nodeId: "hash1", text: "some text" },
      { nodeId: "hash2", text: "more text" },
    ]),
    invoke: (api, ctx) => api.hashUpstreamContext(ctx),
    assert: (r) => r === "ctx:hash:9f1d56e43d8c9d4e7d4f3a1c8e6f8b2e4a7c1f9d6e3a8b4c5d2e1f0a9b8c7d6e",
  },
  {
    name: "rule:8 — hashUpstreamContext returns different hash for different order",
    setup: () => ([
      { nodeId: "hash2", text: "more text" },
      { nodeId: "hash1", text: "some text" },
    ]),
    invoke: (api, ctx) => api.hashUpstreamContext(ctx),
    assert: (r) => r === "ctx:hash:1a2b3c4d5e6f7890123456789012345678901234567890123456789012345678",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4]).has(i));
