// GENERATED by `onto probe node_0212` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/surfaces/walker/state/parse-graph-view-args.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns default depth 2 when input is empty",
    setup: () => "",
    invoke: (api, ctx) => api.parseGraphViewArgs(ctx),
    assert: (r) => r.ok === true && r.depth === 2,
  },
  {
    name: "rule:2 — parses valid integer within range",
    setup: () => "3",
    invoke: (api, ctx) => api.parseGraphViewArgs(ctx),
    assert: (r) => r.ok === true && r.depth === 3,
  },
  {
    name: "rule:3 — rejects non-integer input",
    setup: () => "abc",
    invoke: (api, ctx) => api.parseGraphViewArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes('expects an integer depth (got "abc")'),
  },
  {
    name: "rule:4 — rejects depth below lower bound",
    setup: () => "-1",
    invoke: (api, ctx) => api.parseGraphViewArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes('depth must be between 0 and 5 (got -1)'),
  },
  {
    name: "rule:5 — rejects depth above upper bound",
    setup: () => "6",
    invoke: (api, ctx) => api.parseGraphViewArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes('depth must be between 0 and 5 (got 6)'),
  },
  {
    name: "rule:6 — accepts minimum valid depth",
    setup: () => "0",
    invoke: (api, ctx) => api.parseGraphViewArgs(ctx),
    assert: (r) => r.ok === true && r.depth === 0,
  },
  {
    name: "rule:7 — accepts maximum valid depth",
    setup: () => "5",
    invoke: (api, ctx) => api.parseGraphViewArgs(ctx),
    assert: (r) => r.ok === true && r.depth === 5,
  },
  {
    name: "rule:8 — trims whitespace around input",
    setup: () => "  4  ",
    invoke: (api, ctx) => api.parseGraphViewArgs(ctx),
    assert: (r) => r.ok === true && r.depth === 4,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 4, 5, 6, 7]).has(i));
