// GENERATED by `onto probe node_0111` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/kernel/errors.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — OntologyRuntimeError constructs with message, name, code, and details",
    setup: () => ({
      message: "Runtime error occurred",
      options: { code: "RUNTIME_001", details: { userId: 123 } },
    }),
    invoke: (api, ctx) => new api.OntologyRuntimeError(ctx.message, ctx.options),
    assert: (r) => 
      r.message === "Runtime error occurred" &&
      r.name === "OntologyRuntimeError" &&
      r.code === "RUNTIME_001" &&
      r.details?.userId === 123,
  },
  {
    name: "rule:2 — OntologyContextError extends OntologyRuntimeError and forwards properties",
    setup: () => ({
      message: "Context error occurred",
      options: { code: "CONTEXT_001", details: { scope: "global" } },
    }),
    invoke: (api, ctx) => new api.OntologyContextError(ctx.message, ctx.options),
    assert: (r) => 
      r.message === "Context error occurred" &&
      r.name === "OntologyContextError" &&
      r.code === "CONTEXT_001" &&
      r.details?.scope === "global",
  },
  {
    name: "rule:3 — OntologyTopologyError extends OntologyRuntimeError and forwards properties",
    setup: () => ({
      message: "Topology error occurred",
      options: { code: "TOPOLOGY_001", details: { nodeId: "abc" } },
    }),
    invoke: (api, ctx) => new api.OntologyTopologyError(ctx.message, ctx.options),
    assert: (r) => 
      r.message === "Topology error occurred" &&
      r.name === "OntologyTopologyError" &&
      r.code === "TOPOLOGY_001" &&
      r.details?.nodeId === "abc",
  },
  {
    name: "rule:4 — OntologyBranchError extends OntologyRuntimeError and forwards properties",
    setup: () => ({
      message: "Branch error occurred",
      options: { code: "BRANCH_001", details: { branchId: "main" } },
    }),
    invoke: (api, ctx) => new api.OntologyBranchError(ctx.message, ctx.options),
    assert: (r) => 
      r.message === "Branch error occurred" &&
      r.name === "OntologyBranchError" &&
      r.code === "BRANCH_001" &&
      r.details?.branchId === "main",
  },
  {
    name: "rule:5 — OntologyInvariantError extends OntologyRuntimeError and forwards properties",
    setup: () => ({
      message: "Invariant error occurred",
      options: { code: "INVARIANT_001", details: { constraint: "not-null" } },
    }),
    invoke: (api, ctx) => new api.OntologyInvariantError(ctx.message, ctx.options),
    assert: (r) => 
      r.message === "Invariant error occurred" &&
      r.name === "OntologyInvariantError" &&
      r.code === "INVARIANT_001" &&
      r.details?.constraint === "not-null",
  },
  {
    name: "OntologyRuntimeError without details",
    setup: () => ({
      message: "Simple error",
      options: { code: "SIMPLE_001" },
    }),
    invoke: (api, ctx) => new api.OntologyRuntimeError(ctx.message, ctx.options),
    assert: (r) => 
      r.message === "Simple error" &&
      r.name === "OntologyRuntimeError" &&
      r.code === "SIMPLE_001" &&
      r.details === undefined,
  },
  {
    name: "OntologyContextError without details",
    setup: () => ({
      message: "Context error",
      options: { code: "CONTEXT_002" },
    }),
    invoke: (api, ctx) => new api.OntologyContextError(ctx.message, ctx.options),
    assert: (r) => 
      r.message === "Context error" &&
      r.name === "OntologyContextError" &&
      r.code === "CONTEXT_002" &&
      r.details === undefined,
  },
  {
    name: "OntologyRuntimeError maintains constructor name",
    setup: () => ({
      message: "Test error",
      options: { code: "TEST_001" },
    }),
    invoke: (api, ctx) => new api.OntologyRuntimeError(ctx.message, ctx.options),
    assert: (r) => r.name === "OntologyRuntimeError",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
