// GENERATED by `onto probe node_0177` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 16 self-validated case(s)
// (each matched the source src/runtime/workflow/predicate-parser.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — parse simple verdict equality predicate",
    setup: () => ("verdict == \"pass\""),
    invoke: (api, ctx) => api.parsePredicate(ctx),
    assert: (r) => r.kind === "verdictEq" && r.value === "pass",
  },
  {
    name: "rule:2 — parse severity equality predicate",
    setup: () => ("severity == 'critical'"),
    invoke: (api, ctx) => api.parsePredicate(ctx),
    assert: (r) => r.kind === "severityEq" && r.value === "critical",
  },
  {
    name: "rule:3 — parse step_count predicate",
    setup: () => ("step_count >= 5"),
    invoke: (api, ctx) => api.parsePredicate(ctx),
    assert: (r) => r.kind === "stepCountGte" && r.n === 5,
  },
  {
    name: "rule:4 — parse since_last predicate",
    setup: () => ("since_last(verdict == \"fail\") >= 3"),
    invoke: (api, ctx) => api.parsePredicate(ctx),
    assert: (r) => r.kind === "sinceLastGte" && r.n === 3 && r.inner.kind === "verdictEq" && r.inner.value === "fail",
  },
  {
    name: "rule:5 — parse consecutive predicate",
    setup: () => ("consecutive(severity == \"warning\", 2)"),
    invoke: (api, ctx) => api.parsePredicate(ctx),
    assert: (r) => r.kind === "consecutive" && r.n === 2 && r.inner.kind === "severityEq" && r.inner.value === "warning",
  },
  {
    name: "rule:6 — parse and expression",
    setup: () => ("verdict == \"fail\" && severity == \"major\""),
    invoke: (api, ctx) => api.parsePredicate(ctx),
    assert: (r) => r.kind === "and" && r.left.kind === "verdictEq" && r.left.value === "fail" && r.right.kind === "severityEq" && r.right.value === "major",
  },
  {
    name: "rule:7 — parse or expression",
    setup: () => ("verdict == \"pass\" || verdict == \"skip\""),
    invoke: (api, ctx) => api.parsePredicate(ctx),
    assert: (r) => r.kind === "or" && r.left.kind === "verdictEq" && r.left.value === "pass" && r.right.kind === "verdictEq" && r.right.value === "skip",
  },
  {
    name: "rule:8 — parse nested parentheses",
    setup: () => ("(verdict == \"fail\" && severity == \"critical\") || step_count >= 10"),
    invoke: (api, ctx) => api.parsePredicate(ctx),
    assert: (r) => r.kind === "or" && r.left.kind === "and" && r.right.kind === "stepCountGte",
  },
  {
    name: "rule:9 — predicateFields for verdictEq",
    setup: () => ({ kind: "verdictEq", value: "pass" } as const),
    invoke: (api, ctx) => api.predicateFields(ctx),
    assert: (r) => r.size === 1 && r.has("verdict"),
  },
  {
    name: "rule:10 — predicateFields for severityEq",
    setup: () => ({ kind: "severityEq", value: "warning" } as const),
    invoke: (api, ctx) => api.predicateFields(ctx),
    assert: (r) => r.size === 1 && r.has("severity"),
  },
  {
    name: "rule:11 — predicateFields for composite and expression",
    setup: () => ({ kind: "and", left: { kind: "verdictEq", value: "fail" }, right: { kind: "severityEq", value: "major" } } as const),
    invoke: (api, ctx) => api.predicateFields(ctx),
    assert: (r) => r.size === 2 && r.has("verdict") && r.has("severity"),
  },
  {
    name: "rule:12 — predicateCanMatchPoint for verdict match",
    setup: () => ({ ast: { kind: "verdictEq", value: "pass" }, point: { verdict: "pass" } }),
    invoke: (api, ctx) => api.predicateCanMatchPoint(ctx.ast, ctx.point),
    assert: (r) => r === true,
  },
  {
    name: "rule:13 — predicateCanMatchPoint for verdict mismatch",
    setup: () => ({ ast: { kind: "verdictEq", value: "pass" }, point: { verdict: "fail" } }),
    invoke: (api, ctx) => api.predicateCanMatchPoint(ctx.ast, ctx.point),
    assert: (r) => r === false,
  },
  {
    name: "rule:14 — predicateCanMatchPoint for sinceLastGte with n=0",
    setup: () => ({ ast: { kind: "sinceLastGte", inner: { kind: "verdictEq", value: "fail" }, n: 0 }, point: { verdict: "pass" } }),
    invoke: (api, ctx) => api.predicateCanMatchPoint(ctx.ast, ctx.point),
    assert: (r) => r === true,
  },
  {
    name: "rule:15 — evaluatePredicate for verdictEq match",
    setup: () => ({ ast: { kind: "verdictEq", value: "pass" }, ctx: { current: { verdict: "pass" }, history: [], stepCount: 0 } }),
    invoke: (api, ctx) => api.evaluatePredicate(ctx.ast, ctx.ctx),
    assert: (r) => r === true,
  },
  {
    name: "rule:16 — evaluatePredicate for stepCountGte satisfied",
    setup: () => ({ ast: { kind: "stepCountGte", n: 5 }, ctx: { current: { verdict: "pass" }, history: [], stepCount: 10 } }),
    invoke: (api, ctx) => api.evaluatePredicate(ctx.ast, ctx.ctx),
    assert: (r) => r === true,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]).has(i));
