// GENERATED by `onto probe node_0054` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/surfaces/commands/ingest/cost-estimate.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — computeCostEstimate returns correct structure for single file",
    setup: () => ({
      files: [{ path: "/a.ts", cwdRelative: "a.ts", sizeChars: 3500 }],
      provider: "anthropic",
      model: "claude-opus-4-7",
    }),
    invoke: (api, ctx) => api.computeCostEstimate(ctx.files, ctx.provider, ctx.model),
    assert: (r) => r.fileCount === 1 && r.perFile.length === 1 && r.totalCostUsd >= 0,
  },
  {
    name: "rule:2 — resolveProviderRate returns correct rate for anthropic opus",
    setup: () => ({ provider: "anthropic", model: "claude-opus-4-7" }),
    invoke: (api, ctx) => api.resolveProviderRate(ctx.provider, ctx.model),
    assert: (r) => r.inputUsdPerMillion === 5.0 && r.outputUsdPerMillion === 25.0,
  },
  {
    name: "rule:3 — estimateInputTokens calculates tokens correctly",
    setup: () => ({ fileSizeChars: 3500 }),
    invoke: (api, ctx) => api.estimateInputTokens(ctx.fileSizeChars),
    assert: (r) => r === Math.ceil(3500 / 3.5) + 50,
  },
  {
    name: "rule:4 — estimateOutputTokens returns fixed estimate",
    setup: () => ({ fileSizeChars: 5000 }),
    invoke: (api, ctx) => api.estimateOutputTokens(ctx.fileSizeChars),
    assert: (r) => r === 400,
  },
  {
    name: "rule:5 — readFileSizeInfos returns correct structure",
    setup: () => ({ filePaths: ["./test.ts"] }),
    invoke: (api, ctx) => api.readFileSizeInfos(ctx.filePaths),
    assert: (r) => r.length === 1 && typeof r[0].sizeChars === "number",
  },
  {
    name: "empty files list in computeCostEstimate",
    setup: () => ({
      files: [],
      provider: "anthropic",
    }),
    invoke: (api, ctx) => api.computeCostEstimate(ctx.files, ctx.provider),
    assert: (r) => r.fileCount === 0 && r.totalCostUsd === (1100 / 1_000_000) * 5.0,
  },
  {
    name: "ollama provider returns zero cost rates",
    setup: () => ({ provider: "ollama", model: "llama3" }),
    invoke: (api, ctx) => api.resolveProviderRate(ctx.provider, ctx.model),
    assert: (r) => r.inputUsdPerMillion === 0 && r.outputUsdPerMillion === 0,
  },
  {
    name: "unknown provider returns zero rates with label",
    setup: () => ({ provider: "unknown-provider" }),
    invoke: (api, ctx) => api.resolveProviderRate(ctx.provider),
    assert: (r) => r.inputUsdPerMillion === 0 && r.outputUsdPerMillion === 0 && r.modelLabel === "unknown-provider (rate unknown)",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
