// GENERATED by `onto probe node_0127` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 4 self-validated case(s)
// (each matched the source src/laws/bakeoff-synthesis.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — synthesizeBakeoff throws when arms array is empty",
    setup: () => [],
    invoke: (api, ctx) => {
      try {
        return api.synthesizeBakeoff(ctx);
      } catch (e) {
        return e instanceof Error ? e.message : "unknown error";
      }
    },
    assert: (r) => r === "synthesizeBakeoff: at least one arm is required (the first is the baseline)",
  },
  {
    name: "rule:2 — synthesizeBakeoff treats first arm as baseline",
    setup: () => {
      const mockReport = {
        total: 1,
        byVerdict: {
          epsilon_equivalent: 0,
          divergent_loc: 0,
          divergent_structural: 0,
          divergent_both: 0,
          unrecoverable: 1,
        },
        results: [
          {
            nodeId: "node1",
            sourceFile: "file1.ts",
            verdict: "unrecoverable" as const,
            ok: false,
          },
        ],
      };

      return [
        { label: "A", report: mockReport },
        { label: "B", report: mockReport },
      ];
    },
    invoke: (api, ctx) => api.synthesizeBakeoff(ctx),
    assert: (r) => r.baselineLabel === "A",
  },
  {
    name: "rule:3 — loadAggregateReport throws on invalid JSON",
    setup: () => "/invalid.json",
    invoke: (api, ctx) => {
      try {
        // Simulate fs.readFileSync returning invalid JSON
        // This requires mocking fs, but since we can't do that, we'll test the error handling path indirectly
        // by calling the function with a path that would cause JSON.parse to fail
        // However, since we can't mock fs, we'll have to skip this or make it trivial
        return api.loadAggregateReport(ctx);
      } catch (e) {
        return e instanceof Error ? e.message : "unknown error";
      }
    },
    assert: (r) => typeof r === "string" && r.includes("loadAggregateReport:") && r.includes("is not valid JSON"),
  },
  {
    name: "rule:4 — renderBakeoffSynthesisMarkdown generates deterministic markdown",
    setup: () => {
      const synthesis = {
        baselineLabel: "A",
        armCount: 2,
        arms: [
          {
            label: "A",
            provider: "providerA",
            model: "modelA",
            total: 100,
            byVerdict: {
              epsilon_equivalent: 10,
              divergent_loc: 20,
              divergent_structural: 30,
              divergent_both: 25,
              unrecoverable: 15,
            },
            microRecoveryRate: 0.8,
            macroRecoveryRate: 0.75,
            exactMatchCount: 5,
            nodesWithMandatory: 90,
            failureModeCounts: {
              missing_exports: 2,
              hallucinated_exports: 1,
              empty_regen: 0,
              compile_back_failed: 3,
              gluing_rejected: 1,
              schema_invalid: 0,
            },
            affectedNodes: 7,
            meanStructuralJaccard: 0.6,
            meanLocDistance: 0.4,
            nodesWithMetrics: 80,
            paretoFrontier: [],
          },
          {
            label: "B",
            provider: "providerB",
            model: "modelB",
            total: 100,
            byVerdict: {
              epsilon_equivalent: 15,
              divergent_loc: 15,
              divergent_structural: 25,
              divergent_both: 30,
              unrecoverable: 15,
            },
            microRecoveryRate: 0.85,
            macroRecoveryRate: 0.8,
            exactMatchCount: 8,
            nodesWithMandatory: 90,
            failureModeCounts: {
              missing_exports: 1,
              hallucinated_exports: 0,
              empty_regen: 0,
              compile_back_failed: 2,
              gluing_rejected: 1,
              schema_invalid: 0,
            },
            affectedNodes: 4,
            meanStructuralJaccard: 0.65,
            meanLocDistance: 0.35,
            nodesWithMetrics: 85,
            paretoFrontier: [],
          },
        ],
        exportRecovery: {
          baselineLabel: "A",
          rows: [
            {
              label: "A",
              microRecoveryRate: 0.8,
              macroRecoveryRate: 0.75,
              microDeltaVsBaseline: 0,
              macroDeltaVsBaseline: 0,
              exactMatchCount: 5,
            },
            {
              label: "B",
              microRecoveryRate: 0.85,
              macroRecoveryRate: 0.8,
              microDeltaVsBaseline: 0.05,
              macroDeltaVsBaseline: 0.05,
              exactMatchCount: 8,
            },
          ],
        },
        failureModes: {
          baselineLabel: "A",
          modes: [
            "missing_exports",
            "hallucinated_exports",
            "empty_regen",
            "compile_back_failed",
            "gluing_rejected",
            "schema_invalid",
          ] as const,
          rows: [
            {
              label: "A",
              counts: {
                missing_exports: 2,
                hallucinated_exports: 1,
                empty_regen: 0,
                compile_back_failed: 3,
                gluing_rejected: 1,
                schema_invalid: 0,
              },
              deltaVsBaseline: null,
            },
            {
              label: "B",
              counts: {
                missing_exports: 1,
                hallucinated_exports: 0,
                empty_regen: 0,
                compile_back_failed: 2,
                gluing_rejected: 1,
                schema_invalid: 0,
              },
              deltaVsBaseline: {
                missing_exports: -1,
                hallucinated_exports: -1,
                empty_regen: 0,
                compile_back_failed: -1,
                gluing_rejected: 0,
                schema_invalid: 0,
              },
            },
          ],
        },
        perFile: [
          {
            sourceFile: "file1.ts",
            nodeId: "node1",
            perArm: [
              {
                label: "A",
                verdict: "epsilon_equivalent",
                structuralJaccard: 0.9,
              },
              {
                label: "B",
                verdict: "epsilon_equivalent",
                structuralJaccard: 0.95,
              },
            ],
            trend: "improved" as const,
          },
        ],
        h1: {
          jaccardFloor: 0.1,
          perArm: [
            {
              label: "A",
              meanStructuralJaccard: 0.6,
              passes: true,
            },
            {
              label: "B",
              meanStructuralJaccard: 0.65,
              passes: true,
            },
          ],
          allPass: true,
          anyPass: true,
        },
      };

      return synthesis;
    },
    invoke: (api, ctx) => api.renderBakeoffSynthesisMarkdown(ctx),
    assert: (r) => typeof r === "string" && r.includes("# Move 3α bake-off synthesis") && r.includes("| Arm | Provider | Model | Nodes | Mean Jaccard | Mean LoC dist |"),
  },
  {
    name: "synthesizeBakeoff with single arm produces valid synthesis",
    setup: () => {
      const mockReport = {
        total: 1,
        byVerdict: {
          epsilon_equivalent: 1,
          divergent_loc: 0,
          divergent_structural: 0,
          divergent_both: 0,
          unrecoverable: 0,
        },
        results: [
          {
            nodeId: "node1",
            sourceFile: "file1.ts",
            verdict: "epsilon_equivalent" as const,
            ok: true,
            metrics: {
              structuralJaccard: 0.9,
              locDistance: 0.1,
            },
          },
        ],
      };

      return [{ label: "A", report: mockReport }];
    },
    invoke: (api, ctx) => api.synthesizeBakeoff(ctx),
    assert: (r) => r.armCount === 1 && r.baselineLabel === "A" && r.arms[0].label === "A",
  },
  {
    name: "synthesizeBakeoff computes correct export recovery deltas",
    setup: () => {
      const mockReportA = {
        total: 1,
        byVerdict: {
          epsilon_equivalent: 0,
          divergent_loc: 0,
          divergent_structural: 0,
          divergent_both: 0,
          unrecoverable: 1,
        },
        exportRecovery: {
          microRecoveryRate: 0.5,
          macroRecoveryRate: 0.6,
          exactMatchCount: 3,
          nodesWithMandatory: 10,
        },
        results: [
          {
            nodeId: "node1",
            sourceFile: "file1.ts",
            verdict: "unrecoverable" as const,
            ok: false,
          },
        ],
      };

      const mockReportB = {
        total: 1,
        byVerdict: {
          epsilon_equivalent: 0,
          divergent_loc: 0,
          divergent_structural: 0,
          divergent_both: 0,
          unrecoverable: 1,
        },
        exportRecovery: {
          microRecoveryRate: 0.7,
          macroRecoveryRate: 0.8,
          exactMatchCount: 5,
          nodesWithMandatory: 10,
        },
        results: [
          {
            nodeId: "node1",
            sourceFile: "file1.ts",
            verdict: "unrecoverable" as const,
            ok: false,
          },
        ],
      };

      return [
        { label: "A", report: mockReportA },
        { label: "B", report: mockReportB },
      ];
    },
    invoke: (api, ctx) => api.synthesizeBakeoff(ctx),
    assert: (r) => {
      const baselineRow = r.exportRecovery.rows[0];
      const armRow = r.exportRecovery.rows[1];
      return (
        baselineRow.microDeltaVsBaseline === 0 &&
        baselineRow.macroDeltaVsBaseline === 0 &&
        armRow.microDeltaVsBaseline === 0.2 &&
        armRow.macroDeltaVsBaseline === 0.2
      );
    },
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 3, 4]).has(i));
