// GENERATED by `onto probe node_0136` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/laws/pareto.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { PerNodeMatrix } from "../../src/laws/matrix.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — empty input produces empty output",
    setup: () => [],
    invoke: (api) => api.aggregateByTaskModel([]),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
  {
    name: "rule:2 — single node with valid honesty computes correct aggregate",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        {
          cell: {
            cost: {
              provider: "anthropic",
              model: "claude-3",
              task: "code_sketch",
              inputTokens: 100,
              outputTokens: 50,
              usd: 0.02,
              wallClockMs: 1000,
            },
          },
          honesty: {
            structural: 0.9,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
      ];
      return matrix;
    },
    invoke: (api, ctx) => api.aggregateByTaskModel(ctx),
    assert: (r) => {
      return (
        Array.isArray(r) &&
        r.length === 1 &&
        r[0].task === "code_sketch" &&
        r[0].provider === "anthropic" &&
        r[0].model === "claude-3" &&
        r[0].n === 1 &&
        r[0].meanHonestyStructural === 0.9 &&
        r[0].honestyN === 1 &&
        r[0].meanUsdPerNode === 0.02 &&
        r[0].meanInputTokensPerNode === 100 &&
        r[0].meanOutputTokensPerNode === 50 &&
        r[0].paretoFrontier === true
      );
    },
  },
  {
    name: "rule:3 — multiple nodes same bucket aggregates correctly",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        {
          cell: {
            cost: {
              provider: "openai",
              model: "gpt-4",
              task: "semantic_parse",
              inputTokens: 200,
              outputTokens: 100,
              usd: 0.03,
              wallClockMs: 1500,
            },
          },
          honesty: {
            structural: 0.85,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
        {
          cell: {
            cost: {
              provider: "openai",
              model: "gpt-4",
              task: "semantic_parse",
              inputTokens: 300,
              outputTokens: 150,
              usd: 0.05,
              wallClockMs: 2000,
            },
          },
          honesty: {
            structural: 0.75,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
      ];
      return matrix;
    },
    invoke: (api, ctx) => api.aggregateByTaskModel(ctx),
    assert: (r) => {
      return (
        Array.isArray(r) &&
        r.length === 1 &&
        r[0].n === 2 &&
        r[0].meanHonestyStructural === 0.8 &&
        r[0].honestyN === 2 &&
        r[0].meanUsdPerNode === 0.04 &&
        r[0].meanInputTokensPerNode === 250 &&
        r[0].meanOutputTokensPerNode === 125
      );
    },
  },
  {
    name: "rule:4 — null honesty entries excluded from mean but counted in n",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        {
          cell: {
            cost: {
              provider: "mock",
              model: "test-model",
              task: "test_task",
              inputTokens: 10,
              outputTokens: 5,
              usd: 0.001,
              wallClockMs: 100,
            },
          },
          honesty: {
            structural: null,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
        {
          cell: {
            cost: {
              provider: "mock",
              model: "test-model",
              task: "test_task",
              inputTokens: 20,
              outputTokens: 10,
              usd: 0.002,
              wallClockMs: 200,
            },
          },
          honesty: {
            structural: 0.95,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
      ];
      return matrix;
    },
    invoke: (api, ctx) => api.aggregateByTaskModel(ctx),
    assert: (r) => {
      return (
        Array.isArray(r) &&
        r.length === 1 &&
        r[0].n === 2 &&
        r[0].meanHonestyStructural === 0.95 &&
        r[0].honestyN === 1 &&
        r[0].meanUsdPerNode === 0.0015 &&
        r[0].meanInputTokensPerNode === 15 &&
        r[0].meanOutputTokensPerNode === 7.5
      );
    },
  },
  {
    name: "rule:5 — Pareto frontier correctly marked with dominance",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        // Model A: high cost, high honesty
        {
          cell: {
            cost: {
              provider: "providerA",
              model: "modelA",
              task: "task1",
              inputTokens: 1000,
              outputTokens: 500,
              usd: 0.1,
              wallClockMs: 5000,
            },
          },
          honesty: {
            structural: 0.95,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
        // Model B: low cost, low honesty (dominated by A)
        {
          cell: {
            cost: {
              provider: "providerB",
              model: "modelB",
              task: "task1",
              inputTokens: 500,
              outputTokens: 250,
              usd: 0.05,
              wallClockMs: 2500,
            },
          },
          honesty: {
            structural: 0.8,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
      ];
      return matrix;
    },
    invoke: (api, ctx) => api.aggregateByTaskModel(ctx),
    assert: (r) => {
      if (!Array.isArray(r) || r.length !== 2) return false;
      const modelA = r.find(
        (item) => item.provider === "providerA" && item.model === "modelA"
      );
      const modelB = r.find(
        (item) => item.provider === "providerB" && item.model === "modelB"
      );
      return (
        modelA !== undefined &&
        modelB !== undefined &&
        modelA.paretoFrontier === true &&
        modelB.paretoFrontier === false
      );
    },
  },
  {
    name: "rule:6 — sorting by task, then honesty desc, then cost asc",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        {
          cell: {
            cost: {
              provider: "p1",
              model: "m1",
              task: "taskB",
              inputTokens: 100,
              outputTokens: 50,
              usd: 0.03,
              wallClockMs: 1000,
            },
          },
          honesty: {
            structural: 0.8,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
        {
          cell: {
            cost: {
              provider: "p2",
              model: "m2",
              task: "taskA",
              inputTokens: 200,
              outputTokens: 100,
              usd: 0.04,
              wallClockMs: 2000,
            },
          },
          honesty: {
            structural: 0.7,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
        {
          cell: {
            cost: {
              provider: "p3",
              model: "m3",
              task: "taskA",
              inputTokens: 150,
              outputTokens: 75,
              usd: 0.02,
              wallClockMs: 1500,
            },
          },
          honesty: {
            structural: 0.9,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
      ];
      return matrix;
    },
    invoke: (api, ctx) => api.aggregateByTaskModel(ctx),
    assert: (r) => {
      return (
        Array.isArray(r) &&
        r.length === 3 &&
        r[0].task === "taskA" &&
        r[0].meanHonestyStructural === 0.9 &&
        r[1].task === "taskA" &&
        r[1].meanHonestyStructural === 0.7 &&
        r[2].task === "taskB"
      );
    },
  },
  {
    name: "rule:7 — entries with null honesty never on Pareto frontier",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        {
          cell: {
            cost: {
              provider: "p1",
              model: "m1",
              task: "task1",
              inputTokens: 100,
              outputTokens: 50,
              usd: 0.02,
              wallClockMs: 1000,
            },
          },
          honesty: {
            structural: null,
            contract: null,
            behavior: null,
            intent: null,
          },
        },
      ];
      return matrix;
    },
    invoke: (api, ctx) => api.aggregateByTaskModel(ctx),
    assert: (r) => {
      return (
        Array.isArray(r) &&
        r.length === 1 &&
        r[0].meanHonestyStructural === null &&
        r[0].paretoFrontier === false
      );
    },
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 5, 6]).has(i));
