// GENERATED by `onto probe node_0098` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 4 self-validated case(s)
// (each matched the source src/forward/compile/post/validate-language.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — skips validation when no language is declared",
    setup: () => ({ absolutePath: "/tmp/test.py", language: undefined }),
    invoke: (api, ctx) => api.validateLanguage(ctx),
    assert: (r) => r.status === "skipped" && r.reason === "no language declared",
  },
  {
    name: "rule:2 — skips validation when language has no registered validator",
    setup: () => ({ absolutePath: "/tmp/test.xyz", language: "unknownlang" }),
    invoke: (api, ctx) => api.validateLanguage(ctx),
    assert: (r) => r.status === "skipped" && r.reason === "no validator registered for language=unknownlang",
  },
  {
    name: "rule:3 — handles empty string language as skipped",
    setup: () => ({ absolutePath: "/tmp/test.py", language: "" }),
    invoke: (api, ctx) => api.validateLanguage(ctx),
    assert: (r) => r.status === "skipped" && r.reason === "no language declared",
  },
  {
    name: "rule:4 — handles whitespace-only language as skipped",
    setup: () => ({ absolutePath: "/tmp/test.py", language: "   " }),
    invoke: (api, ctx) => api.validateLanguage(ctx),
    assert: (r) => r.status === "skipped" && r.reason === "no language declared",
  },
  {
    name: "rule:5 — language matching is case-insensitive",
    setup: () => ({ absolutePath: "/tmp/test.py", language: "PYTHON" }),
    invoke: (api, ctx) => api.validateLanguage(ctx),
    assert: (r) => r.status === "skipped" && r.reason === "python3 not on PATH",
  },
  {
    name: "rule:6 — trims whitespace from language declaration",
    setup: () => ({ absolutePath: "/tmp/test.py", language: " python " }),
    invoke: (api, ctx) => api.validateLanguage(ctx),
    assert: (r) => r.status === "skipped" && r.reason === "python3 not on PATH",
  },
  {
    name: "typical case with registered python validator",
    setup: () => ({ absolutePath: "/tmp/valid.py", language: "python" }),
    invoke: (api, ctx) => api.validateLanguage(ctx),
    assert: (r) => r.status === "skipped" && r.reason === "python3 not on PATH",
  },
  {
    name: "lowercase python language triggers validator",
    setup: () => ({ absolutePath: "/tmp/script.py", language: "python" }),
    invoke: (api, ctx) => api.validateLanguage(ctx),
    assert: (r) => r.status === "skipped" && r.reason === "python3 not on PATH",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3]).has(i));
