// GENERATED by `onto probe node_0223` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/runtime/llm/ensemble.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/runtime/legend/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "empty candidates array returns undefined",
    setup: () => ({ candidates: [] as number[], score: (c: number) => c }),
    invoke: (api, ctx) => (api as any).selectBestByScore(ctx.candidates, ctx.score),
    assert: (r) => r === undefined,
  },
  {
    name: "single element returns index 0",
    setup: () => ({ candidates: [42], score: (c: number) => c }),
    invoke: (api, ctx) => (api as any).selectBestByScore(ctx.candidates, ctx.score),
    assert: (r) => r === 0,
  },
  {
    name: "highest score in the middle returns its index",
    setup: () => ({ candidates: [1, 5, 3, 2], score: (c: number) => c }),
    invoke: (api, ctx) => (api as any).selectBestByScore(ctx.candidates, ctx.score),
    assert: (r) => r === 1,
  },
  {
    name: "highest score is the last element",
    setup: () => ({ candidates: [1, 2, 3, 9], score: (c: number) => c }),
    invoke: (api, ctx) => (api as any).selectBestByScore(ctx.candidates, ctx.score),
    assert: (r) => r === 3,
  },
  {
    name: "ties resolve to earliest index (strict greater-than only)",
    setup: () => ({ candidates: [5, 5, 5], score: (c: number) => c }),
    invoke: (api, ctx) => (api as any).selectBestByScore(ctx.candidates, ctx.score),
    assert: (r) => r === 0,
  },
  {
    name: "two equal maxima — earliest of the tied maxima wins",
    setup: () => ({ candidates: [1, 7, 3, 7], score: (c: number) => c }),
    invoke: (api, ctx) => (api as any).selectBestByScore(ctx.candidates, ctx.score),
    assert: (r) => r === 1,
  },
  {
    name: "score function can map objects to numbers",
    setup: () => ({
      candidates: [{ n: 2 }, { n: 8 }, { n: 4 }],
      score: (c: { n: number }) => c.n,
    }),
    invoke: (api, ctx) => (api as any).selectBestByScore(ctx.candidates, ctx.score),
    assert: (r) => r === 1,
  },
  {
    name: "negative scores — least-negative (largest) wins",
    setup: () => ({ candidates: [-5, -1, -3], score: (c: number) => c }),
    invoke: (api, ctx) => (api as any).selectBestByScore(ctx.candidates, ctx.score),
    assert: (r) => r === 1,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
