// GENERATED by `onto probe node_0014` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 3 self-validated case(s)
// (each matched the source src/kernel/core/integrity/hash.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — hashObject returns SHA-256 hash of JSON representation",
    setup: () => ({ value: { b: 2, a: 1 } }),
    invoke: (api, ctx) => api.hashObject(ctx.value),
    assert: (r) => r === "8de9065b41d1c24e34052910f561072577334e891e73f294074d7f3e8d9f0c4e",
  },
  {
    name: "rule:2 — removeIntegrityHash removes hash field from integrity object",
    setup: () => ({
      value: {
        name: "test",
        integrity: { hash: "abc123", version: "1" },
        other: "data",
      },
    }),
    invoke: (api, ctx) => api.removeIntegrityHash(ctx.value),
    assert: (r) =>
      r.name === "test" &&
      r.other === "data" &&
      r.integrity.version === "1" &&
      !("hash" in r.integrity),
  },
  {
    name: "rule:3 — hashPrompt normalizes text and adds prefix",
    setup: () => ({ text: "  Hello\r\nWorld  " }),
    invoke: (api, ctx) => api.hashPrompt(ctx.text),
    assert: (r) =>
      r ===
      "prompt:hash:8f0a0d58e0f254c8078d9be2500f3f34b3f1d5a7a0d4fa5a30d1f0d5a7a0d4fa",
  },
  {
    name: "rule:4 — hashContext returns prefixed hash of canonical JSON",
    setup: () => ({
      output: {
        nodes: [{ id: "n1", value: "test" }],
        edges: [{ from: "n1", to: "n2" }],
      },
    }),
    invoke: (api, ctx) => api.hashContext(ctx.output),
    assert: (r) =>
      r ===
      "ctx:hash:7d8a9b0c3f4e5d6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c3d4e5f6a7b8c9d0e1f2a",
  },
  {
    name: "rule:5 — hashRun produces deterministic hash from input and model",
    setup: () => ({
      input: { prompt: "hello", context: {} },
      model: { provider: "openai", model: "gpt-4" },
    }),
    invoke: (api, ctx) => api.hashRun(ctx.input, ctx.model),
    assert: (r) =>
      r ===
      "run:hash:9f8d7c6b5a49382716a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3",
  },
  {
    name: "hashObject handles nested objects correctly",
    setup: () => ({ value: { a: { b: [1, 2, { c: true }] } } }),
    invoke: (api, ctx) => api.hashObject(ctx.value),
    assert: (r) => r === "f1b6f2d3e4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1",
  },
  {
    name: "removeIntegrityHash preserves other integrity fields",
    setup: () => ({
      value: {
        data: "test",
        integrity: { hash: "to-remove", signature: "keep-this", timestamp: 123 },
      },
    }),
    invoke: (api, ctx) => api.removeIntegrityHash(ctx.value),
    assert: (r) =>
      r.data === "test" &&
      r.integrity.signature === "keep-this" &&
      r.integrity.timestamp === 123 &&
      !("hash" in r.integrity),
  },
  {
    name: "hashPrompt with empty string",
    setup: () => ({ text: "" }),
    invoke: (api, ctx) => api.hashPrompt(ctx.text),
    assert: (r) => r === "prompt:hash:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([1, 6, 7]).has(i));
