// GENERATED by `onto probe node_0157` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/surfaces/mcp/server.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — createOntologyMcpServer returns an McpServer instance with correct name and version",
    setup: () => ({}),
    invoke: (api, ctx) => {
      // Mock process.cwd() and fs.existsSync for deterministic behavior
      const originalCwd = process.cwd;
      const originalExistsSync = require("node:fs").existsSync;
      process.cwd = () => "/mock/cwd";
      require("node:fs").existsSync = () => true;

      try {
        const server = (api as any).createOntologyMcpServer("/mock/cwd");
        return {
          name: server.name,
          version: server.version,
        };
      } finally {
        process.cwd = originalCwd;
        require("node:fs").existsSync = originalExistsSync;
      }
    },
    assert: (r) => r.name === "ontology" && r.version === "0.4.0",
  },
  {
    name: "rule:2 — ONTOLOGY_MCP_NAME is 'ontology'",
    setup: () => ({}),
    invoke: (api, ctx) => (api as any).ONTOLOGY_MCP_NAME,
    assert: (r) => r === "ontology",
  },
  {
    name: "rule:3 — ONTOLOGY_MCP_VERSION is '0.4.0'",
    setup: () => ({}),
    invoke: (api, ctx) => (api as any).ONTOLOGY_MCP_VERSION,
    assert: (r) => r === "0.4.0",
  },
  {
    name: "rule:4 — createOntologyMcpServer throws when cwd is not an Ontology project",
    setup: () => ({}),
    invoke: (api, ctx) => {
      // Mock fs.existsSync to simulate missing state file
      const originalExistsSync = require("node:fs").existsSync;
      require("node:fs").existsSync = () => false;

      try {
        (api as any).createOntologyMcpServer("/invalid/cwd");
        return "did-not-throw";
      } catch (err: any) {
        return err.message;
      } finally {
        require("node:fs").existsSync = originalExistsSync;
      }
    },
    assert: (r) => r.includes("Not an Ontology project"),
  },
  {
    name: "rule:5 — createOntologyMcpServer registers ontology tools",
    setup: () => ({}),
    invoke: (api, ctx) => {
      // Mock process.cwd() and fs.existsSync for deterministic behavior
      const originalCwd = process.cwd;
      const originalExistsSync = require("node:fs").existsSync;
      process.cwd = () => "/mock/cwd";
      require("node:fs").existsSync = () => true;

      try {
        const server = (api as any).createOntologyMcpServer("/mock/cwd");
        // Accessing private property for testing purposes only
        return Object.keys((server as any)._tools ?? {}).length > 0;
      } finally {
        process.cwd = originalCwd;
        require("node:fs").existsSync = originalExistsSync;
      }
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:6 — createOntologyMcpServer registers canon resource",
    setup: () => ({}),
    invoke: (api, ctx) => {
      // Mock process.cwd() and fs.existsSync for deterministic behavior
      const originalCwd = process.cwd;
      const originalExistsSync = require("node:fs").existsSync;
      process.cwd = () => "/mock/cwd";
      require("node:fs").existsSync = () => true;

      try {
        const server = (api as any).createOntologyMcpServer("/mock/cwd");
        // Accessing private property for testing purposes only
        return "canon" in ((server as any)._resources ?? {});
      } finally {
        process.cwd = originalCwd;
        require("node:fs").existsSync = originalExistsSync;
      }
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:7 — createOntologyMcpServer registers overview resource",
    setup: () => ({}),
    invoke: (api, ctx) => {
      // Mock process.cwd() and fs.existsSync for deterministic behavior
      const originalCwd = process.cwd;
      const originalExistsSync = require("node:fs").existsSync;
      process.cwd = () => "/mock/cwd";
      require("node:fs").existsSync = () => true;

      try {
        const server = (api as any).createOntologyMcpServer("/mock/cwd");
        // Accessing private property for testing purposes only
        return "overview" in ((server as any)._resources ?? {});
      } finally {
        process.cwd = originalCwd;
        require("node:fs").existsSync = originalExistsSync;
      }
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:8 — createOntologyMcpServer performs no transport I/O",
    setup: () => ({}),
    invoke: (api, ctx) => {
      // Mock process.cwd() and fs.existsSync for deterministic behavior
      const originalCwd = process.cwd;
      const originalExistsSync = require("node:fs").existsSync;
      process.cwd = () => "/mock/cwd";
      require("node:fs").existsSync = () => true;

      try {
        const server = (api as any).createOntologyMcpServer("/mock/cwd");
        // Check that server does not have a transport attached by default
        return (server as any)._transport === undefined;
      } finally {
        process.cwd = originalCwd;
        require("node:fs").existsSync = originalExistsSync;
      }
    },
    assert: (r) => r === true,
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
