// GENERATED by `onto probe node_0178` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 10 self-validated case(s)
// (each matched the source src/runtime/workflow/verifier-schemas.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — verifierSchemaFields returns correct fields for simple-pass-fail",
    setup: () => ("simple-pass-fail" as const),
    invoke: (api, ctx) => api.verifierSchemaFields(ctx),
    assert: (r) => r instanceof Set && r.size === 1 && r.has("verdict"),
  },
  {
    name: "rule:1 — verifierSchemaFields returns correct fields for with-severity",
    setup: () => ("with-severity" as const),
    invoke: (api, ctx) => api.verifierSchemaFields(ctx),
    assert: (r) =>
      r instanceof Set &&
      r.size === 2 &&
      r.has("verdict") &&
      r.has("severity"),
  },
  {
    name: "rule:2 — verifierSchemaPoints returns correct points for simple-pass-fail",
    setup: () => ("simple-pass-fail" as const),
    invoke: (api, ctx) => api.verifierSchemaPoints(ctx),
    assert: (r) =>
      Array.isArray(r) &&
      r.length === 2 &&
      r.some((p) => p.verdict === "pass" && !p.severity) &&
      r.some((p) => p.verdict === "fail" && !p.severity),
  },
  {
    name: "rule:2 — verifierSchemaPoints returns correct points for with-severity",
    setup: () => ("with-severity" as const),
    invoke: (api, ctx) => api.verifierSchemaPoints(ctx),
    assert: (r) =>
      Array.isArray(r) &&
      r.length === 6 &&
      r.some((p) => p.verdict === "pass" && !p.severity) &&
      r.some((p) => p.verdict === "fail" && !p.severity) &&
      r.some(
        (p) => p.verdict === "pass" && p.severity === "minor",
      ) &&
      r.some(
        (p) => p.verdict === "pass" && p.severity === "major",
      ) &&
      r.some(
        (p) => p.verdict === "fail" && p.severity === "minor",
      ) &&
      r.some(
        (p) => p.verdict === "fail" && p.severity === "major",
      ),
  },
  {
    name: "rule:3 — parseVerdict parses valid simple-pass-fail verdict",
    setup: () => ({
      name: "simple-pass-fail" as const,
      raw: { verdict: "pass", reason: "all good" },
    }),
    invoke: (api, ctx) => api.parseVerdict(ctx.name, ctx.raw),
    assert: (r) =>
      typeof r === "object" &&
      r !== null &&
      "verdict" in r &&
      r.verdict === "pass" &&
      (!("reason" in r) || r.reason === "all good"),
  },
  {
    name: "rule:3 — parseVerdict throws on invalid simple-pass-fail verdict",
    setup: () => ({
      name: "simple-pass-fail" as const,
      raw: { verdict: "unknown" },
    }),
    invoke: (api, ctx) => {
      try {
        api.parseVerdict(ctx.name, ctx.raw);
        return false;
      } catch {
        return true;
      }
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:3 — parseVerdict parses valid with-severity verdict",
    setup: () => ({
      name: "with-severity" as const,
      raw: { verdict: "fail", severity: "major", issues: ["issue1"] },
    }),
    invoke: (api, ctx) => api.parseVerdict(ctx.name, ctx.raw),
    assert: (r) =>
      typeof r === "object" &&
      r !== null &&
      "verdict" in r &&
      r.verdict === "fail" &&
      "severity" in r &&
      r.severity === "major" &&
      "issues" in r &&
      Array.isArray(r.issues) &&
      r.issues.includes("issue1"),
  },
  {
    name: "rule:4 — extractJsonObject extracts valid JSON from text",
    setup: () => '{"verdict":"pass","reason":"all good"}',
    invoke: (api, ctx) => api.extractJsonObject(ctx),
    assert: (r) =>
      typeof r === "object" &&
      r !== null &&
      "verdict" in r &&
      r.verdict === "pass",
  },
  {
    name: "rule:4 — extractJsonObject returns null for invalid JSON",
    setup: () => '{"verdict":"pass",invalid}',
    invoke: (api, ctx) => api.extractJsonObject(ctx),
    assert: (r) => r === null,
  },
  {
    name: "rule:4 — extractJsonObject returns null when no JSON object found",
    setup: () => "no json here",
    invoke: (api, ctx) => api.extractJsonObject(ctx),
    assert: (r) => r === null,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).has(i));
