// GENERATED by `onto probe node_0155` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/runtime/llm/resolve-node-model.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns ref_not_found when model id does not exist",
    setup: () => ({
      ref: "nonexistent_model",
      registry: {
        models: [
          {
            id: "existing_model",
            provider: "mock",
            name: "mock_model_name",
          },
        ],
      },
    }),
    invoke: (api, ctx) => api.resolveNodeModel(ctx.ref, ctx.registry),
    assert: (r) => r.ok === false && r.reason === "ref_not_found",
  },
  {
    name: "rule:2 — returns unsupported_provider when provider is not in DISPATCHABLE_PROVIDERS",
    setup: () => ({
      ref: "unsupported_model",
      registry: {
        models: [
          {
            id: "unsupported_model",
            provider: "openai",
            name: "gpt-4",
          },
        ],
      },
    }),
    invoke: (api, ctx) => api.resolveNodeModel(ctx.ref, ctx.registry),
    assert: (r) => r.ok === false && r.reason === "unsupported_provider",
  },
  {
    name: "rule:3 — returns resolved model when ref exists and provider is supported",
    setup: () => ({
      ref: "valid_model",
      registry: {
        models: [
          {
            id: "valid_model",
            provider: "ollama",
            name: "llama3.2:3b",
          },
        ],
      },
    }),
    invoke: (api, ctx) => api.resolveNodeModel(ctx.ref, ctx.registry),
    assert: (r) => r.ok === true && r.resolved.provider === "ollama" && r.resolved.model === "llama3.2:3b",
  },
  {
    name: "rule:4 — returns resolved model with literal provider when entry has literal provider",
    setup: () => ({
      ref: "literal_model",
      registry: {
        models: [
          {
            id: "literal_model",
            provider: "literal",
            name: "literal_value",
          },
        ],
      },
    }),
    invoke: (api, ctx) => api.resolveNodeModel(ctx.ref, ctx.registry),
    assert: (r) => r.ok === true && r.resolved.provider === "literal" && r.resolved.model === "literal_value",
  },
  {
    name: "rule:5 — returns resolved model with anthropic provider when entry has anthropic provider",
    setup: () => ({
      ref: "anthropic_model",
      registry: {
        models: [
          {
            id: "anthropic_model",
            provider: "anthropic",
            name: "claude-3-opus",
          },
        ],
      },
    }),
    invoke: (api, ctx) => api.resolveNodeModel(ctx.ref, ctx.registry),
    assert: (r) => r.ok === true && r.resolved.provider === "anthropic" && r.resolved.model === "claude-3-opus",
  },
  {
    name: "rule:6 — returns resolved model with mock provider when entry has mock provider",
    setup: () => ({
      ref: "mock_model",
      registry: {
        models: [
          {
            id: "mock_model",
            provider: "mock",
            name: "deterministic-mock-model",
          },
        ],
      },
    }),
    invoke: (api, ctx) => api.resolveNodeModel(ctx.ref, ctx.registry),
    assert: (r) => r.ok === true && r.resolved.provider === "mock" && r.resolved.model === "deterministic-mock-model",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5]).has(i));
