// GENERATED by `onto probe node_0022` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/core/project/paths.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "cwd is echoed back unchanged",
    setup: () => ({ cwd: "/proj" }),
    invoke: (api, ctx) => (api as any).getOntologyPaths(ctx.cwd),
    assert: (r) => r.cwd === "/proj",
  },
  {
    name: "ontologyDir is cwd/.ontology",
    setup: () => ({ cwd: "/proj" }),
    invoke: (api, ctx) => (api as any).getOntologyPaths(ctx.cwd),
    assert: (r) => r.ontologyDir === "/proj/.ontology",
  },
  {
    name: "top-level json files under .ontology",
    setup: () => ({ cwd: "/proj" }),
    invoke: (api, ctx) => (api as any).getOntologyPaths(ctx.cwd),
    assert: (r) =>
      r.statePath === "/proj/.ontology/state.json" &&
      r.eventsPath === "/proj/.ontology/events.jsonl" &&
      r.edgesPath === "/proj/.ontology/edges.jsonl",
  },
  {
    name: "draftsDir is nested under work/drafts",
    setup: () => ({ cwd: "/proj" }),
    invoke: (api, ctx) => (api as any).getOntologyPaths(ctx.cwd),
    assert: (r) => r.draftsDir === "/proj/.ontology/work/drafts",
  },
  {
    name: "asset subdirectories nest under assetsDir",
    setup: () => ({ cwd: "/proj" }),
    invoke: (api, ctx) => (api as any).getOntologyPaths(ctx.cwd),
    assert: (r) =>
      r.assetsDir === "/proj/.ontology/assets" &&
      r.imagesDir === "/proj/.ontology/assets/images" &&
      r.audioDir === "/proj/.ontology/assets/audio" &&
      r.videoDir === "/proj/.ontology/assets/video" &&
      r.filesDir === "/proj/.ontology/assets/files" &&
      r.datasetsDir === "/proj/.ontology/assets/datasets",
  },
  {
    name: "registry paths nest under their dirs",
    setup: () => ({ cwd: "/proj" }),
    invoke: (api, ctx) => (api as any).getOntologyPaths(ctx.cwd),
    assert: (r) =>
      r.modelsRegistryPath === "/proj/.ontology/models/registry.json" &&
      r.processorsRegistryPath === "/proj/.ontology/processors/registry.json",
  },
  {
    name: "drift and embedding nested files",
    setup: () => ({ cwd: "/proj" }),
    invoke: (api, ctx) => (api as any).getOntologyPaths(ctx.cwd),
    assert: (r) =>
      r.driftDir === "/proj/.ontology/drift" &&
      r.driftSnapshotPath === "/proj/.ontology/drift/snapshot.json" &&
      r.embeddingsDir === "/proj/.ontology/embeddings" &&
      r.embeddingIndexPath === "/proj/.ontology/embeddings/index.json",
  },
  {
    name: "report subdirectories and generated artifacts",
    setup: () => ({ cwd: "/proj" }),
    invoke: (api, ctx) => (api as any).getOntologyPaths(ctx.cwd),
    assert: (r) =>
      r.reportsDir === "/proj/.ontology/reports" &&
      r.validationReportsDir === "/proj/.ontology/reports/validations" &&
      r.compilationReportsDir === "/proj/.ontology/reports/compilations" &&
      r.generatedArtifactsDir === "/proj/.ontology/artifacts/generated",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
