// GENERATED by `onto probe node_0118` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/kernel/graph/edge-materialization-preview.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — planEdgeMaterialization returns deterministic output across input permutations",
    setup: () => {
      const nodes = [
        { id: "a", outputs: { files: ["a.ts"] }, coordinates: { branch: "main" } },
        { id: "b", outputs: { files: ["b.ts"] }, coordinates: { branch: "main" } },
      ];
      const edges = [{ from: "a", to: "b", type: "depends_on" }];
      const inferredEdges = [
        { fromFile: "/project/a.ts", toFile: "/project/b.ts", type: "uses_token", tokens: ["x"] },
      ];
      const relativize = (p: string) => p.replace("/project/", "");
      return { nodes, edges, inferredEdges, relativize };
    },
    invoke: (api, ctx) => api.planEdgeMaterialization(ctx),
    assert: (r) => r.schemaVersion === "1.0",
  },
  {
    name: "rule:2 — tripleKey produces deterministic string key from inputs",
    setup: () => ({ from: "nodeA", to: "nodeB", type: "depends_on" }),
    invoke: (api, ctx) => (api as any).tripleKey(ctx.from, ctx.to, ctx.type),
    assert: (r) => r === "nodeA|nodeB|depends_on",
  },
  {
    name: "rule:3 — buildVirtualEdges preserves existing edges and appends resolved ones",
    setup: () => {
      const existing = [{ from: "x", to: "y", type: "existing" }] as any;
      const resolved = [{ fromNodeId: "a", toNodeId: "b", type: "inferred" }] as any;
      return { existing, resolved };
    },
    invoke: (api, ctx) => (api as any).buildVirtualEdges(ctx.existing, ctx.resolved),
    assert: (r) => r.length === 2 && r[0].from === "x" && r[1].from === "a",
  },
  {
    name: "rule:4 — snapshot correctly maps HierarchyMetrics to MetricsSnapshot",
    setup: () => ({
      topology: { nodeCount: 5, edgeCount: 8, maxDepth: 3, averageDepth: 1.6 },
      flatness: { nonRootDirectChildrenOfRootRatio: 0.4, isolatedNodeRatio: 0.2, verdict: "flat" as const },
      contracts: {
        closedWorldGlobalSatisfaction: { ratio: 0.75 },
        closedWorldContextReachableSatisfaction: { ratio: 0.6 },
        topClosedWorldUnreachableRequires: [{ source: "s1", consumers: 2 }],
      }
    }),
    invoke: (api, ctx) => (api as any).snapshot(ctx),
    assert: (r) => r.nodeCount === 5 && r.edgeCount === 8 && r.verdict === "flat",
  },
  {
    name: "empty inferred edges produces empty resolved/skipped lists",
    setup: () => {
      const nodes = [{ id: "n1", outputs: { files: ["f1"] }, coordinates: { branch: "main" } }];
      const edges = [];
      const inferredEdges = [];
      const relativize = (p: string) => p;
      return { nodes, edges, inferredEdges, relativize };
    },
    invoke: (api, ctx) => api.planEdgeMaterialization(ctx),
    assert: (r) => r.resolved.length === 0 && r.skipped.length === 0,
  },
  {
    name: "missing node causes skip with reason from_node_missing",
    setup: () => {
      const nodes = [{ id: "n1", outputs: { files: ["f1"] }, coordinates: { branch: "main" } }];
      const edges = [];
      const inferredEdges = [{ fromFile: "/f2", toFile: "/f1", type: "depends_on", tokens: [] }];
      const relativize = (p: string) => p.replace("/", "");
      return { nodes, edges, inferredEdges, relativize };
    },
    invoke: (api, ctx) => api.planEdgeMaterialization(ctx),
    assert: (r) => r.skipped[0].reason === "from_node_missing",
  },
  {
    name: "cross-branch edge is skipped with cross_branch reason",
    setup: () => {
      const nodes = [
        { id: "n1", outputs: { files: ["f1"] }, coordinates: { branch: "main" } },
        { id: "n2", outputs: { files: ["f2"] }, coordinates: { branch: "dev" } },
      ];
      const edges = [];
      const inferredEdges = [{ fromFile: "/f1", toFile: "/f2", type: "depends_on", tokens: [] }];
      const relativize = (p: string) => p.replace("/", "");
      return { nodes, edges, inferredEdges, relativize };
    },
    invoke: (api, ctx) => api.planEdgeMaterialization(ctx),
    assert: (r) => r.skipped[0].reason === "cross_branch",
  },
  {
    name: "duplicate edge is skipped with edge_already_exists reason",
    setup: () => {
      const nodes = [
        { id: "n1", outputs: { files: ["f1"] }, coordinates: { branch: "main" } },
        { id: "n2", outputs: { files: ["f2"] }, coordinates: { branch: "main" } },
      ];
      const edges = [{ from: "n1", to: "n2", type: "depends_on" }];
      const inferredEdges = [{ fromFile: "/f1", toFile: "/f2", type: "depends_on", tokens: [] }];
      const relativize = (p: string) => p.replace("/", "");
      return { nodes, edges, inferredEdges, relativize };
    },
    invoke: (api, ctx) => api.planEdgeMaterialization(ctx),
    assert: (r) => r.skipped[0].reason === "edge_already_exists",
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
