// GENERATED by `onto probe node_0115` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/kernel/graph/apply-edges-to-copy.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns empty arrays and unchanged state when no edges to apply",
    setup: () => ({
      resolvedEdges: [],
      state: {
        edgeCount: 5,
        eventCount: 10,
        lastEventId: "evt_prev",
        activeBranch: "main",
        updatedAt: "2023-01-01T00:00:00Z",
      },
      branch: "feature",
      mintId: () => "unused",
      timestamp: "2023-06-01T12:00:00Z",
    }),
    invoke: (api, ctx) => api.composeEdgeApplication(ctx),
    assert: (r) => 
      r.edges.length === 0 && 
      r.events.length === 0 && 
      r.newState.edgeCount === 5 && 
      r.newState.eventCount === 10 && 
      r.newState.lastEventId === "evt_prev" &&
      r.newState.activeBranch === "main" &&
      r.newState.updatedAt === "2023-06-01T12:00:00Z",
  },
  {
    name: "rule:2 — applies single edge with correct IDs and increments counters",
    setup: () => ({
      resolvedEdges: [{
        fromNodeId: "nodeA",
        toNodeId: "nodeB",
        type: { category: "related_to" },
      }],
      state: {
        edgeCount: 0,
        eventCount: 0,
        lastEventId: null,
        activeBranch: "main",
        updatedAt: "2023-01-01T00:00:00Z",
      },
      mintId: (() => {
        let counter = 0;
        return () => `id${counter++}`;
      })(),
      timestamp: "2023-06-01T12:00:00Z",
    }),
    invoke: (api, ctx) => api.composeEdgeApplication(ctx),
    assert: (r) => 
      r.edges.length === 1 && 
      r.events.length === 1 &&
      r.edges[0].edgeId === "edge_id0" &&
      r.events[0].eventId === "evt_id1" &&
      r.events[0].sequence === 0 &&
      r.events[0].previousEventId === null &&
      r.newState.edgeCount === 1 &&
      r.newState.eventCount === 1 &&
      r.newState.lastEventId === "evt_id1",
  },
  {
    name: "rule:3 — uses provided branch override instead of state's activeBranch",
    setup: () => ({
      resolvedEdges: [{
        fromNodeId: "node1",
        toNodeId: "node2",
        type: { category: "depends_on" },
      }],
      state: {
        edgeCount: 2,
        eventCount: 4,
        lastEventId: "evt_abc",
        activeBranch: "main",
        updatedAt: "2023-01-01T00:00:00Z",
      },
      branch: "custom-branch",
      mintId: (() => {
        let counter = 10;
        return () => `x${counter++}`;
      })(),
      timestamp: "2023-07-01T10:00:00Z",
    }),
    invoke: (api, ctx) => api.composeEdgeApplication(ctx),
    assert: (r) => 
      r.edges[0].branch === "custom-branch" && 
      r.events[0].branch === "custom-branch",
  },
  {
    name: "rule:4 — includes provenance in event payload when provided",
    setup: () => ({
      resolvedEdges: [{
        fromNodeId: "n1",
        toNodeId: "n2",
        type: { category: "derived_from" },
        provenance: { sourceFile: "test.ts", tokens: ["a", "b"] },
      }],
      state: {
        edgeCount: 0,
        eventCount: 0,
        lastEventId: null,
        activeBranch: "main",
        updatedAt: "2023-01-01T00:00:00Z",
      },
      mintId: () => "prov1",
      timestamp: "2023-08-01T09:00:00Z",
    }),
    invoke: (api, ctx) => api.composeEdgeApplication(ctx),
    assert: (r) => 
      r.events[0].payload.sourceFile === "test.ts" && 
      JSON.stringify(r.events[0].payload.tokens) === '["a","b"]',
  },
  {
    name: "rule:5 — applies multiple edges maintaining sequence and linking events",
    setup: () => ({
      resolvedEdges: [
        { fromNodeId: "a", toNodeId: "b", type: { category: "links_to" } },
        { fromNodeId: "b", toNodeId: "c", type: { category: "links_to" } },
      ],
      state: {
        edgeCount: 3,
        eventCount: 6,
        lastEventId: "evt_xyz",
        activeBranch: "main",
        updatedAt: "2023-01-01T00:00:00Z",
      },
      mintId: (() => {
        let counter = 100;
        return () => `${counter++}`;
      })(),
      timestamp: "2023-09-01T08:00:00Z",
    }),
    invoke: (api, ctx) => api.composeEdgeApplication(ctx),
    assert: (r) => 
      r.edges.length === 2 && 
      r.events.length === 2 &&
      r.events[0].sequence === 6 &&
      r.events[0].previousEventId === "evt_xyz" &&
      r.events[1].sequence === 7 &&
      r.events[1].previousEventId === "evt_100" &&
      r.newState.edgeCount === 5 &&
      r.newState.eventCount === 8 &&
      r.newState.lastEventId === "evt_101",
  },
  {
    name: "rule:6 — sets createdAt and timestamp fields to provided timestamp",
    setup: () => ({
      resolvedEdges: [{
        fromNodeId: "start",
        toNodeId: "end",
        type: { category: "flows_to" },
      }],
      state: {
        edgeCount: 0,
        eventCount: 0,
        lastEventId: null,
        activeBranch: "main",
        updatedAt: "2023-01-01T00:00:00Z",
      },
      mintId: () => "ts1",
      timestamp: "2024-01-01T00:00:00Z",
    }),
    invoke: (api, ctx) => api.composeEdgeApplication(ctx),
    assert: (r) => 
      r.edges[0].createdAt === "2024-01-01T00:00:00Z" && 
      r.events[0].timestamp === "2024-01-01T00:00:00Z" &&
      r.newState.updatedAt === "2024-01-01T00:00:00Z",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5]).has(i));
