// GENERATED by `onto probe node_0186` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/walker/actions/proposals-from-walker.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "node_create with label and level",
    setup: () => ({
      p: {
        id: "p1",
        mutation: { kind: "node_create", payload: { label: "Goal", level: "L1" } },
      },
    }),
    invoke: (api, ctx) => (api as any).summarizeProposalRow(ctx.p),
    assert: (r) => r === "p1  node  [L1]  Goal",
  },
  {
    name: "node_create missing label and level uses fallbacks",
    setup: () => ({
      p: {
        id: "p2",
        mutation: { kind: "node_create", payload: {} },
      },
    }),
    invoke: (api, ctx) => (api as any).summarizeProposalRow(ctx.p),
    assert: (r) => r === "p2  node  [—]  (unlabelled)",
  },
  {
    name: "edge_create formats from -> to (type)",
    setup: () => ({
      p: {
        id: "e1",
        mutation: {
          kind: "edge_create",
          payload: { from: "a", to: "b", type: "depends_on" },
        },
      },
    }),
    invoke: (api, ctx) => (api as any).summarizeProposalRow(ctx.p),
    assert: (r) => r === "e1  edge  a → b  (depends_on)",
  },
  {
    name: "node_update with prompt and label changed",
    setup: () => ({
      p: {
        id: "u1",
        mutation: {
          kind: "node_update",
          payload: { nodeId: "n9", prompt: "hi", label: "X" },
        },
      },
    }),
    invoke: (api, ctx) => (api as any).summarizeProposalRow(ctx.p),
    assert: (r) => r === "u1  update  n9  (prompt+label)",
  },
  {
    name: "node_update with all three fields joined by +",
    setup: () => ({
      p: {
        id: "u2",
        mutation: {
          kind: "node_update",
          payload: { nodeId: "n3", prompt: "p", provides: ["x"], label: "L" },
        },
      },
    }),
    invoke: (api, ctx) => (api as any).summarizeProposalRow(ctx.p),
    assert: (r) => r === "u2  update  n3  (prompt+provides+label)",
  },
  {
    name: "node_update with no recognized field falls back to 'fields'",
    setup: () => ({
      p: {
        id: "u3",
        mutation: { kind: "node_update", payload: { nodeId: "n7" } },
      },
    }),
    invoke: (api, ctx) => (api as any).summarizeProposalRow(ctx.p),
    assert: (r) => r === "u3  update  n7  (fields)",
  },
  {
    name: "node_update_parent (default branch) formats reparent",
    setup: () => ({
      p: {
        id: "r1",
        mutation: {
          kind: "node_update_parent",
          payload: { nodeId: "child", newParentNodeId: "parent" },
        },
      },
    }),
    invoke: (api, ctx) => (api as any).summarizeProposalRow(ctx.p),
    assert: (r) => r === "r1  reparent  child → parent",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6]).has(i));
