// GENERATED by `onto probe node_0185` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 1 self-validated case(s)
// (each matched the source src/surfaces/walker/actions/plan-from-walker.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns compile plan for valid focal node",
    setup: () => ({
      focalId: "node1",
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => (api as any).planFromWalker(ctx),
    assert: (r) => r !== undefined && typeof r === "object"
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0]).has(i));
