// GENERATED by `onto probe node_0154` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 10 self-validated case(s)
// (each matched the source src/runtime/llm/registry.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { LlmProvider, LlmTask } from "../src/runtime/llm/types.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — getDefaultModelForTask returns first preferred model",
    setup: () => ({ provider: "ollama" as LlmProvider, task: "semantic_parse" as LlmTask }),
    invoke: (api, ctx) => api.getDefaultModelForTask(ctx.provider, ctx.task),
    assert: (r) => r === "qwen2.5-coder:3b",
  },
  {
    name: "rule:1 — getDefaultModelForTask returns undefined for unknown provider",
    setup: () => ({ provider: "unknown" as LlmProvider, task: "semantic_parse" as LlmTask }),
    invoke: (api, ctx) => api.getDefaultModelForTask(ctx.provider, ctx.task),
    assert: (r) => r === undefined,
  },
  {
    name: "rule:1 — getDefaultModelForTask returns undefined for task with no routing",
    setup: () => ({ provider: "ollama" as LlmProvider, task: "unknown_task" as LlmTask }),
    invoke: (api, ctx) => api.getDefaultModelForTask(ctx.provider, ctx.task),
    assert: (r) => r === undefined,
  },
  {
    name: "rule:2 — getPreferredModelsForTask returns all preferred models in order",
    setup: () => ({ provider: "anthropic" as LlmProvider, task: "code_sketch" as LlmTask }),
    invoke: (api, ctx) => api.getPreferredModelsForTask(ctx.provider, ctx.task),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === "claude-opus-4-7",
  },
  {
    name: "rule:2 — getPreferredModelsForTask returns empty array for unknown provider",
    setup: () => ({ provider: "unknown" as LlmProvider, task: "semantic_parse" as LlmTask }),
    invoke: (api, ctx) => api.getPreferredModelsForTask(ctx.provider, ctx.task),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
  {
    name: "rule:2 — getPreferredModelsForTask returns empty array for task with no routing",
    setup: () => ({ provider: "ollama" as LlmProvider, task: "unknown_task" as LlmTask }),
    invoke: (api, ctx) => api.getPreferredModelsForTask(ctx.provider, ctx.task),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
  {
    name: "rule:3 — getDefaultRoutingForTask returns full routing entry",
    setup: () => ({ task: "documentation" as LlmTask }),
    invoke: (api, ctx) => api.getDefaultRoutingForTask(ctx.task),
    assert: (r) => r.tier === "fast" && Array.isArray(r.preferred) && r.preferred[0] === "llama3.1:8b",
  },
  {
    name: "rule:3 — getDefaultRoutingForTask throws on unknown task",
    setup: () => ({ task: "unknown_task" as LlmTask }),
    invoke: (api, ctx) => {
      try {
        api.getDefaultRoutingForTask(ctx.task);
        return false;
      } catch (e) {
        return e instanceof Error && e.message.includes("Unknown routing task");
      }
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:4 — DefaultOllamaRouting exposes correct structure",
    setup: () => ({}),
    invoke: (api, _) => api.DefaultOllamaRouting,
    assert: (r) => 
      typeof r === "object" && 
      r !== null && 
      "semantic_parse" in r && 
      r.semantic_parse.tier === "fast" &&
      Array.isArray(r.semantic_parse.preferred),
  },
  {
    name: "rule:5 — DefaultAnthropicRouting exposes correct structure",
    setup: () => ({}),
    invoke: (api, _) => api.DefaultAnthropicRouting,
    assert: (r) => 
      typeof r === "object" && 
      r !== null && 
      "node_critique" in r && 
      r.node_critique.tier === "critic" &&
      Array.isArray(r.node_critique.preferred),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).has(i));
