// GENERATED by `onto probe node_0216` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 4 self-validated case(s)
// (each matched the source src/surfaces/walker/state/parse-workflow-args.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — basic valid args with all required fields",
    setup: () => ":workflow graph.json --input input.txt",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === true && r.args.graphFile === "graph.json" && r.args.inputFile === "input.txt",
  },
  {
    name: "rule:2 — valid args with provider",
    setup: () => ":workflow graph.json ollama --input input.txt",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === true && r.args.provider === "ollama",
  },
  {
    name: "rule:3 — valid args with model",
    setup: () => ":workflow graph.json --input input.txt --model gpt-4",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === true && r.args.model === "gpt-4",
  },
  {
    name: "rule:4 — valid args with host",
    setup: () => ":workflow graph.json --input input.txt --host http://localhost:11434",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === true && r.args.ollamaHost === "http://localhost:11434",
  },
  {
    name: "rule:5 — valid args with propose-update flag",
    setup: () => ":workflow graph.json --input input.txt --propose-update",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === true && r.args.proposeUpdate === true,
  },
  {
    name: "rule:6 — missing graph file",
    setup: () => ":workflow --input input.txt",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes("usage"),
  },
  {
    name: "rule:7 — missing input file flag",
    setup: () => ":workflow graph.json",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === false && r.message === "--input <file> is required",
  },
  {
    name: "rule:8 — unknown provider",
    setup: () => ":workflow graph.json unknown-provider --input input.txt",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes("unknown provider"),
  },
  {
    name: "rule:9 — unknown flag",
    setup: () => ":workflow graph.json --input input.txt --unknown-flag",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes("unknown flag"),
  },
  {
    name: "rule:10 — too many positional arguments",
    setup: () => ":workflow graph.json ollama extra-arg --input input.txt",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes("unexpected argument"),
  },
  {
    name: "rule:11 — empty input",
    setup: () => "",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes("usage"),
  },
  {
    name: "rule:12 — whitespace only input",
    setup: () => "   ",
    invoke: (api, ctx) => (api as any).parseWorkflowArgs(ctx),
    assert: (r) => r.ok === false && r.message.includes("usage"),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([7, 8, 10, 11]).has(i));
