// GENERATED by `onto probe node_0227` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 22 self-validated case(s)
// (each matched the source src/schemas/workflow.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/runtime/legend/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "WorkflowNodeKindSchema accepts a valid kind",
    setup: () => "verifier",
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeKindSchema.safeParse(ctx).success,
    assert: (r) => r === true,
  },
  {
    name: "WorkflowNodeKindSchema rejects an unknown kind",
    setup: () => "router",
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeKindSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "TerminalVerdictSchema rejects a non-member string",
    setup: () => "maybe",
    invoke: (api, ctx) =>
      (api as any).TerminalVerdictSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "VerifierSchemaNameSchema accepts with-severity",
    setup: () => "with-severity",
    invoke: (api, ctx) =>
      (api as any).VerifierSchemaNameSchema.safeParse(ctx).success,
    assert: (r) => r === true,
  },
  {
    name: "WorkflowNode: generator without prompt and without passThrough fails refine",
    setup: () => ({ id: "g1", kind: "generator" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowNode: generator with passThrough=true and no prompt passes",
    setup: () => ({ id: "g1", kind: "generator", passThrough: true }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === true,
  },
  {
    name: "WorkflowNode: generator with empty-string prompt fails (min length via refine)",
    setup: () => ({ id: "g1", kind: "generator", prompt: "" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowNode: verifier with prompt but missing verifierSchema fails",
    setup: () => ({ id: "v1", kind: "verifier", prompt: "check it" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowNode: verifier with prompt and verifierSchema passes",
    setup: () => ({
      id: "v1",
      kind: "verifier",
      prompt: "check it",
      verifierSchema: "simple-pass-fail",
    }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === true,
  },
  {
    name: "WorkflowNode: terminal without terminalVerdict fails",
    setup: () => ({ id: "t1", kind: "terminal" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowNode: terminal with terminalVerdict passes",
    setup: () => ({ id: "t1", kind: "terminal", terminalVerdict: "accept" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === true,
  },
  {
    name: "WorkflowNode: empty id fails (min 1)",
    setup: () => ({ id: "", kind: "terminal", terminalVerdict: "reject" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowNode: temperature above 2 fails",
    setup: () => ({
      id: "g1",
      kind: "generator",
      prompt: "go",
      temperature: 2.5,
    }),
    invoke: (api, ctx) =>
      (api as any).WorkflowNodeSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowFeedsEdgeSchema accepts a valid feeds edge",
    setup: () => ({ from: "a", to: "b", type: "feeds" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowFeedsEdgeSchema.safeParse(ctx).success,
    assert: (r) => r === true,
  },
  {
    name: "WorkflowBranchesOnEdgeSchema rejects missing predicate",
    setup: () => ({ from: "a", to: "b", type: "branches_on" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowBranchesOnEdgeSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowEdgeSchema discriminates on type and parses branches_on",
    setup: () => ({
      from: "v",
      to: "g",
      type: "branches_on",
      predicate: "verdict == reject",
    }),
    invoke: (api, ctx) =>
      (api as any).WorkflowEdgeSchema.safeParse(ctx).success,
    assert: (r) => r === true,
  },
  {
    name: "WorkflowProposedEdgeSchema defaults direction to 'out'",
    setup: () => ({ type: "depends_on", target: "node_42" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowProposedEdgeSchema.parse(ctx).direction,
    assert: (r) => r === "out",
  },
  {
    name: "WorkflowProposedEdgeSchema rejects target not starting with node_",
    setup: () => ({ type: "depends_on", target: "42" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowProposedEdgeSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowProposedEdgeSchema preserves explicit direction 'in'",
    setup: () => ({ type: "depends_on", target: "node_7", direction: "in" }),
    invoke: (api, ctx) =>
      (api as any).WorkflowProposedEdgeSchema.parse(ctx).direction,
    assert: (r) => r === "in",
  },
  {
    name: "WorkflowGraphSchema: entry not in nodes fails refine",
    setup: () => ({
      entry: "missing",
      nodes: [{ id: "t1", kind: "terminal", terminalVerdict: "accept" }],
      edges: [],
    }),
    invoke: (api, ctx) =>
      (api as any).WorkflowGraphSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
  {
    name: "WorkflowGraphSchema: entry present in nodes passes",
    setup: () => ({
      entry: "t1",
      nodes: [{ id: "t1", kind: "terminal", terminalVerdict: "accept" }],
      edges: [],
    }),
    invoke: (api, ctx) =>
      (api as any).WorkflowGraphSchema.safeParse(ctx).success,
    assert: (r) => r === true,
  },
  {
    name: "WorkflowGraphSchema: empty nodes array fails (min 1)",
    setup: () => ({ entry: "t1", nodes: [], edges: [] }),
    invoke: (api, ctx) =>
      (api as any).WorkflowGraphSchema.safeParse(ctx).success,
    assert: (r) => r === false,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]).has(i));
