// GENERATED by `onto probe node_0123` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/kernel/graph/readiness.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — nodes without edges when node count exceeds threshold",
    setup: () => ({
      nodes: Array(51).fill(null).map((_, i) => ({ id: `node-${i}`, label: `Node ${i}` })),
      edges: [],
      thresholds: { minNodesForEdgeFabric: 50 }
    }),
    invoke: (api, ctx) => api.evaluateReadiness(ctx),
    assert: (r) => r.findings.some(f => f.ruleId === "nodes_without_edges") && r.ok === false,
  },
  {
    name: "rule:1 — no failure when node count below edge fabric threshold",
    setup: () => ({
      nodes: Array(10).fill(null).map((_, i) => ({ id: `node-${i}`, label: `Node ${i}` })),
      edges: [],
      thresholds: { minNodesForEdgeFabric: 50 }
    }),
    invoke: (api, ctx) => api.evaluateReadiness(ctx),
    assert: (r) => r.findings.length === 0 && r.ok === true,
  },
  {
    name: "rule:2 — global satisfied but context unreachable",
    setup: () => ({
      nodes: Array(10).fill(null).map((_, i) => ({ id: `node-${i}`, label: `Node ${i}` })),
      edges: Array(5).fill(null).map((_, i) => ({ 
        id: `edge-${i}`, 
        sourceId: `node-0`, 
        targetId: `node-${i+1}`, 
        label: `Edge ${i}` 
      })),
      thresholds: { minClosedWorldReachableRatio: 0.7 },
      rootNodeId: "node-0"
    }),
    invoke: (api, ctx) => {
      const mockMetrics = {
        topology: { nodeCount: 10, edgeCount: 5 },
        contracts: {
          closedWorldRequireCount: 10,
          closedWorldGlobalSatisfaction: { ratio: 1.0 },
          closedWorldContextReachableSatisfaction: { ratio: 0.5 }
        },
        flatness: { 
          nonRootDirectChildrenOfRootRatio: 0.3,
          verdict: "hierarchical" as const
        }
      };
      return api.evaluateReadinessFromMetrics(mockMetrics, ctx.thresholds);
    },
    assert: (r) => r.findings.some(f => f.ruleId === "global_satisfied_unreachable") && r.ok === false,
  },
  {
    name: "rule:2 — no failure when no closed world requires",
    setup: () => {
      const mockMetrics = {
        topology: { nodeCount: 10, edgeCount: 5 },
        contracts: {
          closedWorldRequireCount: 0,
          closedWorldGlobalSatisfaction: { ratio: 0 },
          closedWorldContextReachableSatisfaction: { ratio: 0 }
        },
        flatness: { 
          nonRootDirectChildrenOfRootRatio: 0.3,
          verdict: "hierarchical" as const
        }
      };
      return { metrics: mockMetrics, thresholds: { minClosedWorldReachableRatio: 0.7 } };
    },
    invoke: (api, ctx) => api.evaluateReadinessFromMetrics(ctx.metrics, ctx.thresholds),
    assert: (r) => r.findings.length === 0 && r.ok === true,
  },
  {
    name: "rule:3 — topologically flat graph",
    setup: () => {
      const mockMetrics = {
        topology: { nodeCount: 10, edgeCount: 9 },
        contracts: {
          closedWorldRequireCount: 0,
          closedWorldGlobalSatisfaction: { ratio: 0 },
          closedWorldContextReachableSatisfaction: { ratio: 0 }
        },
        flatness: { 
          nonRootDirectChildrenOfRootRatio: 0.9,
          verdict: "flat" as const
        }
      };
      return { metrics: mockMetrics, thresholds: { flatDirectRatio: 0.8, flatMinNodeCount: 5 } };
    },
    invoke: (api, ctx) => api.evaluateReadinessFromMetrics(ctx.metrics, ctx.thresholds),
    assert: (r) => r.findings.some(f => f.ruleId === "topologically_flat") && r.ok === false,
  },
  {
    name: "rule:3 — not flat when node count too small",
    setup: () => {
      const mockMetrics = {
        topology: { nodeCount: 4, edgeCount: 3 },
        contracts: {
          closedWorldRequireCount: 0,
          closedWorldGlobalSatisfaction: { ratio: 0 },
          closedWorldContextReachableSatisfaction: { ratio: 0 }
        },
        flatness: { 
          nonRootDirectChildrenOfRootRatio: 0.9,
          verdict: "flat" as const
        }
      };
      return { metrics: mockMetrics, thresholds: { flatDirectRatio: 0.8, flatMinNodeCount: 5 } };
    },
    invoke: (api, ctx) => api.evaluateReadinessFromMetrics(ctx.metrics, ctx.thresholds),
    assert: (r) => r.findings.length === 0 && r.ok === true,
  },
  {
    name: "all rules pass produces ok report",
    setup: () => {
      const mockMetrics = {
        topology: { nodeCount: 100, edgeCount: 150 },
        contracts: {
          closedWorldRequireCount: 20,
          closedWorldGlobalSatisfaction: { ratio: 1.0 },
          closedWorldContextReachableSatisfaction: { ratio: 0.8 }
        },
        flatness: { 
          nonRootDirectChildrenOfRootRatio: 0.2,
          verdict: "hierarchical" as const
        }
      };
      return { metrics: mockMetrics };
    },
    invoke: (api, ctx) => api.evaluateReadinessFromMetrics(ctx.metrics),
    assert: (r) => r.findings.length === 0 && r.ok === true,
  },
  {
    name: "formatRatio formats to 3 decimal places",
    setup: () => 0.123456,
    invoke: (api, ctx) => (api as any).formatRatio(ctx),
    assert: (r) => r === "0.123",
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
