// GENERATED by `onto probe node_0117` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/kernel/graph/compile-plan.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { OntologyEdge } from "../src/kernel/graph/schemas/ontology.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns superseded_focal plan when focal node is superseded",
    setup: () => ({
      focalId: "A",
      edges: [
        { from: "B", to: "A", type: "supersedes", edgeId: "e1" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => api.computeCompilePlan(ctx.focalId, ctx.edges),
    assert: (r) => r.ok === false && r.reason === "superseded_focal" && r.successor === "B",
  },
  {
    name: "rule:2 — returns conflict plan when closure contains contradicts edge",
    setup: () => ({
      focalId: "A",
      edges: [
        { from: "A", to: "B", type: "depends_on", edgeId: "e1" },
        { from: "B", to: "C", type: "contradicts", edgeId: "e2" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => api.computeCompilePlan(ctx.focalId, ctx.edges),
    assert: (r) => r.ok === false && r.reason === "conflict" && r.conflicts.length === 1 && r.conflicts[0].edgeId === "e2",
  },
  {
    name: "rule:3 — returns cycle plan when dependency cycle detected",
    setup: () => ({
      focalId: "A",
      edges: [
        { from: "A", to: "B", type: "depends_on", edgeId: "e1" },
        { from: "B", to: "A", type: "depends_on", edgeId: "e2" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => api.computeCompilePlan(ctx.focalId, ctx.edges),
    assert: (r) => r.ok === false && r.reason === "cycle" && r.unresolved.length === 2,
  },
  {
    name: "rule:4 — returns successful plan with warnings for superseded nodes in closure",
    setup: () => ({
      focalId: "A",
      edges: [
        { from: "A", to: "B", type: "depends_on", edgeId: "e1" },
        { from: "C", to: "B", type: "supersedes", edgeId: "e2" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => api.computeCompilePlan(ctx.focalId, ctx.edges),
    assert: (r) => r.ok === true && r.warnings.length === 1 && r.warnings[0].kind === "superseded",
  },
  {
    name: "rule:5 — excludes superseded nodes from closure and steps",
    setup: () => ({
      focalId: "A",
      edges: [
        { from: "A", to: "B", type: "depends_on", edgeId: "e1" },
        { from: "C", to: "B", type: "supersedes", edgeId: "e2" },
        { from: "B", to: "D", type: "depends_on", edgeId: "e3" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => api.computeCompilePlan(ctx.focalId, ctx.edges),
    assert: (r) => r.ok === true && !r.closure.includes("B") && r.steps.every(s => s.nodeId !== "B"),
  },
  {
    name: "rule:6 — emits steps in topological order with correct dependencies",
    setup: () => ({
      focalId: "C",
      edges: [
        { from: "C", to: "B", type: "depends_on", edgeId: "e1" },
        { from: "B", to: "A", type: "depends_on", edgeId: "e2" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => api.computeCompilePlan(ctx.focalId, ctx.edges),
    assert: (r) => r.ok === true && r.steps.map(s => s.nodeId).join(",") === "A,B,C",
  },
  {
    name: "rule:7 — handles empty edges list with focal node only",
    setup: () => ({
      focalId: "A",
      edges: [] as OntologyEdge[],
    }),
    invoke: (api, ctx) => api.computeCompilePlan(ctx.focalId, ctx.edges),
    assert: (r) => r.ok === true && r.steps.length === 1 && r.steps[0].nodeId === "A" && r.closure.length === 1,
  },
  {
    name: "rule:8 — sorts ready nodes alphabetically to ensure deterministic output",
    setup: () => ({
      focalId: "Z",
      edges: [
        { from: "Z", to: "B", type: "depends_on", edgeId: "e1" },
        { from: "Z", to: "A", type: "depends_on", edgeId: "e2" },
        { from: "A", to: "C", type: "depends_on", edgeId: "e3" },
        { from: "B", to: "C", type: "depends_on", edgeId: "e4" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => api.computeCompilePlan(ctx.focalId, ctx.edges),
    assert: (r) => r.ok === true && r.steps.map(s => s.nodeId).join(",") === "C,A,B,Z",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 2, 3, 4, 5, 6, 7]).has(i));
