// GENERATED by `onto probe node_0153` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/runtime/llm/ollama/fetch-shim.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — toPlainHeaders returns empty object for undefined input",
    setup: () => undefined,
    invoke: (api, ctx) => (api as any).toPlainHeaders(ctx),
    assert: (r) => typeof r === "object" && r !== null && Object.keys(r).length === 0,
  },
  {
    name: "rule:2 — toPlainHeaders converts Headers instance to plain object",
    setup: () => {
      const headers = new Headers();
      headers.set("Content-Type", "application/json");
      headers.set("Authorization", "Bearer token");
      return headers;
    },
    invoke: (api, ctx) => (api as any).toPlainHeaders(ctx),
    assert: (r) =>
      typeof r === "object" &&
      r !== null &&
      r["content-type"] === "application/json" &&
      r["authorization"] === "Bearer token",
  },
  {
    name: "rule:3 — toPlainHeaders converts array of pairs to plain object",
    setup: () => [["Content-Type", "text/plain"], ["X-Custom", "value"]],
    invoke: (api, ctx) => (api as any).toPlainHeaders(ctx),
    assert: (r) =>
      typeof r === "object" &&
      r !== null &&
      r["content-type"] === "text/plain" &&
      r["x-custom"] === "value",
  },
  {
    name: "rule:4 — abortError creates error with name AbortError",
    setup: () => ({}),
    invoke: (api, ctx) => (api as any).abortError(),
    assert: (r) => r instanceof Error && r.name === "AbortError",
  },
  {
    name: "rule:5 — noTimeoutFetchImpl preserves response headers without chunked encoding",
    setup: () => ({
      input: "http://localhost:8080/test",
      init: { method: "GET" },
    }),
    invoke: (api, ctx) => (api as any).noTimeoutFetchImpl(ctx.input, ctx.init),
    assert: (r) => r instanceof Response,
  },
  {
    name: "rule:6 — noTimeoutFetchImpl returns null body for status 204",
    setup: () => ({
      input: "http://localhost:8080/no-content",
      init: { method: "GET" },
    }),
    invoke: (api, ctx) => (api as any).noTimeoutFetchImpl(ctx.input, ctx.init),
    assert: (r) => r instanceof Response,
  },
  {
    name: "rule:7 — noTimeoutFetchImpl handles POST with body and sets Content-Length",
    setup: () => ({
      input: "http://localhost:8080/data",
      init: {
        method: "POST",
        body: JSON.stringify({ key: "value" }),
        headers: { "Content-Type": "application/json" },
      },
    }),
    invoke: (api, ctx) => (api as any).noTimeoutFetchImpl(ctx.input, ctx.init),
    assert: (r) => r instanceof Response,
  },
  {
    name: "rule:8 — noTimeoutFetchImpl rejects immediately if signal is already aborted",
    setup: () => {
      const controller = new AbortController();
      controller.abort();
      return {
        input: "http://localhost:8080/test",
        init: { signal: controller.signal },
      };
    },
    invoke: (api, ctx) => (api as any).noTimeoutFetchImpl(ctx.input, ctx.init),
    assert: (r) => r instanceof Error && r.name === "AbortError",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
