// GENERATED by `onto probe node_0023` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 3 self-validated case(s)
// (each matched the source src/kernel/core/projects/registry.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — getProjectRegistryPath returns correct path with XDG_CONFIG_HOME set",
    setup: () => {
      const originalEnv = process.env.XDG_CONFIG_HOME;
      process.env.XDG_CONFIG_HOME = "/custom/config";
      return { originalEnv };
    },
    invoke: (api) => {
      const result = api.getProjectRegistryPath();
      return result;
    },
    assert: (r) => r === "/custom/config/ontology/projects.json",
  },
  {
    name: "rule:1 — getProjectRegistryPath falls back to ~/.config when XDG_CONFIG_HOME is unset",
    setup: () => {
      const originalEnv = process.env.XDG_CONFIG_HOME;
      delete process.env.XDG_CONFIG_HOME;
      return { originalEnv };
    },
    invoke: (api) => {
      const result = api.getProjectRegistryPath();
      return result;
    },
    assert: (r) => r === `${require("os").homedir()}/.config/ontology/projects.json`,
  },
  {
    name: "rule:2 — loadProjectRegistry returns empty registry when file does not exist",
    setup: () => ({}),
    invoke: (api) => api.loadProjectRegistry(),
    assert: (r) => r.projects.length === 0 && r.schemaVersion === "0.1.0",
  },
  {
    name: "rule:4 — registerProject adds new project entry correctly",
    setup: () => ({
      input: { name: "test-project", path: "/tmp/test-project", rootNodeId: "node_abc123" },
    }),
    invoke: (api, ctx) => api.registerProject(ctx.input),
    assert: (r) =>
      r.projects.length === 1 &&
      r.projects[0].name === "test-project" &&
      r.projects[0].path === "/tmp/test-project" &&
      r.projects[0].rootNodeId === "node_abc123",
  },
  {
    name: "rule:4 — registerProject updates existing project entry",
    setup: () => ({
      initialRegistry: {
        schemaVersion: "0.1.0",
        projects: [
          {
            name: "old-name",
            path: "/tmp/test-project",
            rootNodeId: "node_old",
            createdAt: "2023-01-01T00:00:00.000Z",
            lastOpenedAt: "2023-01-01T00:00:00.000Z",
          },
        ],
      },
      input: { name: "new-name", path: "/tmp/test-project", rootNodeId: "node_new" },
    }),
    invoke: (api, ctx) => {
      // Simulate saving initial registry first
      api.saveProjectRegistry(ctx.initialRegistry);
      return api.registerProject(ctx.input);
    },
    assert: (r) =>
      r.projects.length === 1 &&
      r.projects[0].name === "new-name" &&
      r.projects[0].rootNodeId === "node_new" &&
      r.projects[0].createdAt === "2023-01-01T00:00:00.000Z" &&
      r.projects[0].lastOpenedAt !== "2023-01-01T00:00:00.000Z",
  },
  {
    name: "rule:5 — touchProject updates lastOpenedAt without changing other fields",
    setup: () => ({
      registry: {
        schemaVersion: "0.1.0",
        projects: [
          {
            name: "test-project",
            path: "/tmp/test-project",
            rootNodeId: "node_abc123",
            createdAt: "2023-01-01T00:00:00.000Z",
            lastOpenedAt: "2023-01-01T00:00:00.000Z",
          },
        ],
      },
      absPath: "/tmp/test-project",
    }),
    invoke: (api, ctx) => {
      api.saveProjectRegistry(ctx.registry);
      return api.touchProject(ctx.absPath);
    },
    assert: (r) =>
      r.projects.length === 1 &&
      r.projects[0].name === "test-project" &&
      r.projects[0].rootNodeId === "node_abc123" &&
      r.projects[0].createdAt === "2023-01-01T00:00:00.000Z" &&
      r.projects[0].lastOpenedAt !== "2023-01-01T00:00:00.000Z",
  },
  {
    name: "rule:7 — forgetProject removes project by path",
    setup: () => ({
      registry: {
        schemaVersion: "0.1.0",
        projects: [
          {
            name: "project1",
            path: "/tmp/project1",
            createdAt: "2023-01-01T00:00:00.000Z",
            lastOpenedAt: "2023-01-01T00:00:00.000Z",
          },
          {
            name: "project2",
            path: "/tmp/project2",
            createdAt: "2023-01-01T00:00:00.000Z",
            lastOpenedAt: "2023-01-01T00:00:00.000Z",
          },
        ],
      },
      pathToRemove: "/tmp/project1",
    }),
    invoke: (api, ctx) => {
      api.saveProjectRegistry(ctx.registry);
      return api.forgetProject(ctx.pathToRemove);
    },
    assert: (r) =>
      r.removed === 1 &&
      r.registry.projects.length === 1 &&
      r.registry.projects[0].name === "project2",
  },
  {
    name: "rule:8 — projectsByRecency sorts projects by lastOpenedAt descending",
    setup: () => ({
      registry: {
        schemaVersion: "0.1.0",
        projects: [
          {
            name: "project1",
            path: "/tmp/project1",
            createdAt: "2023-01-01T00:00:00.000Z",
            lastOpenedAt: "2023-01-03T00:00:00.000Z",
          },
          {
            name: "project2",
            path: "/tmp/project2",
            createdAt: "2023-01-01T00:00:00.000Z",
            lastOpenedAt: "2023-01-02T00:00:00.000Z",
          },
        ],
      },
    }),
    invoke: (api, ctx) => api.projectsByRecency(ctx.registry),
    assert: (r) => r[0].name === "project1" && r[1].name === "project2",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 6, 7]).has(i));
