// GENERATED by `onto probe node_0135` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/laws/matrix.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — buildMatrixCost populates all fields and ensures non-negative values",
    setup: () => ({
      provider: "anthropic",
      model: "claude-opus-4-7",
      task: "semantic_parse",
      usage: {
        promptTokens: 100,
        completionTokens: 50,
        costUSD: 0.001,
      },
      wallClockMs: 1200,
    }),
    invoke: (api, ctx) => api.buildMatrixCost(ctx),
    assert: (r) => 
      r.provider === "anthropic" &&
      r.model === "claude-opus-4-7" &&
      r.task === "semantic_parse" &&
      r.inputTokens === 100 &&
      r.outputTokens === 50 &&
      r.usd === 0.001 &&
      r.wallClockMs === 1200,
  },
  {
    name: "rule:1 — buildMatrixCost handles missing usage gracefully with defaults",
    setup: () => ({
      provider: "mock",
      model: "test-model",
      task: "code_sketch",
    }),
    invoke: (api, ctx) => api.buildMatrixCost(ctx),
    assert: (r) => 
      r.provider === "mock" &&
      r.model === "test-model" &&
      r.task === "code_sketch" &&
      r.inputTokens === 0 &&
      r.outputTokens === 0 &&
      r.usd === 0 &&
      r.wallClockMs === 0,
  },
  {
    name: "rule:3 — verdictToMatrixCell constructs all required fields from inputs",
    setup: () => ({
      verdict: "epsilon_equivalent" as const,
      literal: true,
      cost: {
        provider: "anthropic",
        model: "claude-opus-4-7",
        task: "semantic_parse",
        inputTokens: 100,
        outputTokens: 50,
        usd: 0.001,
        wallClockMs: 1200,
      },
    }),
    invoke: (api, ctx) => api.verdictToMatrixCell(ctx),
    assert: (r) => 
      r.contract === "not-measured" &&
      r.structural === "pass" &&
      r.behavior === "untested" &&
      r.intent === "not-reviewed" &&
      r.literalRequired === "true" &&
      r.cost.provider === "anthropic",
  },
  {
    name: "rule:3 — verdictToMatrixCell handles unrecoverable verdict correctly",
    setup: () => ({
      verdict: "unrecoverable" as const,
      literal: false,
      cost: {
        provider: "mock",
        model: "test",
        task: "test",
        inputTokens: 0,
        outputTokens: 0,
        usd: 0,
        wallClockMs: 0,
      },
    }),
    invoke: (api, ctx) => api.verdictToMatrixCell(ctx),
    assert: (r) => 
      r.contract === "not-measured" &&
      r.structural === "not-measured" &&
      r.behavior === "not-applicable" &&
      r.intent === "needs-human" &&
      r.literalRequired === "false",
  },
  {
    name: "rule:4 — honestyForCell calculates structural honesty with valid metrics",
    setup: () => ({
      cell: {
        contract: "pass",
        structural: "pass",
        behavior: "pass",
        intent: "accepted",
        literalRequired: "true",
        cost: {
          provider: "test",
          model: "test",
          task: "test",
          inputTokens: 0,
          outputTokens: 0,
          usd: 0,
          wallClockMs: 0,
        },
      },
      metrics: {
        locDistance: 0.2,
        structuralJaccard: 0.8,
      },
    }),
    invoke: (api, ctx) => api.honestyForCell(ctx.cell, ctx.metrics),
    assert: (r) => 
      r.structural !== null && 
      Math.abs(r.structural - 0.9) < 1e-10 && // 0.5 * (1 - 0.2) + 0.5 * 0.8 = 0.9
      r.contract === 1 &&
      r.behavior === 1 &&
      r.intent === 1,
  },
  {
    name: "rule:4 — honestyForCell returns null structural when metrics undefined",
    setup: () => ({
      cell: {
        contract: "unknown",
        structural: "fail",
        behavior: "untested",
        intent: "not-reviewed",
        literalRequired: "false",
        cost: {
          provider: "test",
          model: "test",
          task: "test",
          inputTokens: 0,
          outputTokens: 0,
          usd: 0,
          wallClockMs: 0,
        },
      },
      metrics: undefined,
    }),
    invoke: (api, ctx) => api.honestyForCell(ctx.cell, ctx.metrics),
    assert: (r) => 
      r.structural === null &&
      r.contract === null &&
      r.behavior === null &&
      r.intent === null,
  },
  {
    name: "rule:5 — meanHonesty computes correct means for valid scores",
    setup: () => ([
      { structural: 0.8, contract: 1, behavior: null, intent: 1 },
      { structural: 0.6, contract: 0, behavior: 1, intent: 0.5 },
      { structural: null, contract: null, behavior: null, intent: null },
    ]),
    invoke: (api, ctx) => api.meanHonesty(ctx),
    assert: (r) => 
      r.structural.mean !== null && 
      Math.abs(r.structural.mean - 0.7) < 1e-10 && // (0.8 + 0.6) / 2
      r.structural.n === 2 &&
      r.contract.mean !== null && 
      Math.abs(r.contract.mean - 0.5) < 1e-10 && // (1 + 0) / 2
      r.contract.n === 2 &&
      r.behavior.mean !== null && 
      Math.abs(r.behavior.mean - 1) < 1e-10 && // 1 / 1
      r.behavior.n === 1 &&
      r.intent.mean !== null && 
      Math.abs(r.intent.mean - 0.75) < 1e-10 && // (1 + 0.5) / 2
      r.intent.n === 2,
  },
  {
    name: "rule:6 — verdictDerivedTags derives correct frontier attributes from cell state",
    setup: () => ({
      contract: "fail",
      structural: "fail",
      behavior: "fail",
      intent: "not-reviewed",
      literalRequired: "true",
      cost: {
        provider: "test",
        model: "test",
        task: "test",
        inputTokens: 0,
        outputTokens: 0,
        usd: 0,
        wallClockMs: 0,
      },
    }),
    invoke: (api, ctx) => api.verdictDerivedTags(ctx),
    assert: (r) => 
      r.includes("structural-drift") &&
      r.includes("behavior-drift") &&
      r.includes("contract-missing") &&
      r.includes("not-reviewed") &&
      r.includes("literal-required") &&
      r.length === 5,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 5, 6, 7]).has(i));
