// GENERATED by `onto probe node_0215` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/surfaces/walker/state/parse-query-args.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — empty input returns empty shape",
    setup: () => "",
    invoke: (api, ctx) => api.parseQueryArgs(ctx),
    assert: (r) => r.ok === true && Object.keys(r.shape).length === 0,
  },
  {
    name: "rule:2 — parses single flag with single value",
    setup: () => "--kind X",
    invoke: (api, ctx) => api.parseQueryArgs(ctx),
    assert: (r) => r.ok === true && r.shape.kind?.[0] === "X" && r.shape.kind.length === 1,
  },
  {
    name: "rule:3 — parses multiple flags with single values",
    setup: () => "--kind X --has-incoming Y",
    invoke: (api, ctx) => api.parseQueryArgs(ctx),
    assert: (r) => r.ok === true && r.shape.kind?.[0] === "X" && r.shape.hasIncoming?.[0] === "Y",
  },
  {
    name: "rule:4 — handles comma-separated values",
    setup: () => "--kind X,Y,Z",
    invoke: (api, ctx) => api.parseQueryArgs(ctx),
    assert: (r) => r.ok === true && r.shape.kind?.length === 3 && r.shape.kind?.includes("X") && r.shape.kind?.includes("Y") && r.shape.kind?.includes("Z"),
  },
  {
    name: "rule:5 — merges repeated flags",
    setup: () => "--kind X --kind Y",
    invoke: (api, ctx) => api.parseQueryArgs(ctx),
    assert: (r) => r.ok === true && r.shape.kind?.length === 2 && r.shape.kind?.includes("X") && r.shape.kind?.includes("Y"),
  },
  {
    name: "rule:6 — returns error for unknown flag",
    setup: () => "--unknown X",
    invoke: (api, ctx) => api.parseQueryArgs(ctx),
    assert: (r) => r.ok === false && r.message === "unknown query flag: --unknown",
  },
  {
    name: "rule:7 — returns error for missing value",
    setup: () => "--kind",
    invoke: (api, ctx) => api.parseQueryArgs(ctx),
    assert: (r) => r.ok === false && r.message === "--kind requires a value",
  },
  {
    name: "rule:8 — returns error for empty value",
    setup: () => "--kind ,",
    invoke: (api, ctx) => api.parseQueryArgs(ctx),
    assert: (r) => r.ok === false && r.message === "--kind requires a non-empty value",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
