// GENERATED by `onto probe node_0159` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 9 self-validated case(s)
// (each matched the source src/forward/prompt/parse.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — parsePromptAST with no markers returns empty markers and full body",
    setup: () => ({ raw: "Hello\nWorld\nNo markers here" }),
    invoke: (api, ctx) => api.parsePromptAST(ctx.raw),
    assert: (r) => 
      r.body === "Hello\nWorld\nNo markers here" &&
      r.markers.requires.length === 0 &&
      r.markers.provides.length === 0 &&
      r.markers.expand.length === 0,
  },
  {
    name: "rule:2 — parsePromptAST with valid requires marker extracts tokens correctly",
    setup: () => ({ raw: "@requires: foo, bar\nSome content here" }),
    invoke: (api, ctx) => api.parsePromptAST(ctx.raw),
    assert: (r) => 
      r.body === "Some content here" &&
      r.markers.requires.length === 2 &&
      r.markers.requires[0] === "foo" &&
      r.markers.requires[1] === "bar",
  },
  {
    name: "rule:3 — parsePromptAST with duplicate tokens in same marker deduplicates",
    setup: () => ({ raw: "@requires: foo, bar, foo\nContent" }),
    invoke: (api, ctx) => api.parsePromptAST(ctx.raw),
    assert: (r) => 
      r.body === "Content" &&
      r.markers.requires.length === 2 &&
      r.markers.requires[0] === "foo" &&
      r.markers.requires[1] === "bar",
  },
  {
    name: "rule:4 — parsePromptAST with multiple marker types populates all fields",
    setup: () => ({ raw: "@requires: a\n@provides: b\n@expand: c\nBody content" }),
    invoke: (api, ctx) => api.parsePromptAST(ctx.raw),
    assert: (r) => 
      r.body === "Body content" &&
      r.markers.requires.length === 1 && r.markers.requires[0] === "a" &&
      r.markers.provides.length === 1 && r.markers.provides[0] === "b" &&
      r.markers.expand.length === 1 && r.markers.expand[0] === "c",
  },
  {
    name: "rule:5 — parsePromptAST trims whitespace around tokens and ignores empty ones",
    setup: () => ({ raw: "@requires:  foo , , bar  \nBody" }),
    invoke: (api, ctx) => api.parsePromptAST(ctx.raw),
    assert: (r) => 
      r.body === "Body" &&
      r.markers.requires.length === 2 &&
      r.markers.requires[0] === "foo" &&
      r.markers.requires[1] === "bar",
  },
  {
    name: "rule:6 — hasMarkers returns false when no markers present",
    setup: () => ({ ast: { raw: "test", body: "test", markers: { requires: [], provides: [], expand: [] } } }),
    invoke: (api, ctx) => api.hasMarkers(ctx.ast),
    assert: (r) => r === false,
  },
  {
    name: "rule:7 — hasMarkers returns true when requires markers present",
    setup: () => ({ ast: { raw: "test", body: "test", markers: { requires: ["foo"], provides: [], expand: [] } } }),
    invoke: (api, ctx) => api.hasMarkers(ctx.ast),
    assert: (r) => r === true,
  },
  {
    name: "rule:8 — hasMarkers returns true when provides markers present",
    setup: () => ({ ast: { raw: "test", body: "test", markers: { requires: [], provides: ["bar"], expand: [] } } }),
    invoke: (api, ctx) => api.hasMarkers(ctx.ast),
    assert: (r) => r === true,
  },
  {
    name: "rule:9 — hasMarkers returns true when expand markers present",
    setup: () => ({ ast: { raw: "test", body: "test", markers: { requires: [], provides: [], expand: ["baz"] } } }),
    invoke: (api, ctx) => api.hasMarkers(ctx.ast),
    assert: (r) => r === true,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8]).has(i));
