// GENERATED by `onto probe node_0015` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/kernel/core/integrity/merkle.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type {
  MerkleLeafInput,
  MerkleTree,
  MerkleDiff,
} from "./src/kernel/core/integrity/merkle.ts";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — normalizeLeafPath returns posix-normalized path",
    setup: () => "./some\\path/to/file.txt",
    invoke: (api, ctx) => api.normalizeLeafPath(ctx),
    assert: (r) => r === "some/path/to/file.txt",
  },
  {
    name: "rule:1 — normalizeLeafPath throws on empty path",
    setup: () => "",
    invoke: (api, ctx) => {
      try {
        api.normalizeLeafPath(ctx);
        return "did not throw";
      } catch (e) {
        return "threw";
      }
    },
    assert: (r) => r === "threw",
  },
  {
    name: "rule:2 — hashFileContent produces consistent hash for same content",
    setup: () => "hello world",
    invoke: (api, ctx) => api.hashFileContent(ctx),
    assert: (r) => r === "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9",
  },
  {
    name: "rule:2 — hashFileContent produces same hash for Buffer and string",
    setup: () => ({ str: "hello", buf: Buffer.from("hello") }),
    invoke: (api, ctx) => ({
      strHash: api.hashFileContent(ctx.str),
      bufHash: api.hashFileContent(ctx.buf),
    }),
    assert: (r) => r.strHash === r.bufHash,
  },
  {
    name: "rule:3 — buildMerkleTree constructs tree with correct root hash",
    setup: () => [
      { path: "a.txt", hash: "hash1" },
      { path: "b/c.txt", hash: "hash2" },
    ] as MerkleLeafInput[],
    invoke: (api, ctx) => api.buildMerkleTree(ctx),
    assert: (r) => typeof r.rootHash === "string" && r.rootHash.length === 64,
  },
  {
    name: "rule:3 — buildMerkleTree throws on empty path in leaves",
    setup: () => [{ path: "", hash: "hash" }] as MerkleLeafInput[],
    invoke: (api, ctx) => {
      try {
        api.buildMerkleTree(ctx);
        return "did not throw";
      } catch (e) {
        return "threw";
      }
    },
    assert: (r) => r === "threw",
  },
  {
    name: "rule:3 — buildMerkleTree throws on duplicate paths",
    setup: () => [
      { path: "a.txt", hash: "hash1" },
      { path: "a.txt", hash: "hash2" },
    ] as MerkleLeafInput[],
    invoke: (api, ctx) => {
      try {
        api.buildMerkleTree(ctx);
        return "did not throw";
      } catch (e) {
        return "threw";
      }
    },
    assert: (r) => r === "threw",
  },
  {
    name: "rule:4 — diffMerkleTrees computes added/removed/changed paths",
    setup: () => {
      const prev: MerkleTree = {
        rootHash: "unused",
        root: {
          kind: "dir",
          name: "",
          hash: "prev-root",
          children: [
            { kind: "leaf", name: "a.txt", hash: "old-hash" },
            { kind: "leaf", name: "b.txt", hash: "old-hash-2" },
          ],
        },
        leafCount: 2,
      };
      const next: MerkleTree = {
        rootHash: "unused",
        root: {
          kind: "dir",
          name: "",
          hash: "next-root",
          children: [
            { kind: "leaf", name: "a.txt", hash: "new-hash" }, // changed
            // b.txt removed
            { kind: "leaf", name: "c.txt", hash: "new-file-hash" }, // added
          ],
        },
        leafCount: 2,
      };
      return { prev, next };
    },
    invoke: (api, ctx) => api.diffMerkleTrees(ctx.prev, ctx.next),
    assert: (r) =>
      r.added.length === 1 &&
      r.added[0] === "c.txt" &&
      r.removed.length === 1 &&
      r.removed[0] === "b.txt" &&
      r.changed.length === 1 &&
      r.changed[0] === "a.txt",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 2, 3, 4, 5, 6, 7]).has(i));
