// GENERATED by `onto probe node_0131` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 9 self-validated case(s)
// (each matched the source src/runtime/legend/frontier-tagger.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "effects region path → sorted [algebraic-lawful, pure-transform]",
    setup: () => ({ filePath: "/src/runtime/effects/monad.ts" }),
    invoke: (api, ctx) => (api as any).frontierTagsForFile(ctx.filePath),
    assert: (r) =>
      Array.isArray(r) &&
      r.length === 2 &&
      r[0] === "algebraic-lawful" &&
      r[1] === "pure-transform",
  },
  {
    name: "rule-compiler.ts unions specific + topos region rules, sorted",
    setup: () => ({ filePath: "/src/runtime/topos/rule-compiler.ts" }),
    invoke: (api, ctx) => (api as any).frontierTagsForFile(ctx.filePath),
    assert: (r) =>
      Array.isArray(r) &&
      r.length === 4 &&
      r[0] === "algebraic-lawful" &&
      r[1] === "declarative-validator" &&
      r[2] === "pure-transform" &&
      r[3] === "schema-driven",
  },
  {
    name: "no rule matches → operational-glue fallback",
    setup: () => ({ filePath: "/some/random/file.ts" }),
    invoke: (api, ctx) => (api as any).frontierTagsForFile(ctx.filePath),
    assert: (r) =>
      Array.isArray(r) && r.length === 1 && r[0] === "operational-glue",
  },
  {
    name: "tagFile returns filePath verbatim and a reasons array",
    setup: () => ({ filePath: "/src/schemas/ontology.ts" }),
    invoke: (api, ctx) => (api as any).tagFile(ctx.filePath),
    assert: (r) =>
      r.filePath === "/src/schemas/ontology.ts" &&
      Array.isArray(r.attrs) &&
      r.attrs.length === 1 &&
      r.attrs[0] === "schema-driven" &&
      Array.isArray(r.reasons) &&
      r.reasons.length === 1,
  },
  {
    name: "backslash paths normalized before matching",
    setup: () => ({ filePath: "C:\\repo\\src\\schemas\\workflow.ts" }),
    invoke: (api, ctx) => (api as any).frontierTagsForFile(ctx.filePath),
    assert: (r) =>
      Array.isArray(r) && r.length === 1 && r[0] === "schema-driven",
  },
  {
    name: "content @human-authored marker adds human-authored (no path match → no fallback)",
    setup: () => ({
      filePath: "/some/random/file.ts",
      contents: "const x = 1;\n// @human-authored\n",
    }),
    invoke: (api, ctx) =>
      (api as any).frontierTagsForFile(ctx.filePath, ctx.contents),
    assert: (r) =>
      Array.isArray(r) && r.length === 1 && r[0] === "human-authored",
  },
  {
    name: "literal: true content marker adds literal-required atop path attrs, sorted",
    setup: () => ({
      filePath: "/src/runtime/effects/io.ts",
      contents: "export const node = { literal: true };",
    }),
    invoke: (api, ctx) =>
      (api as any).frontierTagsForFile(ctx.filePath, ctx.contents),
    assert: (r) =>
      Array.isArray(r) &&
      r.length === 3 &&
      r[0] === "algebraic-lawful" &&
      r[1] === "literal-required" &&
      r[2] === "pure-transform",
  },
  {
    name: "translator.ts unions specific (glue, prompt-sensitive) + legend region (pure-transform)",
    setup: () => ({ filePath: "/src/runtime/legend/translator.ts" }),
    invoke: (api, ctx) => (api as any).frontierTagsForFile(ctx.filePath),
    assert: (r) =>
      Array.isArray(r) &&
      r.length === 3 &&
      r[0] === "operational-glue" &&
      r[1] === "prompt-sensitive" &&
      r[2] === "pure-transform",
  },
  {
    name: "contents omitted → content rules do not run (only path attrs)",
    setup: () => ({ filePath: "/src/core/integrity/hash.ts" }),
    invoke: (api, ctx) => (api as any).tagFile(ctx.filePath),
    assert: (r) =>
      Array.isArray(r.attrs) &&
      r.attrs.length === 1 &&
      r.attrs[0] === "pure-transform",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8]).has(i));
