// GENERATED by `onto probe node_0116` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/kernel/graph/artifact-category.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { OntologyEdge } from "../src/kernel/graph/schemas/ontology.js";
import type { CompilePlan } from "../src/kernel/graph/compile-plan.js";
import type { ArtifactCategory, FunctorialityReport } from "../src/kernel/graph/artifact-category.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — computeCompilePlan returns failure when plan fails",
    setup: () => ({
      focalId: "A",
      edges: [
        { edgeId: "e1", from: "A", to: "B", type: "hard-dep" },
        { edgeId: "e2", from: "B", to: "A", type: "hard-dep" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => (api as any).verifyFunctoriality(ctx.focalId, ctx.edges),
    assert: (r: FunctorialityReport) => r.ok === false && r.planFailed === true,
  },
  {
    name: "rule:2 — identityPreserved is false when duplicate nodes exist",
    setup: () => ({
      focalId: "A",
      edges: [
        { edgeId: "e1", from: "A", to: "B", type: "hard-dep" },
        { edgeId: "e2", from: "B", to: "C", type: "hard-dep" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => {
      const plan = (api as any).computeCompilePlan(ctx.focalId, ctx.edges);
      if (!plan.ok) return { ok: false, planFailed: true } as any;
      const badPlan = {
        ...plan,
        steps: [...plan.steps, plan.steps[0]], // duplicate step
      };
      return (api as any).buildArtifactCategory(badPlan, ctx.edges);
    },
    assert: (r: ArtifactCategory) => r.objects.length > new Set(r.objects).size,
  },
  {
    name: "rule:3 — morphismsPreserved fails when compile order violates dependency",
    setup: () => ({
      focalId: "A",
      edges: [
        { edgeId: "e1", from: "A", to: "B", type: "hard-dep" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => (api as any).verifyFunctoriality(ctx.focalId, ctx.edges),
    assert: (r: FunctorialityReport) => {
      if (r.ok) return true; // if it passes, that's fine
      return r.violations.some(v => v.includes("dep must precede dependent"));
    },
  },
  {
    name: "rule:4 — compositionPreserved fails when transitive closures disagree",
    setup: () => ({
      focalId: "A",
      edges: [
        { edgeId: "e1", from: "A", to: "B", type: "hard-dep" },
        { edgeId: "e2", from: "B", to: "C", type: "hard-dep" },
        { edgeId: "e3", from: "A", to: "C", type: "soft-dep" }, // not hard, so not in I
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => (api as any).verifyFunctoriality(ctx.focalId, ctx.edges),
    assert: (r: FunctorialityReport) => {
      if (r.ok) return true;
      return r.violations.some(v => v.includes("intention-reach") && v.includes("artifact-reach"));
    },
  },
  {
    name: "transitiveClosure with empty inputs",
    setup: () => ({
      objects: [] as string[],
      directEdges: [] as Array<{ from: string; to: string }>,
    }),
    invoke: (api, ctx) => (api as any).transitiveClosure(ctx.objects, ctx.directEdges),
    assert: (r: Map<string, Set<string>>) => r.size === 0,
  },
  {
    name: "transitiveClosure with linear chain",
    setup: () => ({
      objects: ["A", "B", "C"],
      directEdges: [{ from: "A", to: "B" }, { from: "B", to: "C" }],
    }),
    invoke: (api, ctx) => (api as any).transitiveClosure(ctx.objects, ctx.directEdges),
    assert: (r: Map<string, Set<string>>) => {
      const aReach = r.get("A");
      return aReach !== undefined && aReach.has("B") && aReach.has("C");
    },
  },
  {
    name: "buildArtifactCategory with valid plan and edges",
    setup: () => {
      const plan = {
        ok: true,
        closure: ["A", "B"],
        steps: [
          { nodeId: "A", dependsOn: [] },
          { nodeId: "B", dependsOn: ["e1"] },
        ],
      } as unknown as Extract<CompilePlan, { ok: true }>;
      const edges = [
        { edgeId: "e1", from: "B", to: "A", type: "hard-dep" },
      ] as OntologyEdge[];
      return { plan, edges };
    },
    invoke: (api, ctx) => (api as any).buildArtifactCategory(ctx.plan, ctx.edges),
    assert: (r: ArtifactCategory) => r.objects.length === 2 && r.order.length === 2,
  },
  {
    name: "verifyFunctoriality with valid acyclic graph",
    setup: () => ({
      focalId: "A",
      edges: [
        { edgeId: "e1", from: "A", to: "B", type: "hard-dep" },
        { edgeId: "e2", from: "B", to: "C", type: "hard-dep" },
      ] as OntologyEdge[],
    }),
    invoke: (api, ctx) => (api as any).verifyFunctoriality(ctx.focalId, ctx.edges),
    assert: (r: FunctorialityReport) => typeof r.ok === "boolean",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([1, 2, 3, 4, 5, 6, 7]).has(i));
