// GENERATED by `onto probe node_0164` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/inverse/static/edges.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns empty array when extensions list is empty",
    setup: () => ({ rootDir: "/project", extensions: [] }),
    invoke: (api, ctx) => api.inferEdgesAutoFromDirectory(ctx.rootDir, ctx.extensions),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
  {
    name: "rule:2 — includes TypeScript edges when .ts extension is provided",
    setup: () => ({ rootDir: "/project", extensions: ["ts"] }),
    invoke: (api, ctx) => api.inferEdgesAutoFromDirectory(ctx.rootDir, ctx.extensions),
    assert: (r) => Array.isArray(r),
  },
  {
    name: "rule:3 — includes Python edges when .py extension is provided",
    setup: () => ({ rootDir: "/project", extensions: ["py"] }),
    invoke: (api, ctx) => api.inferEdgesAutoFromDirectory(ctx.rootDir, ctx.extensions),
    assert: (r) => Array.isArray(r),
  },
  {
    name: "rule:4 — includes both TS and Python edges for mixed-language project",
    setup: () => ({ rootDir: "/project", extensions: ["ts", "py"] }),
    invoke: (api, ctx) => api.inferEdgesAutoFromDirectory(ctx.rootDir, ctx.extensions),
    assert: (r) => Array.isArray(r),
  },
  {
    name: "rule:5 — normalizes extensions by removing leading dots and lowercasing",
    setup: () => ({ rootDir: "/project", extensions: [".TS", ".PY"] }),
    invoke: (api, ctx) => api.inferEdgesAutoFromDirectory(ctx.rootDir, ctx.extensions),
    assert: (r) => Array.isArray(r),
  },
  {
    name: "rule:6 — ignores unknown extensions silently",
    setup: () => ({ rootDir: "/project", extensions: ["unknown", "ts"] }),
    invoke: (api, ctx) => api.inferEdgesAutoFromDirectory(ctx.rootDir, ctx.extensions),
    assert: (r) => Array.isArray(r),
  },
  {
    name: "rule:7 — returns sorted edges by fromFile, toFile, and type",
    setup: () => ({ rootDir: "/project", extensions: ["ts"] }),
    invoke: (api, ctx) => api.inferEdgesAutoFromDirectory(ctx.rootDir, ctx.extensions),
    assert: (r) => Array.isArray(r),
  },
  {
    name: "rule:8 — async variant loads Rust parser dynamically when .rs extension is provided",
    setup: () => ({ rootDir: "/project", extensions: ["rs"] }),
    invoke: async (api, ctx) => await api.inferEdgesAutoFromDirectoryAsync(ctx.rootDir, ctx.extensions),
    assert: (r) => Array.isArray(r),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
