// GENERATED by `onto probe node_0147` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/runtime/llm/gemini/adapter.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — throws when GEMINI_API_KEY missing",
    setup: () => ({}),
    invoke: (api, ctx) => {
      try {
        api.createGeminiAdapter();
        return "did not throw";
      } catch (e) {
        return "threw";
      }
    },
    assert: (r) => r === "threw",
  },
  {
    name: "rule:1 — accepts valid apiKey in options",
    setup: () => ({ options: { apiKey: "test-key" } }),
    invoke: (api, ctx) => {
      try {
        const adapter = api.createGeminiAdapter(ctx.options);
        return { provider: adapter.provider };
      } catch (e) {
        return "threw";
      }
    },
    assert: (r) => (r as any).provider === "gemini",
  },
  {
    name: "health returns ok status",
    setup: () => ({ options: { apiKey: "test-key" } }),
    invoke: (api, ctx) => api.createGeminiAdapter(ctx.options).health(),
    assert: (r) => (r as any).ok === true,
  },
  {
    name: "listModels returns static model handles",
    setup: () => ({ options: { apiKey: "test-key" } }),
    invoke: (api, ctx) => api.createGeminiAdapter(ctx.options).listModels(),
    assert: (r) => Array.isArray(r) && r.length === 2 && r[0].id === "gemini-2.5-pro",
  },
  {
    name: "generate uses request.model when provided",
    setup: () => ({
      options: { apiKey: "test-key" },
      request: { model: "gemini-2.5-pro", prompt: "test" },
    }),
    invoke: (api, ctx) => {
      const adapter = api.createGeminiAdapter(ctx.options);
      // Mock the ai.models.generateContent to avoid real API calls
      (adapter as any)._ai = {
        models: {
          generateContent: async () => ({ text: "response" }),
        },
      };
      return adapter.generate(ctx.request);
    },
    assert: (r) => (r as any).model === "gemini-2.5-pro",
  },
  {
    name: "generate uses defaultModel when request.model missing",
    setup: () => ({
      options: { apiKey: "test-key", defaultModel: "gemini-2.5-flash" },
      request: { prompt: "test" },
    }),
    invoke: (api, ctx) => {
      const adapter = api.createGeminiAdapter(ctx.options);
      (adapter as any)._ai = {
        models: {
          generateContent: async () => ({ text: "response" }),
        },
      };
      return adapter.generate(ctx.request);
    },
    assert: (r) => (r as any).model === "gemini-2.5-flash",
  },
  {
    name: "generate includes googleSearch tool when webSearch=true",
    setup: () => ({
      options: { apiKey: "test-key" },
      request: { prompt: "test", webSearch: true },
    }),
    invoke: (api, ctx) => {
      const adapter = api.createGeminiAdapter(ctx.options);
      let capturedConfig: any;
      (adapter as any)._ai = {
        models: {
          generateContent: async (params: any) => {
            capturedConfig = params.config;
            return { text: "response" };
          },
        },
      };
      return { adapter: adapter, capturedConfigPromise: adapter.generate(ctx.request).then(() => capturedConfig) };
    },
    assert: async (r) => {
      const result = await (r as any).capturedConfigPromise;
      return result.tools && result.tools[0] && result.tools[0].googleSearch !== undefined;
    },
  },
  {
    name: "generate omits tools when webSearch=false",
    setup: () => ({
      options: { apiKey: "test-key" },
      request: { prompt: "test", webSearch: false },
    }),
    invoke: (api, ctx) => {
      const adapter = api.createGeminiAdapter(ctx.options);
      let capturedConfig: any;
      (adapter as any)._ai = {
        models: {
          generateContent: async (params: any) => {
            capturedConfig = params.config;
            return { text: "response" };
          },
        },
      };
      return { adapter: adapter, capturedConfigPromise: adapter.generate(ctx.request).then(() => capturedConfig) };
    },
    assert: async (r) => {
      const result = await (r as any).capturedConfigPromise;
      return !result.tools;
    },
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5]).has(i));
