// GENERATED by `onto probe node_0162` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/laws/query/types.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — QueryShapeSchema is strict and does not allow undefined fields",
    setup: () => ({ unknownField: "value" }),
    invoke: (api, ctx) => {
      try {
        api.QueryShapeSchema.parse(ctx);
        return false;
      } catch {
        return true;
      }
    },
    assert: (r) => r === true,
  },
  {
    name: "valid empty query shape",
    setup: () => ({}),
    invoke: (api, ctx) => api.QueryShapeSchema.parse(ctx),
    assert: (r) => r !== undefined && Object.keys(r).length === 0,
  },
  {
    name: "valid query shape with all fields",
    setup: () => ({
      kind: ["function"],
      abstraction: ["project"],
      plane: ["semantic"],
      manifestation: ["code"],
      status: ["draft"],
      branch: "main",
      provides: ["concept1"],
      requires: ["concept2"],
      forbids: ["concept3"],
      hasIncoming: ["depends_on"],
      hasOutgoing: ["inherits_from"],
    }),
    invoke: (api, ctx) => api.QueryShapeSchema.parse(ctx),
    assert: (r) => r.kind?.[0] === "function" && r.branch === "main",
  },
  {
    name: "valid query shape with only disjunctive fields",
    setup: () => ({
      kind: ["entity", "action"],
      abstraction: ["domain"],
      plane: ["data", "security"],
      manifestation: ["test"],
      status: ["valid", "compiled"],
    }),
    invoke: (api, ctx) => api.QueryShapeSchema.parse(ctx),
    assert: (r) => r.kind?.length === 2 && r.status?.includes("valid"),
  },
  {
    name: "valid query shape with only conjunctive fields",
    setup: () => ({
      provides: ["service", "auth"],
      requires: ["db"],
      forbids: ["legacy"],
      hasIncoming: ["uses_token", "reads_from"],
      hasOutgoing: ["emits", "mutates"],
    }),
    invoke: (api, ctx) => api.QueryShapeSchema.parse(ctx),
    assert: (r) => r.provides?.length === 2 && r.hasOutgoing?.includes("emits"),
  },
  {
    name: "query shape with optional fields omitted",
    setup: () => ({
      branch: "develop",
    }),
    invoke: (api, ctx) => api.QueryShapeSchema.parse(ctx),
    assert: (r) => r.branch === "develop" && Object.keys(r).length === 1,
  },
  {
    name: "query shape with empty arrays",
    setup: () => ({
      kind: [],
      provides: [],
      hasIncoming: [],
    }),
    invoke: (api, ctx) => api.QueryShapeSchema.parse(ctx),
    assert: (r) => Array.isArray(r.kind) && r.kind.length === 0,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6]).has(i));
