// GENERATED by `onto probe node_0213` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/surfaces/walker/state/parse-link-args.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — requires both --to and --type flags",
    setup: () => (""),
    invoke: (api, ctx) => api.parseLinkArgs(ctx),
    assert: (r) => !r.ok && r.message === ":link requires --to <nodeId>",
  },
  {
    name: "rule:2 — rejects explicit --from flag",
    setup: () => ("--from X --to Y --type Z"),
    invoke: (api, ctx) => api.parseLinkArgs(ctx),
    assert: (r) => !r.ok && r.message === "--from is implicit (the focal node); drop it",
  },
  {
    name: "rule:3 — captures rationale as remaining tokens after --rationale",
    setup: () => ("--to node123 --type refines --rationale because this is important"),
    invoke: (api, ctx) => api.parseLinkArgs(ctx),
    assert: (r) => r.ok && r.args?.rationale === "because this is important",
  },
  {
    name: "rule:4 — returns error when --to has no value",
    setup: () => ("--to --type edge"),
    invoke: (api, ctx) => api.parseLinkArgs(ctx),
    assert: (r) => !r.ok && r.message === "--to requires a node id",
  },
  {
    name: "rule:5 — returns error when --type has no value",
    setup: () => ("--to node1 --type"),
    invoke: (api, ctx) => api.parseLinkArgs(ctx),
    assert: (r) => !r.ok && r.message === "--type requires an edge type",
  },
  {
    name: "rule:6 — returns error for unknown flags",
    setup: () => ("--to node1 --type edge --unknown-flag"),
    invoke: (api, ctx) => api.parseLinkArgs(ctx),
    assert: (r) => !r.ok && r.message.startsWith("unknown link flag:"),
  },
  {
    name: "rule:7 — parses valid args with optional rationale",
    setup: () => ("--to targetNode --type connects --rationale linking for traceability"),
    invoke: (api, ctx) => api.parseLinkArgs(ctx),
    assert: (r) => r.ok && r.args?.to === "targetNode" && r.args.type === "connects" && r.args.rationale === "linking for traceability",
  },
  {
    name: "rule:8 — parses minimal valid args without rationale",
    setup: () => ("--to target --type dependency"),
    invoke: (api, ctx) => api.parseLinkArgs(ctx),
    assert: (r) => r.ok && r.args?.to === "target" && r.args.type === "dependency" && r.args.rationale === undefined,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
