// GENERATED by `onto probe node_0149` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 11 self-validated case(s)
// (each matched the source src/runtime/llm/model-capabilities.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — LLM_TASK_KINDS exports correct task kind constants",
    setup: () => ({}),
    invoke: (api) => api.LLM_TASK_KINDS,
    assert: (r) => 
      Array.isArray(r) && 
      r.length === 5 &&
      r[0] === 'structured_extraction' &&
      r[1] === 'reasoning' &&
      r[2] === 'summarization' &&
      r[3] === 'code_generation' &&
      r[4] === 'critique'
  },
  {
    name: "rule:2 — ModelCapabilityProfile interface has correct fields",
    setup: () => ({
      profile: {
        model: "test-model",
        bannedFor: ["reasoning"],
        preferredFor: ["structured_extraction"],
        notes: "test note"
      }
    }),
    invoke: (api, ctx) => ctx.profile,
    assert: (r) => 
      typeof r === 'object' && 
      r !== null &&
      typeof r.model === 'string' &&
      (r.bannedFor === undefined || Array.isArray(r.bannedFor)) &&
      (r.preferredFor === undefined || Array.isArray(r.preferredFor)) &&
      (r.notes === undefined || typeof r.notes === 'string')
  },
  {
    name: "rule:3 — llmTaskToTaskKind maps semantic_parse to structured_extraction",
    setup: () => ({ task: "semantic_parse" as const }),
    invoke: (api, ctx) => api.llmTaskToTaskKind(ctx.task),
    assert: (r) => r === 'structured_extraction'
  },
  {
    name: "rule:3 — llmTaskToTaskKind maps node_critique to critique",
    setup: () => ({ task: "node_critique" as const }),
    invoke: (api, ctx) => api.llmTaskToTaskKind(ctx.task),
    assert: (r) => r === 'critique'
  },
  {
    name: "rule:4 — getCapabilityProfile returns profile for existing model",
    setup: () => ({ model: "qwen2.5-coder:3b" }),
    invoke: (api, ctx) => api.getCapabilityProfile(ctx.model),
    assert: (r) => 
      r !== undefined && 
      r.model === "qwen2.5-coder:3b" &&
      Array.isArray(r.preferredFor) &&
      r.preferredFor.includes("structured_extraction")
  },
  {
    name: "rule:4 — getCapabilityProfile returns undefined for non-existent model",
    setup: () => ({ model: "non-existent-model" }),
    invoke: (api, ctx) => api.getCapabilityProfile(ctx.model),
    assert: (r) => r === undefined
  },
  {
    name: "rule:5 — isModelBannedForTask returns true for banned model/task combination",
    setup: () => ({ model: "deepseek-r1:1.5b", task: "structured_extraction" as const }),
    invoke: (api, ctx) => api.isModelBannedForTask(ctx.model, ctx.task),
    assert: (r) => r === true
  },
  {
    name: "rule:5 — isModelBannedForTask returns false for non-banned model/task combination",
    setup: () => ({ model: "qwen2.5-coder:3b", task: "structured_extraction" as const }),
    invoke: (api, ctx) => api.isModelBannedForTask(ctx.model, ctx.task),
    assert: (r) => r === false
  },
  {
    name: "rule:6 — modelsPreferredForTask returns models for structured_extraction",
    setup: () => ({ task: "structured_extraction" as const }),
    invoke: (api, ctx) => api.modelsPreferredForTask(ctx.task),
    assert: (r) => 
      Array.isArray(r) && 
      r.includes("qwen2.5-coder:3b") &&
      r.includes("llama3.2:3b") &&
      r.includes("claude-sonnet-4-6")
  },
  {
    name: "rule:7 — LlmTaskKindSchema validates correct enum values",
    setup: () => ({ value: "reasoning" as const }),
    invoke: (api, ctx) => api.LlmTaskKindSchema.safeParse(ctx.value),
    assert: (r) => r.success === true
  },
  {
    name: "rule:7 — LlmTaskKindSchema rejects invalid enum values",
    setup: () => ({ value: "invalid_task" }),
    invoke: (api, ctx) => api.LlmTaskKindSchema.safeParse(ctx.value),
    assert: (r) => r.success === false
  },
  {
    name: "rule:8 — ModelCapabilityProfileSchema validates correct profile structure",
    setup: () => ({
      profile: {
        model: "test-model",
        bannedFor: ["reasoning"],
        preferredFor: ["structured_extraction"],
        notes: "test note"
      }
    }),
    invoke: (api, ctx) => api.ModelCapabilityProfileSchema.safeParse(ctx.profile),
    assert: (r) => r.success === true
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11]).has(i));
