// GENERATED by `onto probe node_0145` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/runtime/llm/anthropic/adapter.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { AnthropicAdapterOptions } from "./adapter.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — createAnthropicAdapter returns LlmAdapter with provider anthropic",
    setup: () => ({ apiKey: "test-key" } as AnthropicAdapterOptions),
    invoke: (api, ctx) => {
      const adapter = api.createAnthropicAdapter(ctx);
      return adapter.provider;
    },
    assert: (r) => r === "anthropic",
  },
  {
    name: "rule:2 — dispatchWithRetry retries on 429 error",
    setup: () => {
      let callCount = 0;
      const failingSend = async () => {
        callCount++;
        if (callCount < 2) {
          const err = new Error("Rate limit");
          (err as any).status = 429;
          throw err;
        }
        return "success";
      };
      return { send: failingSend, callCount };
    },
    invoke: async (api, ctx) => {
      const result = await (api as any).dispatchWithRetry(ctx.send);
      return result;
    },
    assert: (r) => r === "success",
  },
  {
    name: "rule:3 — isRetryableTransient identifies 429 as retryable",
    setup: () => {
      const err = new Error("Rate limit");
      (err as any).status = 429;
      return err;
    },
    invoke: (api, ctx) => (api as any).isRetryableTransient(ctx),
    assert: (r) => r === true,
  },
  {
    name: "rule:3 — isRetryableTransient identifies 500 as retryable",
    setup: () => {
      const err = new Error("Server error");
      (err as any).status = 500;
      return err;
    },
    invoke: (api, ctx) => (api as any).isRetryableTransient(ctx),
    assert: (r) => r === true,
  },
  {
    name: "rule:3 — isRetryableTransient identifies ECONNRESET as retryable",
    setup: () => {
      const err = new Error("Connection reset");
      (err as any).code = "ECONNRESET";
      return err;
    },
    invoke: (api, ctx) => (api as any).isRetryableTransient(ctx),
    assert: (r) => r === true,
  },
  {
    name: "rule:3 — isRetryableTransient identifies 400 as non-retryable",
    setup: () => {
      const err = new Error("Bad request");
      (err as any).status = 400;
      return err;
    },
    invoke: (api, ctx) => (api as any).isRetryableTransient(ctx),
    assert: (r) => r === false,
  },
  {
    name: "rule:4 — sleep resolves after specified milliseconds",
    setup: () => 10,
    invoke: async (api, ctx) => {
      const start = Date.now();
      await (api as any).sleep(ctx);
      return Date.now() - start;
    },
    assert: (r) => r >= 10,
  },
  {
    name: "rule:5 — AnthropicAdapterOptions allows apiKey and defaultModel",
    setup: () => ({
      apiKey: "test-key",
      defaultModel: "claude-opus-4-7",
    } as AnthropicAdapterOptions),
    invoke: (api, ctx) => ctx,
    assert: (r) => 
      r.apiKey === "test-key" && 
      r.defaultModel === "claude-opus-4-7",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
