// GENERATED by `onto probe node_0163` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 10 self-validated case(s)
// (each matched the source src/kernel/semantic/embedding-index.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — resolveEmbeddingAdapter returns mock adapter when provider is mock",
    setup: () => ({ provider: "mock" as const }),
    invoke: (api, ctx) => api.resolveEmbeddingAdapter(ctx.provider),
    assert: (r) => r != null && typeof r === "object" && "embed" in r,
  },
  {
    name: "rule:2 — resolveEmbeddingAdapter returns ollama adapter when provider is ollama",
    setup: () => ({ provider: "ollama" as const }),
    invoke: (api, ctx) => api.resolveEmbeddingAdapter(ctx.provider),
    assert: (r) => r != null && typeof r === "object" && "embed" in r,
  },
  {
    name: "rule:3 — resolveEmbeddingAdapter throws for unsupported provider",
    setup: () => ({ provider: "unsupported" as any }),
    invoke: (api, ctx) => {
      try {
        api.resolveEmbeddingAdapter(ctx.provider);
        return false;
      } catch {
        return true;
      }
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:4 — cosineSimilarity returns 0 for empty arrays",
    setup: () => ({ a: [], b: [] }),
    invoke: (api, ctx) => api.cosineSimilarity(ctx.a, ctx.b),
    assert: (r) => r === 0,
  },
  {
    name: "rule:5 — cosineSimilarity returns 1 for identical vectors",
    setup: () => ({ a: [1, 0, 0], b: [1, 0, 0] }),
    invoke: (api, ctx) => api.cosineSimilarity(ctx.a, ctx.b),
    assert: (r) => r === 1,
  },
  {
    name: "rule:6 — cosineSimilarity returns 0 for orthogonal vectors",
    setup: () => ({ a: [1, 0, 0], b: [0, 1, 0] }),
    invoke: (api, ctx) => api.cosineSimilarity(ctx.a, ctx.b),
    assert: (r) => r === 0,
  },
  {
    name: "rule:7 — cosineSimilarity returns value between 0 and 1 for general vectors",
    setup: () => ({ a: [1, 1, 0], b: [1, 0, 0] }),
    invoke: (api, ctx) => api.cosineSimilarity(ctx.a, ctx.b),
    assert: (r) => r >= 0 && r <= 1,
  },
  {
    name: "rule:8 — rankBySimilarity respects top limit",
    setup: () => ({
      index: {
        version: 1,
        provider: "mock",
        model: "mock_embed",
        dim: 3,
        createdAt: "2023-01-01T00:00:00.000Z",
        entries: [
          { nodeId: "a", sourceHash: "hash1", vector: [1, 0, 0] },
          { nodeId: "b", sourceHash: "hash2", vector: [0, 1, 0] },
          { nodeId: "c", sourceHash: "hash3", vector: [0, 0, 1] },
        ],
      },
      queryVector: [1, 0, 0],
      options: { top: 2 },
    }),
    invoke: (api, ctx) => api.rankBySimilarity(ctx.index, ctx.queryVector, ctx.options),
    assert: (r) => Array.isArray(r) && r.length <= 2,
  },
  {
    name: "rule:9 — rankBySimilarity respects minScore threshold",
    setup: () => ({
      index: {
        version: 1,
        provider: "mock",
        model: "mock_embed",
        dim: 3,
        createdAt: "2023-01-01T00:00:00.000Z",
        entries: [
          { nodeId: "a", sourceHash: "hash1", vector: [1, 0, 0] },
          { nodeId: "b", sourceHash: "hash2", vector: [0.5, 0.5, 0] },
          { nodeId: "c", sourceHash: "hash3", vector: [0, 0, 1] },
        ],
      },
      queryVector: [1, 0, 0],
      options: { minScore: 0.6 },
    }),
    invoke: (api, ctx) => api.rankBySimilarity(ctx.index, ctx.queryVector, ctx.options),
    assert: (r) => Array.isArray(r) && r.every((item) => item.score >= 0.6),
  },
  {
    name: "rule:10 — staleIndexNodeIds returns empty array when all nodes match",
    setup: () => {
      const text = "test node text";
      const provider = "mock";
      const model = "mock_embed";
      const sourceHash = require("crypto")
        .createHash("sha256")
        .update(`${provider}\u0000${model}\u0000${text}`)
        .digest("hex");
      return {
        index: {
          version: 1,
          provider,
          model,
          dim: 3,
          createdAt: "2023-01-01T00:00:00.000Z",
          entries: [{ nodeId: "node1", sourceHash, vector: [1, 0, 0] }],
        },
        nodes: [
          {
            id: "node1",
            label: "Test Node",
            prompt: { raw: "test prompt" },
            rules: [],
            context: { provides: [] },
            coordinates: { branch: "main", path: "test" },
          },
        ],
      };
    },
    invoke: (api, ctx) => {
      // Manually override embeddingSourceText to return known text
      const original = (api as any).embeddingSourceText;
      (api as any).embeddingSourceText = () => "test node text";
      try {
        return api.staleIndexNodeIds(ctx.index, ctx.nodes);
      } finally {
        (api as any).embeddingSourceText = original;
      }
    },
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
  {
    name: "rule:11 — staleIndexNodeIds returns node ID when text has changed",
    setup: () => ({
      index: {
        version: 1,
        provider: "mock",
        model: "mock_embed",
        dim: 3,
        createdAt: "2023-01-01T00:00:00.000Z",
        entries: [
          {
            nodeId: "node1",
            sourceHash: "old_hash", // This will not match the current hash
            vector: [1, 0, 0],
          },
        ],
      },
      nodes: [
        {
          id: "node1",
          label: "Test Node",
          prompt: { raw: "updated prompt" },
          rules: [],
          context: { provides: [] },
          coordinates: { branch: "main", path: "test" },
        },
      ],
    }),
    invoke: (api, ctx) => {
      // Override embeddingSourceText to return predictable text
      const original = (api as any).embeddingSourceText;
      (api as any).embeddingSourceText = (node: any) => node.label + (node.prompt?.raw ?? "");
      try {
        return api.staleIndexNodeIds(ctx.index, ctx.nodes);
      } finally {
        (api as any).embeddingSourceText = original;
      }
    },
    assert: (r) => Array.isArray(r) && r.includes("node1"),
  },
  {
    name: "rule:12 — embeddingSourceText combines label, prompt, rules and provides",
    setup: () => ({
      node: {
        id: "test-node",
        label: "Test Label",
        prompt: { raw: "Test prompt" },
        rules: ["Rule 1", "Rule 2"],
        context: {
          provides: [
            { key: "key1", description: "Description 1" },
            { key: "key2", description: "" },
          ],
        },
        coordinates: { branch: "main", path: "test" },
      },
    }),
    invoke: (api, ctx) => api.embeddingSourceText(ctx.node),
    assert: (r) =>
      typeof r === "string" &&
      r.includes("Test Label") &&
      r.includes("Test prompt") &&
      r.includes("Rule 1") &&
      r.includes("Rule 2") &&
      r.includes("key1: Description 1") &&
      r.includes("key2"),
  },
  {
    name: "rule:13 — embeddingSourceHash produces consistent hash",
    setup: () => ({
      text: "test text",
      provider: "mock",
      model: "mock_embed",
    }),
    invoke: (api, ctx) => api.embeddingSourceHash(ctx.text, ctx.provider, ctx.model),
    assert: (r) => typeof r === "string" && r.length === 64, // SHA256 hex is 64 chars
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([2, 3, 4, 5, 6, 7, 8, 10, 11, 12]).has(i));
