// GENERATED by `onto probe node_0134` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/laws/matrix-intersections.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type {
  PerNodeMatrix,
  MatrixCell,
  FrontierAttribute,
  ContractState,
  StructuralState,
  BehaviorState,
  IntentState,
  LiteralRequiredState,
} from "../../src/laws/matrix.js";
import type { IntersectionSpec } from "../../src/laws/matrix-intersections.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — REQUIRED_INTERSECTIONS has exactly seven entries",
    setup: () => ({}),
    invoke: (api) => (api as any).REQUIRED_INTERSECTIONS.length,
    assert: (r) => r === 7,
  },
  {
    name: "rule:2 — entryMatchesIntersection returns true when all tags match and no axisStates",
    setup: () => {
      const entry: PerNodeMatrix = {
        frontier: ["io-bound", "structural-drift"],
        cell: {},
      } as PerNodeMatrix;
      const spec: IntersectionSpec = {
        name: "test",
        tags: ["io-bound", "structural-drift"],
      };
      return { entry, spec };
    },
    invoke: (api, ctx) => (api as any).entryMatchesIntersection(ctx.entry, ctx.spec),
    assert: (r) => r === true,
  },
  {
    name: "rule:3 — entryMatchesIntersection returns false when a tag is missing",
    setup: () => {
      const entry: PerNodeMatrix = {
        frontier: ["io-bound"],
        cell: {},
      } as PerNodeMatrix;
      const spec: IntersectionSpec = {
        name: "test",
        tags: ["io-bound", "structural-drift"],
      };
      return { entry, spec };
    },
    invoke: (api, ctx) => (api as any).entryMatchesIntersection(ctx.entry, ctx.spec),
    assert: (r) => r === false,
  },
  {
    name: "rule:4 — entryMatchesIntersection checks axisStates when present and matches",
    setup: () => {
      const entry: PerNodeMatrix = {
        frontier: ["schema-driven"],
        cell: { contract: "pass" },
      } as PerNodeMatrix;
      const spec: IntersectionSpec = {
        name: "test",
        tags: ["schema-driven"],
        axisStates: { contract: "pass" },
      };
      return { entry, spec };
    },
    invoke: (api, ctx) => (api as any).entryMatchesIntersection(ctx.entry, ctx.spec),
    assert: (r) => r === true,
  },
  {
    name: "rule:5 — entryMatchesIntersection fails when axisStates mismatch",
    setup: () => {
      const entry: PerNodeMatrix = {
        frontier: ["schema-driven"],
        cell: { contract: "fail" },
      } as PerNodeMatrix;
      const spec: IntersectionSpec = {
        name: "test",
        tags: ["schema-driven"],
        axisStates: { contract: "pass" },
      };
      return { entry, spec };
    },
    invoke: (api, ctx) => (api as any).entryMatchesIntersection(ctx.entry, ctx.spec),
    assert: (r) => r === false,
  },
  {
    name: "rule:6 — aggregateByIntersection includes all required intersections with zero counts when no matches",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        {
          frontier: ["unrelated-tag"],
          cell: {},
        } as PerNodeMatrix,
      ];
      return { matrix };
    },
    invoke: (api, ctx) => (api as any).aggregateByIntersection(ctx.matrix),
    assert: (r) => {
      const requiredNames = [
        "io-bound ∧ structural-drift",
        "io-bound ∧ behavior-drift",
        "literal-required ∧ prompt-sensitive",
        "cli-parsing ∧ behavior-drift",
        "schema-driven ∧ contract-equivalent",
        "pure-transform ∧ behavior-equivalent",
        "contract-missing ∧ not-reviewed",
      ];
      for (const name of requiredNames) {
        if (!(name in r) || r[name] !== 0) return false;
      }
      return true;
    },
  },
  {
    name: "rule:7 — aggregateByIntersection counts matches correctly",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        {
          frontier: ["io-bound", "structural-drift"],
          cell: {},
        } as PerNodeMatrix,
        {
          frontier: ["io-bound", "structural-drift"],
          cell: {},
        } as PerNodeMatrix,
      ];
      return { matrix };
    },
    invoke: (api, ctx) => (api as any).aggregateByIntersection(ctx.matrix),
    assert: (r) => r["io-bound ∧ structural-drift"] === 2,
  },
  {
    name: "rule:8 — aggregateByIntersection merges additional specs and preserves shape",
    setup: () => {
      const matrix: PerNodeMatrix[] = [
        {
          frontier: ["custom-tag-a", "custom-tag-b"],
          cell: {},
        } as PerNodeMatrix,
      ];
      const additional: IntersectionSpec[] = [
        { name: "custom-intersection", tags: ["custom-tag-a", "custom-tag-b"] },
      ];
      return { matrix, additional };
    },
    invoke: (api, ctx) =>
      (api as any).aggregateByIntersection(ctx.matrix, ctx.additional),
    assert: (r) => {
      return (
        "io-bound ∧ structural-drift" in r &&
        r["custom-intersection"] === 1 &&
        r["io-bound ∧ structural-drift"] === 0
      );
    },
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
