// GENERATED by `onto probe node_0121` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 14 self-validated case(s)
// (each matched the source src/kernel/graph/hierarchy-metrics.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — computeHierarchyMetrics returns correct schema version",
    setup: () => ({
      input: {
        nodes: [],
        edges: [],
      },
    }),
    invoke: (api, ctx) => api.computeHierarchyMetrics(ctx.input),
    assert: (r) => r.schemaVersion === "1.1",
  },
  {
    name: "rule:2 — resolveRoot returns explicit when valid override provided",
    setup: () => ({
      override: "root1",
      nodes: [
        { id: "root1", graph: { parentId: null }, coordinates: { abstraction: "concrete", branch: "main" } },
      ] as any[],
    }),
    invoke: (api, ctx) => (api as any).resolveRoot(ctx.override, ctx.nodes),
    assert: (r) => r.rootNodeId === "root1" && r.detection === "explicit",
  },
  {
    name: "rule:3 — buildReachabilitySet includes consumer and ancestors",
    setup: () => {
      const nodeById = new Map([
        ["n1", { id: "n1", graph: { parentId: null }, coordinates: { abstraction: "concrete", branch: "main" } }],
        ["n2", { id: "n2", graph: { parentId: "n1" }, coordinates: { abstraction: "concrete", branch: "main" } }],
      ]);
      const adjByNode = new Map();
      const consumer = nodeById.get("n2")!;
      return { consumer, nodeById, adjByNode, branch: "main" };
    },
    invoke: (api, ctx) => (api as any).buildReachabilitySet(ctx.consumer, ctx.nodeById, ctx.adjByNode, ctx.branch),
    assert: (r) => r.has("n2") && r.has("n1"),
  },
  {
    name: "rule:4 — sortRecord produces lexicographically sorted keys",
    setup: () => ({
      counts: new Map([["z", 1], ["a", 2], ["m", 3]]),
    }),
    invoke: (api, ctx) => (api as any).sortRecord(ctx.counts),
    assert: (r) => Object.keys(r).join(",") === "a,m,z",
  },
  {
    name: "rule:5 — summariseSatisfaction computes ratio and top unsatisfied",
    setup: () => ({
      satisfied: [{ source: "a", consumer: "c1" }],
      unsatisfied: [{ source: "b", consumer: "c2" }, { source: "b", consumer: "c3" }],
      topN: 5,
    }),
    invoke: (api, ctx) => (api as any).summariseSatisfaction(ctx.satisfied, ctx.unsatisfied, ctx.topN),
    assert: (r) => r.ratio === 0.3333333333333333 && r.topUnsatisfied[0].source === "b" && r.topUnsatisfied[0].consumers === 2,
  },
  {
    name: "rule:6 — classifyRequire returns internal_symbol when hasGlobalProvider is true",
    setup: () => ({
      source: "some-source",
      hasGlobalProvider: true,
      consumer: { id: "c1", coordinates: { branch: "main" } },
      fileToNodeIds: new Map(),
    }),
    invoke: (api, ctx) => (api as any).classifyRequire(ctx.source, ctx.hasGlobalProvider, ctx.consumer, ctx.fileToNodeIds),
    assert: (r) => r.class === "internal_symbol" && r.resolvedNodeId === null,
  },
  {
    name: "rule:7 — isPathLike identifies relative paths",
    setup: () => ({ source: "./relative/path" }),
    invoke: (api, ctx) => (api as any).isPathLike(ctx.source),
    assert: (r) => r === true,
  },
  {
    name: "rule:8 — isOpenWorldName identifies node-prefixed modules",
    setup: () => ({ source: "node:fs" }),
    invoke: (api, ctx) => (api as any).isOpenWorldName(ctx.source),
    assert: (r) => r === true,
  },
  {
    name: "rule:9 — resolvePathToNode resolves relative path with extension variants",
    setup: () => {
      const source = "./file.js";
      const consumer = { outputs: { files: ["dir/consumer.ts"] } };
      const fileToNodeIds = new Map([["dir/file.ts", ["node1"]]]);
      return { source, consumer, fileToNodeIds };
    },
    invoke: (api, ctx) => (api as any).resolvePathToNode(ctx.source, ctx.consumer, ctx.fileToNodeIds),
    assert: (r) => r === "node1",
  },
  {
    name: "rule:10 — generateExtensionVariants produces ts variants for js files",
    setup: () => ({ p: "dir/file.js" }),
    invoke: (api, ctx) => (api as any).generateExtensionVariants(ctx.p),
    assert: (r) => r.includes("dir/file.ts") && r.includes("dir/file.tsx"),
  },
  {
    name: "rule:11 — topByConsumerCount ranks sources by consumer count",
    setup: () => ({
      pairs: [
        { source: "a", consumer: "c1" },
        { source: "a", consumer: "c2" },
        { source: "b", consumer: "c3" },
      ],
      topN: 5,
    }),
    invoke: (api, ctx) => (api as any).topByConsumerCount(ctx.pairs, ctx.topN),
    assert: (r) => r[0].source === "a" && r[0].consumers === 2,
  },
  {
    name: "rule:12 — rollUpPathMismatches groups by source and counts consumers",
    setup: () => ({
      pairs: [
        { source: "a", consumer: "c1", resolvedNodeId: "n1" },
        { source: "a", consumer: "c2", resolvedNodeId: "n1" },
        { source: "b", consumer: "c3", resolvedNodeId: null },
      ],
      topN: 5,
    }),
    invoke: (api, ctx) => (api as any).rollUpPathMismatches(ctx.pairs, ctx.topN),
    assert: (r) => r[0].source === "a" && r[0].consumers === 2 && r[0].resolvedNodeId === "n1",
  },
  {
    name: "rule:13 — computeVerdict returns flat when nonRootDirectChildrenOfRootRatio >= 0.8",
    setup: () => ({
      nodeCount: 10,
      edgeCount: 5,
      edgePerNode: 0.5,
      maxDepth: 1,
      nonRootDirectChildrenOfRootRatio: 0.9,
      contractTokenCount: 0,
    }),
    invoke: (api, ctx) => (api as any).computeVerdict(ctx),
    assert: (r) => r === "flat",
  },
  {
    name: "rule:14 — summariseFlatness formats metrics into single line string",
    setup: () => ({
      metrics: {
        flatness: {
          verdict: "healthy",
          edgeCount: 10,
          maxDepth: 3,
          nonRootDirectChildrenOfRootRatio: 0.25,
          isolatedNodeRatio: 0.1,
        },
        topology: { nodeCount: 20 },
      } as any,
    }),
    invoke: (api, ctx) => (api as any).summariseFlatness(ctx.metrics),
    assert: (r) => r === "verdict=healthy nodes=20 edges=10 maxDepth=3 directChildrenRatio=0.25 isolatedRatio=0.10",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]).has(i));
