// GENERATED by `onto probe node_0100` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 3 self-validated case(s)
// (each matched the source src/forward/context/assembler.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — throws on unsupported mode",
    setup: () => ({
      input: {
        targetNodeId: "test-node-1",
        mode: "unsupported-mode"
      },
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => {
      try {
        return api.assembleContext(ctx.input, ctx.cwd);
      } catch (e) {
        return e instanceof Error ? e.message : "unknown error";
      }
    },
    assert: (r) => r === "Unsupported context assembly mode: unsupported-mode"
  },
  {
    name: "rule:2 — throws when target node not found",
    setup: () => ({
      input: {
        targetNodeId: "nonexistent-node"
      },
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => {
      try {
        return api.assembleContext(ctx.input, ctx.cwd);
      } catch (e) {
        return e instanceof Error ? e.message : "unknown error";
      }
    },
    assert: (r) => r === "Target node not found: nonexistent-node"
  },
  {
    name: "rule:3 — throws on branch mismatch",
    setup: () => ({
      input: {
        targetNodeId: "node-with-branch-mismatch"
      },
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => {
      try {
        return api.assembleContext(ctx.input, ctx.cwd);
      } catch (e) {
        return e instanceof Error ? e.message : "unknown error";
      }
    },
    assert: (r) => r.includes("Branch mismatch for node")
  },
  {
    name: "rule:4 — throws on parent cycle detection",
    setup: () => ({
      input: {
        targetNodeId: "node-with-cycle"
      },
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => {
      try {
        return api.assembleContext(ctx.input, ctx.cwd);
      } catch (e) {
        return e instanceof Error ? e.message : "unknown error";
      }
    },
    assert: (r) => r.includes("Parent cycle detected")
  },
  {
    name: "rule:5 — throws when context path does not terminate at root",
    setup: () => ({
      input: {
        targetNodeId: "node-not-reaching-root"
      },
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => {
      try {
        return api.assembleContext(ctx.input, ctx.cwd);
      } catch (e) {
        return e instanceof Error ? e.message : "unknown error";
      }
    },
    assert: (r) => r.includes("Context path does not terminate at root")
  },
  {
    name: "rule:6 — includes edges when includeEdges is true",
    setup: () => ({
      input: {
        targetNodeId: "node-with-edges",
        includeEdges: true
      },
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => api.assembleContext(ctx.input, ctx.cwd),
    assert: (r) => r.edgeContext !== undefined
  },
  {
    name: "rule:7 — excludes edges when includeEdges is false",
    setup: () => ({
      input: {
        targetNodeId: "node-with-edges",
        includeEdges: false
      },
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => api.assembleContext(ctx.input, ctx.cwd),
    assert: (r) => r.edgeContext === undefined
  },
  {
    name: "rule:8 — extracts canon from rules when available",
    setup: () => ({
      input: {
        targetNodeId: "node-with-canonical-rule"
      },
      cwd: "/test/project"
    }),
    invoke: (api, ctx) => api.assembleContext(ctx.input, ctx.cwd),
    assert: (r) => typeof r.canon === "string"
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([5, 6, 7]).has(i));
