// GENERATED by `onto probe node_0225` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 15 self-validated case(s)
// (each matched the source src/runtime/legend/reps-aggregator.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "median throws on empty list",
    setup: () => ({ xs: [] as number[] }),
    invoke: (api, ctx) => {
      try {
        (api as any).median((ctx as any).xs);
        return { threw: false, msg: "" };
      } catch (e) {
        return { threw: true, msg: (e as Error).message };
      }
    },
    assert: (r) => r.threw === true && r.msg === "median: empty list",
  },
  {
    name: "median of odd-length list returns the middle of the sorted copy",
    setup: () => ({ xs: [3, 1, 2] }),
    invoke: (api, ctx) => (api as any).median((ctx as any).xs),
    assert: (r) => r === 2,
  },
  {
    name: "median of even-length list returns mean of two middle values",
    setup: () => ({ xs: [4, 1, 3, 2] }),
    invoke: (api, ctx) => (api as any).median((ctx as any).xs),
    assert: (r) => r === 2.5,
  },
  {
    name: "median does not mutate the input array",
    setup: () => ({ xs: [3, 1, 2] }),
    invoke: (api, ctx) => {
      (api as any).median((ctx as any).xs);
      return (ctx as any).xs;
    },
    assert: (r) =>
      Array.isArray(r) &&
      r.length === 3 &&
      r[0] === 3 &&
      r[1] === 1 &&
      r[2] === 2,
  },
  {
    name: "mean throws on empty list",
    setup: () => ({ xs: [] as number[] }),
    invoke: (api, ctx) => {
      try {
        (api as any).mean((ctx as any).xs);
        return { threw: false, msg: "" };
      } catch (e) {
        return { threw: true, msg: (e as Error).message };
      }
    },
    assert: (r) => r.threw === true && r.msg === "mean: empty list",
  },
  {
    name: "mean returns arithmetic mean (sum / length)",
    setup: () => ({ xs: [1, 2, 3, 4] }),
    invoke: (api, ctx) => (api as any).mean((ctx as any).xs),
    assert: (r) => r === 2.5,
  },
  {
    name: "aggregateDistanceMetrics throws on empty rep list",
    setup: () => ({ reps: [] as any[] }),
    invoke: (api, ctx) => {
      try {
        (api as any).aggregateDistanceMetrics((ctx as any).reps);
        return { threw: false, msg: "" };
      } catch (e) {
        return { threw: true, msg: (e as Error).message };
      }
    },
    assert: (r) =>
      r.threw === true && r.msg === "aggregateDistanceMetrics: empty rep list",
  },
  {
    name: "aggregateDistanceMetrics (median default) folds numeric axes and picks closest-Jaccard regenDeclarations",
    setup: () => ({
      reps: [
        {
          locDistance: 10,
          structuralJaccard: 0.2,
          originalLineCount: 100,
          regenLineCount: 90,
          originalDeclarations: ["a", "b"],
          regenDeclarations: ["r0"],
        },
        {
          locDistance: 20,
          structuralJaccard: 0.6,
          originalLineCount: 999,
          regenLineCount: 110,
          originalDeclarations: ["x"],
          regenDeclarations: ["r1"],
        },
        {
          locDistance: 30,
          structuralJaccard: 0.8,
          originalLineCount: 7,
          regenLineCount: 130,
          originalDeclarations: ["y"],
          regenDeclarations: ["r2"],
        },
      ],
    }),
    // median loc = 20, median jaccard = 0.6, median regenLines = round(110)=110.
    // originalLineCount/originalDeclarations from reps[0] => 100 / ["a","b"].
    // closest jaccard to 0.6 is reps[1] (diff 0) => regenDeclarations ["r1"].
    invoke: (api, ctx) =>
      (api as any).aggregateDistanceMetrics((ctx as any).reps),
    assert: (r) =>
      r.locDistance === 20 &&
      r.structuralJaccard === 0.6 &&
      r.regenLineCount === 110 &&
      r.originalLineCount === 100 &&
      Array.isArray(r.originalDeclarations) &&
      r.originalDeclarations.length === 2 &&
      r.originalDeclarations[0] === "a" &&
      r.originalDeclarations[1] === "b" &&
      Array.isArray(r.regenDeclarations) &&
      r.regenDeclarations.length === 1 &&
      r.regenDeclarations[0] === "r1",
  },
  {
    name: "aggregateDistanceMetrics with mean aggregator rounds regenLineCount via Math.round",
    setup: () => ({
      reps: [
        {
          locDistance: 0,
          structuralJaccard: 0.0,
          originalLineCount: 50,
          regenLineCount: 10,
          originalDeclarations: ["d0"],
          regenDeclarations: ["g0"],
        },
        {
          locDistance: 2,
          structuralJaccard: 1.0,
          originalLineCount: 50,
          regenLineCount: 11,
          originalDeclarations: ["d0"],
          regenDeclarations: ["g1"],
        },
      ],
    }),
    // mean loc = 1, mean jaccard = 0.5, mean regenLines = round(10.5)=11 (round half up).
    // tie on |jaccard-0.5|: both diff 0.5 => first occurrence wins => regenDeclarations ["g0"].
    invoke: (api, ctx) =>
      (api as any).aggregateDistanceMetrics((ctx as any).reps, "mean"),
    assert: (r) =>
      r.locDistance === 1 &&
      r.structuralJaccard === 0.5 &&
      r.regenLineCount === 11 &&
      r.regenDeclarations[0] === "g0",
  },
  {
    name: "aggregateUsage returns undefined when no rep carries usage",
    setup: () => ({
      reps: [
        { nodeId: "n", sourceFile: "f", ok: true, verdict: "ok" },
        { nodeId: "n", sourceFile: "f", ok: false, verdict: "unrecoverable" },
      ] as any[],
    }),
    invoke: (api, ctx) => (api as any).aggregateUsage((ctx as any).reps),
    assert: (r) => r === undefined,
  },
  {
    name: "aggregateUsage sums defined fields and sets cached true only when every usage rep was cached",
    setup: () => ({
      reps: [
        {
          nodeId: "n",
          sourceFile: "f",
          ok: true,
          verdict: "ok",
          usage: {
            promptTokens: 100,
            completionTokens: 50,
            totalTokens: 150,
            costUSD: 0.01,
            cached: true,
          },
        },
        {
          nodeId: "n",
          sourceFile: "f",
          ok: true,
          verdict: "ok",
          usage: {
            promptTokens: 200,
            completionTokens: 60,
            totalTokens: 260,
            costUSD: 0.02,
            cached: false,
          },
        },
      ] as any[],
    }),
    invoke: (api, ctx) => (api as any).aggregateUsage((ctx as any).reps),
    assert: (r) =>
      r !== undefined &&
      r.promptTokens === 300 &&
      r.completionTokens === 110 &&
      r.totalTokens === 410 &&
      Math.abs(r.costUSD - 0.03) < 1e-9 &&
      r.cached === undefined,
  },
  {
    name: "aggregateUsage only sets a field when at least one rep defined it, cached when all cached",
    setup: () => ({
      reps: [
        {
          nodeId: "n",
          sourceFile: "f",
          ok: true,
          verdict: "ok",
          usage: { promptTokens: 5, cached: true },
        },
        {
          nodeId: "n",
          sourceFile: "f",
          ok: true,
          verdict: "ok",
          usage: { promptTokens: 7, cached: true },
        },
      ] as any[],
    }),
    invoke: (api, ctx) => (api as any).aggregateUsage((ctx as any).reps),
    assert: (r) =>
      r !== undefined &&
      r.promptTokens === 12 &&
      r.completionTokens === undefined &&
      r.totalTokens === undefined &&
      r.costUSD === undefined &&
      r.cached === true,
  },
  {
    name: "aggregateRepResults throws on empty rep list",
    setup: () => ({
      reps: [] as any[],
      options: { thresholds: {} as any },
    }),
    invoke: (api, ctx) => {
      try {
        (api as any).aggregateRepResults(
          (ctx as any).reps,
          (ctx as any).options,
        );
        return { threw: false, msg: "" };
      } catch (e) {
        return { threw: true, msg: (e as Error).message };
      }
    },
    assert: (r) =>
      r.threw === true && r.msg === "aggregateRepResults: empty rep list",
  },
  {
    name: "aggregateRepResults all-unrecoverable cohort returns unrecoverable aggregate with first failure",
    setup: () => ({
      reps: [
        {
          nodeId: "node-A",
          sourceFile: "src/A.ts",
          ok: false,
          verdict: "unrecoverable",
        },
        {
          nodeId: "node-A",
          sourceFile: "src/A.ts",
          ok: false,
          verdict: "unrecoverable",
          failure: "boom",
        },
      ] as any[],
      options: { thresholds: { tag: "t" } as any },
    }),
    invoke: (api, ctx) =>
      (api as any).aggregateRepResults(
        (ctx as any).reps,
        (ctx as any).options,
      ),
    assert: (r) =>
      r.ok === false &&
      r.nodeId === "node-A" &&
      r.sourceFile === "src/A.ts" &&
      r.verdict === "unrecoverable" &&
      r.failure === "boom" &&
      r.thresholds.tag === "t" &&
      r.usage === undefined &&
      r.dispatchModel === undefined &&
      r.reps.count === 2 &&
      r.reps.aggregator === "median" &&
      r.reps.successCount === 0 &&
      Array.isArray(r.reps.perRepMetrics) &&
      r.reps.perRepMetrics.length === 2 &&
      r.reps.perRepMetrics[0] === null &&
      r.reps.perRepMetrics[1] === null &&
      Array.isArray(r.reps.perRepVerdicts) &&
      r.reps.perRepVerdicts.length === 2,
  },
  {
    name: "aggregateRepResults all-unrecoverable with no failure messages falls back to default string",
    setup: () => ({
      reps: [
        {
          nodeId: "node-B",
          sourceFile: "src/B.ts",
          ok: false,
          verdict: "unrecoverable",
        },
      ] as any[],
      options: { thresholds: {} as any },
    }),
    invoke: (api, ctx) =>
      (api as any).aggregateRepResults(
        (ctx as any).reps,
        (ctx as any).options,
      ),
    assert: (r) =>
      r.ok === false &&
      r.failure === "all reps unrecoverable" &&
      r.verdict === "unrecoverable" &&
      r.reps.successCount === 0,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).has(i));
