// GENERATED by `onto probe node_0141` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/inverse/translator.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { OntologyNode } from "../src/kernel/schemas/ontology.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — computeTranslatorSourceHash includes all relevant fields",
    setup: () => ({
      node: {
        id: "test-node",
        label: "Test Node",
        kind: "test",
        prompt: { raw: "test prompt" },
        rules: ["rule1", "rule2"],
        context: {
          provides: [{ key: "provide1" }, { key: "provide2" }],
          requires: [{ source: "require1" }, { source: "require2" }],
          forbids: [{ source: "forbid1" }],
        },
        literal: "test literal",
        translator: null,
      } as OntologyNode,
    }),
    invoke: (api, ctx) => api.computeTranslatorSourceHash(ctx.node),
    assert: (r) => typeof r === "string" && r.length === 64,
  },
  {
    name: "rule:2 — computeTranslatorSourceHash produces stable output",
    setup: () => {
      const node1: OntologyNode = {
        id: "test-node",
        label: "Test Node",
        kind: "test",
        prompt: { raw: "test prompt" },
        rules: ["rule1", "rule2"],
        context: {
          provides: [{ key: "provide1" }, { key: "provide2" }],
          requires: [{ source: "require1" }, { source: "require2" }],
          forbids: [{ source: "forbid1" }],
        },
        literal: "test literal",
        translator: null,
      };
      const node2: OntologyNode = {
        id: "test-node",
        label: "Test Node",
        kind: "test",
        prompt: { raw: "test prompt" },
        rules: ["rule2", "rule1"], // Different order
        context: {
          provides: [{ key: "provide2" }, { key: "provide1" }], // Different order
          requires: [{ source: "require2" }, { source: "require1" }], // Different order
          forbids: [{ source: "forbid1" }],
        },
        literal: "test literal",
        translator: null,
      };
      return { node1, node2 };
    },
    invoke: (api, ctx) => {
      const hash1 = api.computeTranslatorSourceHash(ctx.node1);
      const hash2 = api.computeTranslatorSourceHash(ctx.node2);
      return hash1 === hash2;
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:3 — checkTranslatorCache returns miss when no translator",
    setup: () => ({
      node: {
        id: "test-node",
        label: "Test Node",
        kind: "test",
        prompt: { raw: "test prompt" },
        rules: ["rule1"],
        context: {
          provides: [{ key: "provide1" }],
          requires: [{ source: "require1" }],
          forbids: [{ source: "forbid1" }],
        },
        literal: "test literal",
        translator: null,
      } as OntologyNode,
    }),
    invoke: (api, ctx) => api.checkTranslatorCache(ctx.node),
    assert: (r) => r.hit === false && r.reason === "no_translator",
  },
  {
    name: "rule:4 — checkTranslatorCache returns hit when hash matches",
    setup: () => {
      const node: OntologyNode = {
        id: "test-node",
        label: "Test Node",
        kind: "test",
        prompt: { raw: "test prompt" },
        rules: ["rule1"],
        context: {
          provides: [{ key: "provide1" }],
          requires: [{ source: "require1" }],
          forbids: [{ source: "forbid1" }],
        },
        literal: "test literal",
        translator: {
          text: "cached text",
          model: "test-model",
          provider: "test-provider",
          generatedAt: "2023-01-01T00:00:00Z",
          sourceHash: "", // Will be filled after computing hash
        },
      };
      const hash = require("../src/inverse/translator.js").computeTranslatorSourceHash(node);
      node.translator!.sourceHash = hash;
      return { node };
    },
    invoke: (api, ctx) => api.checkTranslatorCache(ctx.node),
    assert: (r) => r.hit === true && r.text === "cached text",
  },
  {
    name: "rule:5 — checkTranslatorCache returns miss when hash differs",
    setup: () => ({
      node: {
        id: "test-node",
        label: "Test Node",
        kind: "test",
        prompt: { raw: "test prompt" },
        rules: ["rule1"],
        context: {
          provides: [{ key: "provide1" }],
          requires: [{ source: "require1" }],
          forbids: [{ source: "forbid1" }],
        },
        literal: "test literal",
        translator: {
          text: "cached text",
          model: "test-model",
          provider: "test-provider",
          generatedAt: "2023-01-01T00:00:00Z",
          sourceHash: "different-hash",
        },
      } as OntologyNode,
    }),
    invoke: (api, ctx) => api.checkTranslatorCache(ctx.node),
    assert: (r) => r.hit === false && r.reason === "source_changed",
  },
  {
    name: "rule:6 — buildInspectorPrompt formats node information correctly",
    setup: () => ({
      node: {
        id: "test-node",
        label: "Test Node",
        kind: "test",
        prompt: { raw: "test prompt" },
        rules: ["rule1", "rule2"],
        context: {
          provides: [{ key: "provide1" }],
          requires: [{ source: "require1" }],
          forbids: [{ source: "forbid1" }],
        },
        literal: "test literal",
        translator: null,
      } as OntologyNode,
    }),
    invoke: (api, ctx) => api.buildInspectorPrompt(ctx.node),
    assert: (r) => 
      r.includes("Node id:    test-node") &&
      r.includes("Node label: Test Node") &&
      r.includes("Node kind:  test") &&
      r.includes("Assembled prompt:") &&
      r.includes("test prompt") &&
      r.includes("Contract:") &&
      r.includes("provides: provide1") &&
      r.includes("requires: require1") &&
      r.includes("forbids:  forbid1") &&
      r.includes("Rules:") &&
      r.includes("  - rule1") &&
      r.includes("  - rule2"),
  },
  {
    name: "rule:7 — buildInspectorPrompt handles missing optional fields",
    setup: () => ({
      node: {
        id: "test-node",
        label: null,
        kind: null,
        prompt: null,
        rules: [],
        context: null,
        literal: null,
        translator: null,
      } as OntologyNode,
    }),
    invoke: (api, ctx) => api.buildInspectorPrompt(ctx.node),
    assert: (r) => 
      r.includes("Node label: (unlabeled)") &&
      r.includes("Node kind:  (unspecified)") &&
      r.includes("(empty prompt)") &&
      !r.includes("Contract:") &&
      !r.includes("Rules:"),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 4, 5, 6]).has(i));
