// GENERATED by `onto probe node_0109` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 14 self-validated case(s)
// (each matched the source src/runtime/effects/io.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "pureEffect then runEffect yields ok(value)",
    setup: () => ({ value: 42 }),
    invoke: (api, ctx) =>
      (api as any).runEffect((api as any).pureEffect(ctx.value)),
    assert: (r) => r.tag === "ok" && r.value === 42,
  },
  {
    name: "failEffect then runEffect yields err(error)",
    setup: () => ({ error: "boom" }),
    invoke: (api, ctx) =>
      (api as any).runEffect((api as any).failEffect(ctx.error)),
    assert: (r) => r.tag === "err" && r.error === "boom",
  },
  {
    name: "mapEffect transforms the success value",
    setup: () => ({ value: 5 }),
    invoke: (api, ctx) =>
      (api as any).runEffect(
        (api as any).mapEffect((api as any).pureEffect(ctx.value), (t: number) => t * 2),
      ),
    assert: (r) => r.tag === "ok" && r.value === 10,
  },
  {
    name: "mapEffect leaves errors untouched and skips f",
    setup: () => ({ error: "bad" }),
    invoke: (api, ctx) =>
      (api as any).runEffect(
        (api as any).mapEffect((api as any).failEffect(ctx.error), (t: number) => t * 2),
      ),
    assert: (r) => r.tag === "err" && r.error === "bad",
  },
  {
    name: "bindEffect chains successful effects",
    setup: () => ({ value: 3 }),
    invoke: (api, ctx) =>
      (api as any).runEffect(
        (api as any).bindEffect((api as any).pureEffect(ctx.value), (t: number) =>
          (api as any).pureEffect(t + 1),
        ),
      ),
    assert: (r) => r.tag === "ok" && r.value === 4,
  },
  {
    name: "bindEffect short-circuits on upstream failure (f not invoked)",
    setup: () => ({ error: "nope" }),
    invoke: (api, ctx) =>
      (api as any).runEffect(
        (api as any).bindEffect((api as any).failEffect(ctx.error), () =>
          (api as any).pureEffect("unreachable"),
        ),
      ),
    assert: (r) => r.tag === "err" && r.error === "nope",
  },
  {
    name: "pureWithLog yields ok(value) with no logs",
    setup: () => ({ value: 7 }),
    invoke: (api, ctx) =>
      (api as any).runWithLog((api as any).pureWithLog(ctx.value)),
    assert: (r) =>
      r.value.tag === "ok" &&
      r.value.value === 7 &&
      Array.isArray(r.logs) &&
      r.logs.length === 0,
  },
  {
    name: "failWithLog yields err(error) with no logs",
    setup: () => ({ error: "ouch" }),
    invoke: (api, ctx) =>
      (api as any).runWithLog((api as any).failWithLog(ctx.error)),
    assert: (r) =>
      r.value.tag === "err" &&
      r.value.error === "ouch" &&
      Array.isArray(r.logs) &&
      r.logs.length === 0,
  },
  {
    name: "logInfo emits a single info entry and resolves to ok(undefined)",
    setup: () => ({ message: "hello", data: { k: 1 } }),
    invoke: (api, ctx) =>
      (api as any).runWithLog((api as any).logInfo(ctx.message, ctx.data)),
    assert: (r) =>
      r.value.tag === "ok" &&
      r.value.value === undefined &&
      r.logs.length === 1 &&
      r.logs[0].level === "info" &&
      r.logs[0].message === "hello" &&
      r.logs[0].data.k === 1,
  },
  {
    name: "logWarn emits a single warn entry",
    setup: () => ({ message: "careful" }),
    invoke: (api, ctx) =>
      (api as any).runWithLog((api as any).logWarn(ctx.message)),
    assert: (r) =>
      r.logs.length === 1 &&
      r.logs[0].level === "warn" &&
      r.logs[0].message === "careful",
  },
  {
    name: "logError emits a single error entry",
    setup: () => ({ message: "fatal" }),
    invoke: (api, ctx) =>
      (api as any).runWithLog((api as any).logError(ctx.message)),
    assert: (r) =>
      r.logs.length === 1 &&
      r.logs[0].level === "error" &&
      r.logs[0].message === "fatal",
  },
  {
    name: "mapWithLog transforms success value and preserves logs",
    setup: () => ({ value: 4 }),
    invoke: (api, ctx) =>
      (api as any).runWithLog(
        (api as any).mapWithLog(
          (api as any).bindWithLog((api as any).logInfo("step"), () =>
            (api as any).pureWithLog(ctx.value),
          ),
          (t: number) => t + 100,
        ),
      ),
    assert: (r) =>
      r.value.tag === "ok" &&
      r.value.value === 104 &&
      r.logs.length === 1 &&
      r.logs[0].level === "info" &&
      r.logs[0].message === "step",
  },
  {
    name: "bindWithLog concatenates logs across both legs on success",
    setup: () => ({}),
    invoke: (api) =>
      (api as any).runWithLog(
        (api as any).bindWithLog((api as any).logInfo("a"), () =>
          (api as any).logWarn("b"),
        ),
      ),
    assert: (r) =>
      r.value.tag === "ok" &&
      r.logs.length === 2 &&
      r.logs[0].message === "a" &&
      r.logs[0].level === "info" &&
      r.logs[1].message === "b" &&
      r.logs[1].level === "warn",
  },
  {
    name: "bindWithLog short-circuits on failure but keeps first leg's logs",
    setup: () => ({ error: "stop" }),
    invoke: (api, ctx) =>
      (api as any).runWithLog(
        (api as any).bindWithLog(
          (api as any).bindWithLog((api as any).logInfo("kept"), () =>
            (api as any).failWithLog(ctx.error),
          ),
          () => (api as any).logWarn("unreachable"),
        ),
      ),
    assert: (r) =>
      r.value.tag === "err" &&
      r.value.error === "stop" &&
      r.logs.length === 1 &&
      r.logs[0].message === "kept",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]).has(i));
