// GENERATED by `onto probe node_0165` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/inverse/static/python.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — parsePythonFile extracts basic import",
    setup: () => ({
      filePath: "/project/main.py",
      source: "import os\nprint('hello')",
    }),
    invoke: (api, ctx) => (api as any).parsePythonFile(ctx.filePath, ctx.source),
    assert: (r) => r.imports.length === 1 && r.imports[0].modulePath === "os" && r.imports[0].isFromForm === false,
  },
  {
    name: "rule:2 — parseImportStatement handles multiple imports on one line",
    setup: () => ({
      body: "foo, bar.baz",
      filePath: "/project/main.py",
    }),
    invoke: (api, ctx) => (api as any).parseImportStatement(ctx.body, ctx.filePath),
    assert: (r) => r.length === 2 && r[0].modulePath === "foo" && r[1].modulePath === "bar.baz",
  },
  {
    name: "rule:3 — parseFromImportStatement handles named symbol import",
    setup: () => ({
      body: "foo import bar",
      filePath: "/project/main.py",
    }),
    invoke: (api, ctx) => (api as any).parseFromImportStatement(ctx.body, ctx.filePath),
    assert: (r) => r !== undefined && r.modulePath === "foo" && r.imports[0] === "bar" && r.isFromForm === true,
  },
  {
    name: "rule:4 — stripInlineComment removes inline comments",
    setup: () => ({
      s: "import foo  # this is a comment",
    }),
    invoke: (api, ctx) => (api as any).stripInlineComment(ctx.s),
    assert: (r) => r === "import foo",
  },
  {
    name: "rule:5 — resolvePythonModule resolves absolute module to file",
    setup: () => ({
      modulePath: "foo",
      relativeLevel: 0,
      importerFilePath: "/project/main.py",
      rootDir: "/project",
    }),
    invoke: (api, ctx) => {
      // Mock fs.statSync to simulate file existence
      const originalStatSync = (global as any).fs?.statSync;
      (global as any).fs = {
        statSync: (p: string) => ({
          isFile: () => p === "/project/foo.py"
        })
      };
      try {
        return (api as any).resolvePythonModule(ctx.modulePath, ctx.relativeLevel, ctx.importerFilePath, ctx.rootDir);
      } finally {
        if (originalStatSync) {
          (global as any).fs.statSync = originalStatSync;
        } else {
          delete (global as any).fs;
        }
      }
    },
    assert: (r) => r === "/project/foo.py",
  },
  {
    name: "rule:6 — existsAndIsFile returns true for existing file",
    setup: () => ({
      p: "/tmp/test.py"
    }),
    invoke: (api, ctx) => {
      // Mock fs.statSync to simulate file existence
      const originalStatSync = (global as any).fs?.statSync;
      (global as any).fs = {
        statSync: () => ({ isFile: () => true })
      };
      try {
        return (api as any).existsAndIsFile(ctx.p);
      } finally {
        if (originalStatSync) {
          (global as any).fs.statSync = originalStatSync;
        } else {
          delete (global as any).fs;
        }
      }
    },
    assert: (r) => r === true,
  },
  {
    name: "parsePythonFile handles from-import with wildcard",
    setup: () => ({
      filePath: "/project/main.py",
      source: "from foo import *\nprint('hello')",
    }),
    invoke: (api, ctx) => (api as any).parsePythonFile(ctx.filePath, ctx.source),
    assert: (r) => r.imports.length === 1 && r.imports[0].imports[0] === "*" && r.imports[0].isFromForm === true,
  },
  {
    name: "parseImportStatement handles aliased import",
    setup: () => ({
      body: "foo as bar",
      filePath: "/project/main.py",
    }),
    invoke: (api, ctx) => (api as any).parseImportStatement(ctx.body, ctx.filePath),
    assert: (r) => r.length === 1 && r[0].modulePath === "foo" && r[0].imports[0] === "bar",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
