// GENERATED by `onto probe node_0125` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/inverse/ingest/github.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — fetchPullRequest returns IntentSource with valid fields",
    setup: () => ({
      num: 123,
      repo: "owner/repo",
      rawJson: `{
        "number": 123,
        "title": "Test PR",
        "body": "This is a test pull request",
        "url": "https://github.com/owner/repo/pull/123",
        "state": "open",
        "author": {"login": "testuser"},
        "files": [{"path": "src/index.ts"}, {"path": "README.md"}]
      }`,
    }),
    invoke: (api, ctx) => {
      // Mock runGh to return our test JSON
      const originalRunGh = (api as any).runGh;
      (api as any).runGh = () => ctx.rawJson;
      try {
        return api.fetchPullRequest(ctx.num, ctx.repo);
      } finally {
        (api as any).runGh = originalRunGh;
      }
    },
    assert: (r) => 
      r.kind === "pr" &&
      r.number === 123 &&
      r.title === "Test PR" &&
      r.body === "This is a test pull request" &&
      r.url === "https://github.com/owner/repo/pull/123" &&
      r.state === "open" &&
      r.author === "testuser" &&
      Array.isArray(r.files) &&
      r.files.length === 2 &&
      r.files[0].path === "src/index.ts" &&
      r.files[1].path === "README.md",
  },
  {
    name: "rule:2 — fetchIssue returns IntentSource with valid fields",
    setup: () => ({
      num: 456,
      repo: "owner/repo",
      rawJson: `{
        "number": 456,
        "title": "Test Issue",
        "body": "This is a test issue",
        "url": "https://github.com/owner/repo/issues/456",
        "state": "open",
        "author": {"name": "Test User"}
      }`,
    }),
    invoke: (api, ctx) => {
      const originalRunGh = (api as any).runGh;
      (api as any).runGh = () => ctx.rawJson;
      try {
        return api.fetchIssue(ctx.num, ctx.repo);
      } finally {
        (api as any).runGh = originalRunGh;
      }
    },
    assert: (r) => 
      r.kind === "issue" &&
      r.number === 456 &&
      r.title === "Test Issue" &&
      r.body === "This is a test issue" &&
      r.url === "https://github.com/owner/repo/issues/456" &&
      r.state === "open" &&
      r.author === "Test User" &&
      r.files === undefined,
  },
  {
    name: "rule:3 — fetchPullRequest handles missing fields gracefully",
    setup: () => ({
      num: 789,
      repo: undefined,
      rawJson: `{"number": 789}`,
    }),
    invoke: (api, ctx) => {
      const originalRunGh = (api as any).runGh;
      (api as any).runGh = () => ctx.rawJson;
      try {
        return api.fetchPullRequest(ctx.num, ctx.repo);
      } finally {
        (api as any).runGh = originalRunGh;
      }
    },
    assert: (r) => 
      r.kind === "pr" &&
      r.number === 789 &&
      r.title === "PR #789" &&
      r.body === "" &&
      r.url === "" &&
      r.state === undefined &&
      r.author === undefined &&
      Array.isArray(r.files) &&
      r.files.length === 0,
  },
  {
    name: "rule:4 — fetchIssue handles missing fields gracefully",
    setup: () => ({
      num: 101,
      repo: undefined,
      rawJson: `{"number": 101}`,
    }),
    invoke: (api, ctx) => {
      const originalRunGh = (api as any).runGh;
      (api as any).runGh = () => ctx.rawJson;
      try {
        return api.fetchIssue(ctx.num, ctx.repo);
      } finally {
        (api as any).runGh = originalRunGh;
      }
    },
    assert: (r) => 
      r.kind === "issue" &&
      r.number === 101 &&
      r.title === "Issue #101" &&
      r.body === "" &&
      r.url === "" &&
      r.state === undefined &&
      r.author === undefined &&
      r.files === undefined,
  },
  {
    name: "rule:5 — runGh throws ENOENT error when gh CLI is missing",
    setup: () => ({
      args: ["pr", "view", "123"],
    }),
    invoke: (api, ctx) => {
      try {
        (api as any).runGh(ctx.args);
        return "no error thrown";
      } catch (e) {
        return (e as Error).message;
      }
    },
    assert: (r) => typeof r === "string" && r.includes("GitHub CLI `gh` was not found on PATH"),
  },
  {
    name: "rule:6 — parseGhJson throws on invalid JSON",
    setup: () => ({
      raw: "invalid json",
      what: "test object",
    }),
    invoke: (api, ctx) => {
      try {
        (api as any).parseGhJson(ctx.raw, ctx.what);
        return "no error thrown";
      } catch (e) {
        return (e as Error).message;
      }
    },
    assert: (r) => typeof r === "string" && r.includes("Could not parse `gh` JSON output for test object"),
  },
  {
    name: "rule:7 — repoArgs constructs args correctly",
    setup: () => ({
      repo: "owner/repo",
    }),
    invoke: (api, ctx) => (api as any).repoArgs(ctx.repo),
    assert: (r) => Array.isArray(r) && r.length === 2 && r[0] === "--repo" && r[1] === "owner/repo",
  },
  {
    name: "rule:8 — repoArgs returns empty array when repo is undefined",
    setup: () => ({
      repo: undefined,
    }),
    invoke: (api, ctx) => (api as any).repoArgs(ctx.repo),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 6, 7]).has(i));
