// GENERATED by `onto probe node_0122` (model: qwen2.5-coder:7b). Do not hand-edit;
// re-run probe to regenerate. 2 self-validated case(s)
// (each matched the source src/kernel/graph/poset.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — posetIndex returns correct index for 'canon'",
    setup: () => ("canon" as AbstractionLevel),
    invoke: (api, ctx) => api.posetIndex(ctx),
    assert: (r) => r === 0,
  },
  {
    name: "rule:2 — posetIndex returns correct index for 'artifact'",
    setup: () => ("artifact" as AbstractionLevel),
    invoke: (api, ctx) => api.posetIndex(ctx),
    assert: (r) => r === 10,
  },
  {
    name: "validateEdgeDirection allows upward edge",
    setup: () => ({
      sourceLevel: "project" as AbstractionLevel,
      targetLevel: "target" as AbstractionLevel,
      edgeType: "refines" as OntologyEdge["type"],
    }),
    invoke: (api, ctx) => api.validateEdgeDirection(ctx),
    assert: (r) => r.ok === true,
  },
  {
    name: "validateEdgeDirection rejects downward edge",
    setup: () => ({
      sourceLevel: "target" as AbstractionLevel,
      targetLevel: "project" as AbstractionLevel,
      edgeType: "refines" as OntologyEdge["type"],
    }),
    invoke: (api, ctx) => api.validateEdgeDirection(ctx),
    assert: (r) => r.ok === false && r.reason.includes("points against the abstraction poset"),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1]).has(i));
