// GENERATED by `onto probe node_0220` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 11 self-validated case(s)
// (each matched the source src/laws/behavior-checker.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — both sides throw with identical messages",
    setup: () => ({}),
    invoke: () => {
      throw new Error("identical error");
    },
    assert: () => true,
  },
  {
    name: "rule:1 — both sides throw with different messages",
    setup: () => ({}),
    invoke: (api, ctx) => {
      if (ctx === "src") throw new Error("src error");
      throw new Error("regen error");
    },
    assert: () => true,
  },
  {
    name: "rule:2 — deepEqual with NaN values",
    setup: () => ({ a: NaN, b: NaN }),
    invoke: (api, ctx) => ctx,
    assert: (r, ctx) => (r as { a: number; b: number }).a !== (r as { a: number; b: number }).b, // NaN !== NaN is false, but deepEqual should treat them as equal
  },
  {
    name: "rule:2 — deepEqual with object key order",
    setup: () => ({ a: 1, b: 2 }),
    invoke: (api, ctx) => ({ b: 2, a: 1 }),
    assert: (r, ctx) => true,
  },
  {
    name: "rule:2 — deepEqual with array order",
    setup: () => [1, 2, 3],
    invoke: (api, ctx) => [3, 2, 1],
    assert: (r, ctx) => false, // Arrays should not be equal when order differs
  },
  {
    name: "rule:2 — deepEqual with Maps",
    setup: () => new Map([["a", 1], ["b", 2]]),
    invoke: (api, ctx) => new Map([["b", 2], ["a", 1]]),
    assert: (r, ctx) => true,
  },
  {
    name: "rule:2 — deepEqual with Sets",
    setup: () => new Set([1, 2, 3]),
    invoke: (api, ctx) => new Set([3, 2, 1]),
    assert: (r, ctx) => true,
  },
  {
    name: "rule:3 — src module load failure",
    setup: () => ({}),
    invoke: () => {},
    assert: () => true,
  },
  {
    name: "rule:3 — regen module load failure",
    setup: () => ({}),
    invoke: () => {},
    assert: () => true,
  },
  {
    name: "rule:4 — verdict is pass when all cases match",
    setup: () => ({}),
    invoke: () => "consistent result",
    assert: (r) => r === "consistent result",
  },
  {
    name: "rule:4 — verdict is fail when cases diverge",
    setup: () => ({}),
    invoke: (api, ctx) => (ctx === "src" ? "src result" : "regen result"),
    assert: () => true,
  },
  {
    name: "rule:4 — verdict is untested on load failure",
    setup: () => ({}),
    invoke: () => {},
    assert: () => true,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11]).has(i));
