// GENERATED by `onto probe node_0017` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/core/nodes/node-id.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "zero pads to four zeros (code does NOT increment, despite prose)",
    setup: () => ({ n: 0 }),
    invoke: (api, ctx) => (api as any).createSequentialNodeId(ctx.n),
    assert: (r) => r === "node_0000",
  },
  {
    name: "one pads to 0001",
    setup: () => ({ n: 1 }),
    invoke: (api, ctx) => (api as any).createSequentialNodeId(ctx.n),
    assert: (r) => r === "node_0001",
  },
  {
    name: "two-digit value left-pads to four chars",
    setup: () => ({ n: 42 }),
    invoke: (api, ctx) => (api as any).createSequentialNodeId(ctx.n),
    assert: (r) => r === "node_0042",
  },
  {
    name: "boundary: four-digit value unchanged",
    setup: () => ({ n: 9999 }),
    invoke: (api, ctx) => (api as any).createSequentialNodeId(ctx.n),
    assert: (r) => r === "node_9999",
  },
  {
    name: "value longer than four chars is not truncated or padded",
    setup: () => ({ n: 12345 }),
    invoke: (api, ctx) => (api as any).createSequentialNodeId(ctx.n),
    assert: (r) => r === "node_12345",
  },
  {
    name: "negative number: padStart pads the string '-1' to '00-1'",
    setup: () => ({ n: -1 }),
    invoke: (api, ctx) => (api as any).createSequentialNodeId(ctx.n),
    assert: (r) => r === "node_00-1",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5]).has(i));
