// GENERATED by `onto probe node_0110` (model: qwen2.5-coder:7b). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/laws/effects/result.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — ok constructor",
    setup: () => ({ value: 42 }),
    invoke: (api, ctx) => api.ok(ctx.value),
    assert: (r) => r.tag === "ok" && r.value === 42,
  },
  {
    name: "rule:2 — err constructor",
    setup: () => ({ error: new Error("Oops") }),
    invoke: (api, ctx) => api.err(ctx.error),
    assert: (r) => r.tag === "err" && r.error instanceof Error && r.error.message === "Oops",
  },
  {
    name: "rule:3 — isOk type guard",
    setup: () => ({ result: api.ok(42) }),
    invoke: (api, ctx) => api.isOk(ctx.result),
    assert: (r) => r,
  },
  {
    name: "rule:4 — isErr type guard",
    setup: () => ({ result: api.err(new Error("Oops")) }),
    invoke: (api, ctx) => api.isErr(ctx.result),
    assert: (r) => r,
  },
  {
    name: "rule:5 — mapResult on ok",
    setup: () => ({ result: api.ok(42), f: (x: number) => x * 2 }),
    invoke: (api, ctx) => api.mapResult(ctx.result, ctx.f),
    assert: (r) => r.tag === "ok" && r.value === 84,
  },
  {
    name: "rule:6 — mapResult on err",
    setup: () => ({ result: api.err(new Error("Oops")), f: (x: number) => x * 2 }),
    invoke: (api, ctx) => api.mapResult(ctx.result, ctx.f),
    assert: (r) => r.tag === "err" && r.error instanceof Error && r.error.message === "Oops",
  },
  {
    name: "rule:7 — bindResult on ok",
    setup: () => ({ result: api.ok(42), f: (x: number) => api.ok(x * 2) }),
    invoke: (api, ctx) => api.bindResult(ctx.result, ctx.f),
    assert: (r) => r.tag === "ok" && r.value === 84,
  },
  {
    name: "rule:8 — bindResult on err",
    setup: () => ({ result: api.err(new Error("Oops")), f: (x: number) => api.ok(x * 2) }),
    invoke: (api, ctx) => api.bindResult(ctx.result, ctx.f),
    assert: (r) => r.tag === "err" && r.error instanceof Error && r.error.message === "Oops",
  },
  {
    name: "rule:9 — mapErrResult on ok",
    setup: () => ({ result: api.ok(42), f: (e: Error) => new Error(e.message + " mapped") }),
    invoke: (api, ctx) => api.mapErrResult(ctx.result, ctx.f),
    assert: (r) => r.tag === "ok" && r.value === 42,
  },
  {
    name: "rule:10 — mapErrResult on err",
    setup: () => ({ result: api.err(new Error("Oops")), f: (e: Error) => new Error(e.message + " mapped") }),
    invoke: (api, ctx) => api.mapErrResult(ctx.result, ctx.f),
    assert: (r) => r.tag === "err" && r.error instanceof Error && r.error.message === "Oops mapped",
  },
  {
    name: "rule:11 — traverseResult on empty array",
    setup: () => ({ items: [], f: (x: number) => api.ok(x * 2) }),
    invoke: (api, ctx) => api.traverseResult(ctx.items, ctx.f),
    assert: (r) => r.tag === "ok" && r.value.length === 0,
  },
  {
    name: "rule:12 — traverseResult on array of ok",
    setup: () => ({ items: [1, 2, 3], f: (x: number) => api.ok(x * 2) }),
    invoke: (api, ctx) => api.traverseResult(ctx.items, ctx.f),
    assert: (r) => r.tag === "ok" && JSON.stringify(r.value) === JSON.stringify([2, 4, 6]),
  },
  {
    name: "rule:13 — traverseResult on array with err",
    setup: () => ({ items: [1, 2, 3], f: (x: number) => x === 2 ? api.err(new Error("Two")) : api.ok(x * 2) }),
    invoke: (api, ctx) => api.traverseResult(ctx.items, ctx.f),
    assert: (r) => r.tag === "err" && r.error instanceof Error && r.error.message === "Two",
  },
  {
    name: "rule:14 — sequenceResult on empty array",
    setup: () => ({ items: [] }),
    invoke: (api, ctx) => api.sequenceResult(ctx.items),
    assert: (r) => r.tag === "ok" && r.value.length === 0,
  },
  {
    name: "rule:15 — sequenceResult on array of ok",
    setup: () => ({ items: [api.ok(1), api.ok(2), api.ok(3)] }),
    invoke: (api, ctx) => api.sequenceResult(ctx.items),
    assert: (r) => r.tag === "ok" && JSON.stringify(r.value) === JSON.stringify([1, 2, 3]),
  },
  {
    name: "rule:16 — sequenceResult on array with err",
    setup: () => ({ items: [api.ok(1), api.err(new Error("Two")), api.ok(3)] }),
    invoke: (api, ctx) => api.sequenceResult(ctx.items),
    assert: (r) => r.tag === "err" && r.error instanceof Error && r.error.message === "Two",
  },
  {
    name: "rule:17 — unwrapResult on ok",
    setup: () => ({ result: api.ok(42) }),
    invoke: (api, ctx) => api.unwrapResult(ctx.result),
    assert: (r) => r === 42,
  },
  {
    name: "rule:18 — unwrapResult on err",
    setup: () => ({ result: api.err(new Error("Oops")) }),
    invoke: (api, ctx) => () => api.unwrapResult(ctx.result), // Asserting against a deterministic throw
    assert: () => true,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 10, 11, 12, 13]).has(i));
