// GENERATED by `onto probe node_0146` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 16 self-validated case(s)
// (each matched the source src/runtime/llm/dispatcher.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "request.model override collapses to single-element list",
    setup: () => ({ request: { task: "code_sketch", model: "qwen2.5-coder:7b" }, options: undefined }),
    invoke: (api, ctx) => (api as any).buildDispatchCandidates(ctx.request, ctx.options),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === "qwen2.5-coder:7b",
  },
  {
    name: "request.model takes precedence over options.defaultModel",
    setup: () => ({ request: { task: "code_sketch", model: "from-request" }, options: { defaultModel: "from-options" } }),
    invoke: (api, ctx) => (api as any).buildDispatchCandidates(ctx.request, ctx.options),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === "from-request",
  },
  {
    name: "options.defaultModel used when request.model absent",
    setup: () => ({ request: { task: "code_sketch" }, options: { defaultModel: "default-x" } }),
    invoke: (api, ctx) => (api as any).buildDispatchCandidates(ctx.request, ctx.options),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === "default-x",
  },
  {
    name: "no override, mock provider collapses to [undefined]",
    setup: () => ({ request: { task: "code_sketch" }, options: { provider: "mock" } }),
    invoke: (api, ctx) => (api as any).buildDispatchCandidates(ctx.request, ctx.options),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === undefined,
  },
  {
    name: "no override, no options defaults to mock -> [undefined]",
    setup: () => ({ request: { task: "code_sketch" }, options: undefined }),
    invoke: (api, ctx) => (api as any).buildDispatchCandidates(ctx.request, ctx.options),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === undefined,
  },
  {
    name: "no override, literal provider collapses to [undefined]",
    setup: () => ({ request: { task: "code_sketch" }, options: { provider: "literal" } }),
    invoke: (api, ctx) => (api as any).buildDispatchCandidates(ctx.request, ctx.options),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === undefined,
  },
  {
    name: "isModelUnavailableError: ollama 404 model not found message",
    setup: () => ({ err: new Error("model 'qwen2.5-coder:14b' not found") }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === true,
  },
  {
    name: "isModelUnavailableError: anthropic model_not_found token",
    setup: () => ({ err: new Error("API error: model_not_found") }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === true,
  },
  {
    name: "isModelUnavailableError: 'not pulled' substring",
    setup: () => ({ err: "the requested model is not pulled" }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === true,
  },
  {
    name: "isModelUnavailableError: 'does not exist' requires 'model' token too",
    setup: () => ({ err: new Error("this model does not exist") }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === true,
  },
  {
    name: "isModelUnavailableError: 'does not exist' without 'model' is false",
    setup: () => ({ err: new Error("file does not exist") }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === false,
  },
  {
    name: "isModelUnavailableError: 404 plus model token is true",
    setup: () => ({ err: new Error("HTTP 404 for model id") }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === true,
  },
  {
    name: "isModelUnavailableError: bare 404 without model token is false",
    setup: () => ({ err: new Error("404 not found") }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === false,
  },
  {
    name: "isModelUnavailableError: unrelated error is false",
    setup: () => ({ err: new Error("connection refused") }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === false,
  },
  {
    name: "isModelUnavailableError: case-insensitive on uppercase message",
    setup: () => ({ err: new Error("MODEL NOT FOUND") }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === true,
  },
  {
    name: "isModelUnavailableError: non-Error coerced via String()",
    setup: () => ({ err: { toString: () => "model_not_found in body" } }),
    invoke: (api, ctx) => (api as any).isModelUnavailableError(ctx.err),
    assert: (r) => r === true,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]).has(i));
