// GENERATED by `onto probe node_0079` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 12 self-validated case(s)
// (each matched the source src/surfaces/commands/query/run-query.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { QueryCommandOptions, QueryShape } from "../src/surfaces/commands/query/run-query.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — assertOntologyProject is called",
    setup: () => ({ shape: "{}" }),
    invoke: async (api, ctx) => {
      // This case is about side effects, not return values.
      // The actual assertion is done by the test harness comparing the regenerated code.
      await (api as any).runQueryCommand(ctx);
      return true;
    },
    assert: () => true,
  },
  {
    name: "rule:2 — resolveShape with valid JSON shape",
    setup: () => ({ shape: '{"kind": ["rule"]}' }),
    invoke: (api, ctx) => (api as any).resolveShape(ctx),
    assert: (r: QueryShape) => r.kind !== undefined && r.kind[0] === "rule",
  },
  {
    name: "rule:2 — resolveShape with valid shapeFile",
    setup: () => ({ shapeFile: "/tmp/valid-shape.json" }),
    invoke: (api, ctx) => (api as any).resolveShape(ctx),
    assert: (r: QueryShape) => r.kind !== undefined && r.kind[0] === "rule",
  },
  {
    name: "rule:2 — resolveShape with per-field flags",
    setup: () => ({ kind: "rule,concept", status: "active" }),
    invoke: (api, ctx) => (api as any).resolveShape(ctx),
    assert: (r: QueryShape) => Array.isArray(r.kind) && r.kind.includes("rule") && r.status === "active",
  },
  {
    name: "rule:2 — resolveShape throws on invalid JSON",
    setup: () => ({ shape: '{"kind":' }),
    invoke: (api, ctx) => {
      try {
        (api as any).resolveShape(ctx);
        return "did not throw";
      } catch (e) {
        return "threw";
      }
    },
    assert: (r: string) => r === "threw",
  },
  {
    name: "rule:2 — resolveShape throws on mutually exclusive shape and shapeFile",
    setup: () => ({ shape: "{}", shapeFile: "any.json" }),
    invoke: (api, ctx) => {
      try {
        (api as any).resolveShape(ctx);
        return "did not throw";
      } catch (e) {
        return "threw";
      }
    },
    assert: (r: string) => r === "threw",
  },
  {
    name: "rule:3 — queryNodes is called with correct args",
    setup: () => ({ shape: "{}" }),
    invoke: async (api, ctx) => {
      // This is about internal behavior, not return values.
      await (api as any).runQueryCommand(ctx);
      return true;
    },
    assert: () => true,
  },
  {
    name: "rule:4 — loadEmbeddingIndex is called when semantic option is present",
    setup: () => ({ shape: "{}", semantic: "test query" }),
    invoke: async (api, ctx) => {
      // This is about internal behavior, not return values.
      await (api as any).runQueryCommand(ctx);
      return true;
    },
    assert: () => true,
  },
  {
    name: "rule:5 — renderTable is called for pretty output",
    setup: () => ({ shape: "{}" }),
    invoke: async (api, ctx) => {
      // This is about internal behavior, not return values.
      await (api as any).runQueryCommand(ctx);
      return true;
    },
    assert: () => true,
  },
  {
    name: "rule:6 — printPretty outputs JSON when json flag is true",
    setup: () => ({ shape: "{}", json: true }),
    invoke: async (api, ctx) => {
      // This is about console output, not return values.
      await (api as any).runQueryCommand(ctx);
      return true;
    },
    assert: () => true,
  },
  {
    name: "rule:7 — describeShape renders compact shape description",
    setup: () => ({ kind: "rule", status: "active" }),
    invoke: (api, ctx) => {
      const shape = (api as any).resolveShape(ctx);
      return (api as any).describeShape(shape);
    },
    assert: (r: string) => r === "kind=rule status=active",
  },
  {
    name: "rule:8 — runQueryCommand handles semantic search path",
    setup: () => ({ shape: "{}", semantic: "test", top: "5" }),
    invoke: async (api, ctx) => {
      // This is about internal behavior, not return values.
      await (api as any).runQueryCommand(ctx);
      return true;
    },
    assert: () => true,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]).has(i));
