// GENERATED by `onto probe node_0088` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/surfaces/commands/verify/homeomorphism.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — computeDistanceMetrics returns correct shape for valid inputs",
    setup: () => ({
      original: "function foo() {}\nconsole.log('hello');",
      regen: "function foo() {}\nconsole.log('world');",
      language: "typescript" as const,
    }),
    invoke: (api, ctx) => api.computeDistanceMetrics(ctx.original, ctx.regen, ctx.language),
    assert: (r) => 
      typeof r === "object" && 
      r !== null && 
      typeof r.locDistance === "number" && 
      typeof r.structuralJaccard === "number" && 
      typeof r.originalLineCount === "number" && 
      typeof r.regenLineCount === "number" && 
      Array.isArray(r.originalDeclarations) && 
      Array.isArray(r.regenDeclarations),
  },
  {
    name: "rule:2 — classifyVerdict returns epsilon_equivalent when both metrics are within thresholds",
    setup: () => ({
      metrics: { 
        locDistance: 0.01, 
        structuralJaccard: 0.99,
        originalLineCount: 10,
        regenLineCount: 10,
        originalDeclarations: ["foo"],
        regenDeclarations: ["foo"]
      },
      thresholds: { loc: 0.05, jaccard: 0.95 }
    }),
    invoke: (api, ctx) => api.classifyVerdict(ctx.metrics, ctx.thresholds),
    assert: (r) => r === "epsilon_equivalent",
  },
  {
    name: "rule:3 — classifyVerdict returns divergent_loc when only loc exceeds threshold",
    setup: () => ({
      metrics: { 
        locDistance: 0.1, 
        structuralJaccard: 0.99,
        originalLineCount: 10,
        regenLineCount: 12,
        originalDeclarations: ["foo"],
        regenDeclarations: ["foo"]
      },
      thresholds: { loc: 0.05, jaccard: 0.95 }
    }),
    invoke: (api, ctx) => api.classifyVerdict(ctx.metrics, ctx.thresholds),
    assert: (r) => r === "divergent_loc",
  },
  {
    name: "rule:4 — classifyVerdict returns divergent_structural when only jaccard falls below threshold",
    setup: () => ({
      metrics: { 
        locDistance: 0.01, 
        structuralJaccard: 0.9,
        originalLineCount: 10,
        regenLineCount: 10,
        originalDeclarations: ["foo"],
        regenDeclarations: ["bar"]
      },
      thresholds: { loc: 0.05, jaccard: 0.95 }
    }),
    invoke: (api, ctx) => api.classifyVerdict(ctx.metrics, ctx.thresholds),
    assert: (r) => r === "divergent_structural",
  },
  {
    name: "rule:5 — classifyVerdict returns divergent_both when both metrics exceed thresholds",
    setup: () => ({
      metrics: { 
        locDistance: 0.1, 
        structuralJaccard: 0.9,
        originalLineCount: 10,
        regenLineCount: 15,
        originalDeclarations: ["foo"],
        regenDeclarations: ["bar"]
      },
      thresholds: { loc: 0.05, jaccard: 0.95 }
    }),
    invoke: (api, ctx) => api.classifyVerdict(ctx.metrics, ctx.thresholds),
    assert: (r) => r === "divergent_both",
  },
  {
    name: "rule:6 — inferLanguageHint returns javascript for .js files",
    setup: () => ({ filePath: "/path/to/file.js" }),
    invoke: (api, ctx) => api.inferLanguageHint(ctx.filePath),
    assert: (r) => r === "javascript",
  },
  {
    name: "rule:7 — inferLanguageHint returns typescript for .ts files",
    setup: () => ({ filePath: "/path/to/file.ts" }),
    invoke: (api, ctx) => api.inferLanguageHint(ctx.filePath),
    assert: (r) => r === "typescript",
  },
  {
    name: "rule:8 — inferLanguageHint returns python for .py files",
    setup: () => ({ filePath: "/path/to/file.py" }),
    invoke: (api, ctx) => api.inferLanguageHint(ctx.filePath),
    assert: (r) => r === "python",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 6, 7]).has(i));
