// GENERATED by `onto probe node_0161` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/laws/query/representable.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { OntologyNode, OntologyEdge } from "../../kernel/schemas/ontology.js";
import type { QueryShape } from "./types.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — matchesShape returns false when kind does not match",
    setup: () => ({
      node: { id: "n1", kind: "Type", coordinates: {}, status: "active", context: { provides: [], requires: [], forbids: [] } } as OntologyNode,
      shape: { kind: ["Interface"] } as QueryShape,
      edges: [] as readonly OntologyEdge[],
    }),
    invoke: (api, ctx) => api.matchesShape(ctx.node, ctx.shape, ctx.edges),
    assert: (r) => r === false,
  },
  {
    name: "rule:2 — matchesShape returns true when all shape constraints are satisfied",
    setup: () => ({
      node: {
        id: "n1",
        kind: "Type",
        coordinates: { abstraction: "domain", plane: "core", manifestation: "concrete", branch: "main" },
        status: "active",
        context: {
          provides: [{ key: "conceptA" }],
          requires: [{ source: "conceptB" }],
          forbids: [{ source: "conceptC" }],
        },
      } as OntologyNode,
      shape: {
        kind: ["Type"],
        abstraction: ["domain"],
        plane: ["core"],
        manifestation: ["concrete"],
        branch: "main",
        provides: ["conceptA"],
        requires: ["conceptB"],
        forbids: ["conceptC"],
        hasIncoming: ["refines"],
        hasOutgoing: ["depends_on"],
      } as QueryShape,
      edges: [
        { from: "n2", to: "n1", type: "refines" },
        { from: "n1", to: "n3", type: "depends_on" },
      ] as readonly OntologyEdge[],
    }),
    invoke: (api, ctx) => api.matchesShape(ctx.node, ctx.shape, ctx.edges),
    assert: (r) => r === true,
  },
  {
    name: "rule:3 — matchesShape returns false when branch does not match",
    setup: () => ({
      node: { id: "n1", kind: "Type", coordinates: { branch: "dev" }, status: "active", context: { provides: [], requires: [], forbids: [] } } as OntologyNode,
      shape: { branch: "main" } as QueryShape,
      edges: [] as readonly OntologyEdge[],
    }),
    invoke: (api, ctx) => api.matchesShape(ctx.node, ctx.shape, ctx.edges),
    assert: (r) => r === false,
  },
  {
    name: "rule:4 — matchesShape returns false when required concept is missing from provides",
    setup: () => ({
      node: { id: "n1", kind: "Type", coordinates: {}, status: "active", context: { provides: [], requires: [], forbids: [] } } as OntologyNode,
      shape: { provides: ["missingConcept"] } as QueryShape,
      edges: [] as readonly OntologyEdge[],
    }),
    invoke: (api, ctx) => api.matchesShape(ctx.node, ctx.shape, ctx.edges),
    assert: (r) => r === false,
  },
  {
    name: "rule:5 — matchesShape returns false when required edge type is missing in incoming",
    setup: () => ({
      node: { id: "n1", kind: "Type", coordinates: {}, status: "active", context: { provides: [], requires: [], forbids: [] } } as OntologyNode,
      shape: { hasIncoming: ["refines"] } as QueryShape,
      edges: [] as readonly OntologyEdge[],
    }),
    invoke: (api, ctx) => api.matchesShape(ctx.node, ctx.shape, ctx.edges),
    assert: (r) => r === false,
  },
  {
    name: "rule:6 — queryNodes returns matching nodes sorted by id",
    setup: () => ({
      nodes: [
        { id: "n2", kind: "Type", coordinates: {}, status: "active", context: { provides: [], requires: [], forbids: [] } } as OntologyNode,
        { id: "n1", kind: "Type", coordinates: {}, status: "active", context: { provides: [], requires: [], forbids: [] } } as OntologyNode,
      ],
      shape: { kind: ["Type"] } as QueryShape,
      edges: [] as readonly OntologyEdge[],
    }),
    invoke: (api, ctx) => api.queryNodes(ctx.nodes, ctx.shape, ctx.edges),
    assert: (r) => r.length === 2 && r[0].id === "n1" && r[1].id === "n2",
  },
  {
    name: "rule:7 — queryNodes returns empty array when no nodes match",
    setup: () => ({
      nodes: [
        { id: "n1", kind: "Type", coordinates: {}, status: "active", context: { provides: [], requires: [], forbids: [] } } as OntologyNode,
      ],
      shape: { kind: ["Interface"] } as QueryShape,
      edges: [] as readonly OntologyEdge[],
    }),
    invoke: (api, ctx) => api.queryNodes(ctx.nodes, ctx.shape, ctx.edges),
    assert: (r) => r.length === 0,
  },
  {
    name: "rule:8 — matchesShape returns true when shape is empty (no constraints)",
    setup: () => ({
      node: { id: "n1", kind: "Type", coordinates: {}, status: "active", context: { provides: [], requires: [], forbids: [] } } as OntologyNode,
      shape: {} as QueryShape,
      edges: [] as readonly OntologyEdge[],
    }),
    invoke: (api, ctx) => api.matchesShape(ctx.node, ctx.shape, ctx.edges),
    assert: (r) => r === true,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
