// GENERATED by `onto probe node_0137` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 5 self-validated case(s)
// (each matched the source src/laws/progress-report.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — newRunId returns a string starting with 'run_' followed by 8 hex characters",
    setup: () => ({}),
    invoke: (api) => api.newRunId(),
    assert: (r) => typeof r === "string" && /^run_[0-9a-f]{8}$/.test(r),
  },
  {
    name: "rule:2 — writeProgressReport creates parent directory and writes file",
    setup: () => ({
      cwd: "/tmp/test-project",
      kind: "INGEST" as const,
      runId: "run_12345678",
      body: "# Test Report\n\nThis is a test report body.",
    }),
    invoke: (api, ctx) => api.writeProgressReport(ctx.cwd, ctx.kind, ctx.runId, ctx.body),
    assert: (r) => r === "/tmp/test-project/.ontology/reports/INGEST_run_12345678.md",
  },
  {
    name: "rule:3 — relativiseOrAbsolute returns relative path when file is under root",
    setup: () => ({
      filePath: "/Users/test/project/src/index.ts",
      rootDir: "/Users/test/project",
    }),
    invoke: (api, ctx) => (api as any).relativiseOrAbsolute(ctx.filePath, ctx.rootDir),
    assert: (r) => r === "src/index.ts",
  },
  {
    name: "rule:4 — relativiseOrAbsolute returns absolute path when file is not under root",
    setup: () => ({
      filePath: "/other/path/file.ts",
      rootDir: "/Users/test/project",
    }),
    invoke: (api, ctx) => (api as any).relativiseOrAbsolute(ctx.filePath, ctx.rootDir),
    assert: (r) => r === "/other/path/file.ts",
  },
  {
    name: "rule:5 — renderIngestReport generates markdown with expected sections",
    setup: () => ({
      data: {
        runId: "run_12345678",
        timestamp: "2023-01-01T00:00:00Z",
        rootDir: "/test/project",
        branch: "main",
        provider: "openai",
        model: "gpt-4",
        dryRun: false,
        files: [],
        proposalsCreated: 0,
        totalTokens: 0,
        totalUsd: 0,
      } as any,
    }),
    invoke: (api, ctx) => api.renderIngestReport(ctx.data),
    assert: (r) => r.startsWith(`# ingest report — run_12345678`),
  },
  {
    name: "rule:6 — renderCompileReport generates markdown with expected sections",
    setup: () => ({
      data: {
        runId: "run_87654321",
        timestamp: "2023-01-01T00:00:00Z",
        rootDir: "/test/project",
        focalId: "node_123",
        branch: "main",
        provider: "openai",
        steps: [],
        totalTokens: 0,
        totalUsd: 0,
      } as any,
    }),
    invoke: (api, ctx) => api.renderCompileReport(ctx.data),
    assert: (r) => r.startsWith(`# compile report — run_87654321`),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([1, 2, 3, 4, 5]).has(i));
