// GENERATED by `onto probe node_0102` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/forward/context/gluing.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type {
  ContextFragment,
  GluingConflict,
  GluingConflictType,
  GluingOptions,
  GluingResult,
} from "./gluing.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — glueFragments returns empty merged fragment with warning when input is empty",
    setup: () => ({ fragments: [] as ContextFragment[] }),
    invoke: (api, ctx) => api.glueFragments(ctx.fragments),
    assert: (r: GluingResult) =>
      r.ok === true &&
      r.merged.nodeId === "merged" &&
      r.merged.branch === "main" &&
      r.merged.provides.length === 0 &&
      r.merged.requires.length === 0 &&
      r.merged.forbids.length === 0 &&
      r.merged.optional.length === 0 &&
      r.merged.rules.length === 0 &&
      r.conflicts.length === 0 &&
      r.warnings.includes("No context fragments provided."),
  },
  {
    name: "rule:2 — glueFragments detects branch mismatch conflict",
    setup: () => ({
      fragments: [
        {
          nodeId: "a",
          branch: "main",
          provides: ["x"],
          requires: [],
          forbids: [],
          optional: [],
          rules: [],
        },
        {
          nodeId: "b",
          branch: "dev",
          provides: ["y"],
          requires: [],
          forbids: [],
          optional: [],
          rules: [],
        },
      ] as ContextFragment[],
    }),
    invoke: (api, ctx) => api.glueFragments(ctx.fragments),
    assert: (r: GluingResult) =>
      r.ok === false &&
      r.conflicts.some(
        (c: GluingConflict) =>
          c.type === "branch_mismatch" &&
          c.message === "Fragments belong to different branches." &&
          c.nodeIds.includes("a") &&
          c.nodeIds.includes("b"),
      ),
  },
  {
    name: "rule:3 — glueFragments detects duplicate provider conflict by default",
    setup: () => ({
      fragments: [
        {
          nodeId: "a",
          branch: "main",
          provides: ["x"],
          requires: [],
          forbids: [],
          optional: [],
          rules: [],
        },
        {
          nodeId: "b",
          branch: "main",
          provides: ["x"],
          requires: [],
          forbids: [],
          optional: [],
          rules: [],
        },
      ] as ContextFragment[],
    }),
    invoke: (api, ctx) => api.glueFragments(ctx.fragments),
    assert: (r: GluingResult) =>
      r.ok === false &&
      r.conflicts.some(
        (c: GluingConflict) =>
          c.type === "duplicate_provider" &&
          c.message === "Duplicate provider for key: x" &&
          c.nodeIds.includes("a") &&
          c.nodeIds.includes("b"),
      ),
  },
  {
    name: "rule:4 — glueFragments identifies equal providers under identify-if-equal option",
    setup: () => ({
      fragments: [
        {
          nodeId: "a",
          branch: "main",
          provides: ["x"],
          provideSignatures: { x: "sig1" },
          requires: [],
          forbids: [],
          optional: [],
          rules: [],
        },
        {
          nodeId: "b",
          branch: "main",
          provides: ["x"],
          provideSignatures: { x: "sig1" },
          requires: [],
          forbids: [],
          optional: [],
          rules: [],
        },
      ] as ContextFragment[],
      options: { onDuplicateProvider: "identify-if-equal" } as GluingOptions,
    }),
    invoke: (api, ctx) => api.glueFragments(ctx.fragments, ctx.options),
    assert: (r: GluingResult) =>
      r.ok === true &&
      r.warnings.some((w) =>
        w.includes("Identified 2 providers of key \"x\" by equal signature."),
      ) &&
      r.merged.provides.includes("x") &&
      r.merged.provideSignatures?.x === "sig1",
  },
  {
    name: "rule:5 — glueFragments detects missing requirement",
    setup: () => ({
      fragments: [
        {
          nodeId: "a",
          branch: "main",
          provides: [],
          requires: ["x"],
          forbids: [],
          optional: [],
          rules: [],
        },
      ] as ContextFragment[],
    }),
    invoke: (api, ctx) => api.glueFragments(ctx.fragments),
    assert: (r: GluingResult) =>
      r.ok === false &&
      r.conflicts.some(
        (c: GluingConflict) =>
          c.type === "missing_requirement" &&
          c.message === "Missing requirement: x" &&
          c.nodeIds.includes("a"),
      ),
  },
  {
    name: "rule:6 — glueFragments detects forbidden match",
    setup: () => ({
      fragments: [
        {
          nodeId: "a",
          branch: "main",
          provides: ["x"],
          requires: [],
          forbids: [],
          optional: [],
          rules: [],
        },
        {
          nodeId: "b",
          branch: "main",
          provides: [],
          requires: [],
          forbids: ["x"],
          optional: [],
          rules: [],
        },
      ] as ContextFragment[],
    }),
    invoke: (api, ctx) => api.glueFragments(ctx.fragments),
    assert: (r: GluingResult) =>
      r.ok === false &&
      r.conflicts.some(
        (c: GluingConflict) =>
          c.type === "forbidden_match" &&
          c.message === "Forbidden match found for key: x" &&
          c.nodeIds.includes("a") &&
          c.nodeIds.includes("b"),
      ),
  },
  {
    name: "rule:7 — restrictSection returns correct subset based on piece domain",
    setup: () => ({
      section: {
        nodeId: "merged",
        branch: "main",
        provides: ["x", "y", "z"],
        requires: ["a", "b"],
        forbids: ["c"],
        optional: ["d"],
        rules: ["r1", "r2"],
        provideSignatures: { x: "sigX", y: "sigY" },
      } as ContextFragment,
      piece: {
        nodeId: "piece1",
        branch: "main",
        provides: ["x", "z"],
        requires: ["a"],
        forbids: [],
        optional: ["d"],
        rules: ["r1"],
      } as ContextFragment,
    }),
    invoke: (api, ctx) => api.restrictSection(ctx.section, ctx.piece),
    assert: (r: ContextFragment) =>
      r.nodeId === "piece1" &&
      r.branch === "main" &&
      r.provides.includes("x") &&
      r.provides.includes("z") &&
      r.provides.length === 2 &&
      r.requires.includes("a") &&
      r.requires.length === 1 &&
      r.forbids.length === 0 &&
      r.optional.includes("d") &&
      r.optional.length === 1 &&
      r.rules.includes("r1") &&
      r.rules.length === 1 &&
      r.provideSignatures?.x === "sigX" &&
      r.provideSignatures?.z === undefined,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6]).has(i));
