// GENERATED by `onto probe node_0143` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 12 self-validated case(s)
// (each matched the source src/laws/verify-homeomorphism.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — extractTopLevelDeclarations returns unique sorted names for TypeScript",
    setup: () => ({
      source: `export function foo() {}\nexport class Bar {}\nexport { foo as baz };`,
      language: "typescript" as const,
      filePath: "test.ts",
    }),
    invoke: (api, ctx) => api.extractTopLevelDeclarations(ctx.source, ctx.language, ctx.filePath),
    assert: (r) => Array.isArray(r) && r.length === 3 && r[0] === "Bar" && r[1] === "baz" && r[2] === "foo",
  },
  {
    name: "rule:2 — extractTopLevelDeclarations filters out 'default' export",
    setup: () => ({
      source: `export default function() {}\nexport function foo() {}`,
      language: "typescript" as const,
      filePath: "test.ts",
    }),
    invoke: (api, ctx) => api.extractTopLevelDeclarations(ctx.source, ctx.language, ctx.filePath),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === "foo",
  },
  {
    name: "rule:3 — extractTopLevelDeclarations returns sorted names for Python",
    setup: () => ({
      source: `def foo(): pass\nclass Bar: pass\nasync def baz(): pass`,
      language: "python" as const,
    }),
    invoke: (api, ctx) => api.extractTopLevelDeclarations(ctx.source, ctx.language),
    assert: (r) => Array.isArray(r) && r.length === 3 && r[0] === "Bar" && r[1] === "baz" && r[2] === "foo",
  },
  {
    name: "rule:4 — extractTopLevelDeclarations deduplicates Python declarations",
    setup: () => ({
      source: `def foo(): pass\ndef foo(): pass`,
      language: "python" as const,
    }),
    invoke: (api, ctx) => api.extractTopLevelDeclarations(ctx.source, ctx.language),
    assert: (r) => Array.isArray(r) && r.length === 1 && r[0] === "foo",
  },
  {
    name: "rule:5 — extractTopLevelDeclarations returns empty array for unknown language",
    setup: () => ({
      source: `function foo() {}`,
      language: "unknown" as const,
    }),
    invoke: (api, ctx) => api.extractTopLevelDeclarations(ctx.source, ctx.language),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
  {
    name: "rule:6 — computeDistanceMetrics calculates locDistance correctly",
    setup: () => ({
      original: "line1\nline2\nline3",
      regen: "line1\nline2",
      language: "unknown" as const,
    }),
    invoke: (api, ctx) => api.computeDistanceMetrics(ctx.original, ctx.regen, ctx.language),
    assert: (r) => r.locDistance === 1/3,
  },
  {
    name: "rule:7 — computeDistanceMetrics calculates structuralJaccard correctly",
    setup: () => ({
      original: "def foo(): pass\ndef bar(): pass",
      regen: "def foo(): pass\ndef baz(): pass",
      language: "python" as const,
    }),
    invoke: (api, ctx) => api.computeDistanceMetrics(ctx.original, ctx.regen, ctx.language),
    assert: (r) => r.structuralJaccard === 1/3,
  },
  {
    name: "rule:8 — computeDistanceMetrics handles empty declarations",
    setup: () => ({
      original: "",
      regen: "",
      language: "unknown" as const,
    }),
    invoke: (api, ctx) => api.computeDistanceMetrics(ctx.original, ctx.regen, ctx.language),
    assert: (r) => r.structuralJaccard === 1,
  },
  {
    name: "rule:9 — classifyVerdict returns epsilon_equivalent when both metrics pass",
    setup: () => ({
      metrics: { locDistance: 0.1, structuralJaccard: 0.8 } as any,
      thresholds: { loc: 0.3, jaccard: 0.5 },
    }),
    invoke: (api, ctx) => api.classifyVerdict(ctx.metrics, ctx.thresholds),
    assert: (r) => r === "epsilon_equivalent",
  },
  {
    name: "rule:10 — classifyVerdict returns divergent_loc when only loc fails",
    setup: () => ({
      metrics: { locDistance: 0.5, structuralJaccard: 0.8 } as any,
      thresholds: { loc: 0.3, jaccard: 0.5 },
    }),
    invoke: (api, ctx) => api.classifyVerdict(ctx.metrics, ctx.thresholds),
    assert: (r) => r === "divergent_loc",
  },
  {
    name: "rule:11 — classifyVerdict returns divergent_structural when only jaccard fails",
    setup: () => ({
      metrics: { locDistance: 0.1, structuralJaccard: 0.3 } as any,
      thresholds: { loc: 0.3, jaccard: 0.5 },
    }),
    invoke: (api, ctx) => api.classifyVerdict(ctx.metrics, ctx.thresholds),
    assert: (r) => r === "divergent_structural",
  },
  {
    name: "rule:12 — classifyVerdict returns divergent_both when both metrics fail",
    setup: () => ({
      metrics: { locDistance: 0.5, structuralJaccard: 0.3 } as any,
      thresholds: { loc: 0.3, jaccard: 0.5 },
    }),
    invoke: (api, ctx) => api.classifyVerdict(ctx.metrics, ctx.thresholds),
    assert: (r) => r === "divergent_both",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]).has(i));
