// GENERATED by `onto probe node_0176` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/runtime/workflow/graph-load.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "edgePredicateKey: typical from/to/index joined with double underscores",
    setup: () => ({ from: "nodeA", to: "nodeB", index: 0 }),
    invoke: (api, ctx) => (api as any).edgePredicateKey(ctx.from, ctx.to, ctx.index),
    assert: (r) => r === "nodeA__nodeB__0",
  },
  {
    name: "edgePredicateKey: non-zero index is stringified verbatim",
    setup: () => ({ from: "verifier-1", to: "term", index: 3 }),
    invoke: (api, ctx) => (api as any).edgePredicateKey(ctx.from, ctx.to, ctx.index),
    assert: (r) => r === "verifier-1__term__3",
  },
  {
    name: "edgePredicateKey: empty string endpoints",
    setup: () => ({ from: "", to: "", index: 0 }),
    invoke: (api, ctx) => (api as any).edgePredicateKey(ctx.from, ctx.to, ctx.index),
    assert: (r) => r === "____0",
  },
  {
    name: "edgePredicateKey: ids containing underscores remain distinguishable by structure",
    setup: () => ({ from: "a_b", to: "c_d", index: 12 }),
    invoke: (api, ctx) => (api as any).edgePredicateKey(ctx.from, ctx.to, ctx.index),
    assert: (r) => r === "a_b__c_d__12",
  },
  {
    name: "edgePredicateKey: negative index is stringified as-is",
    setup: () => ({ from: "x", to: "y", index: -1 }),
    invoke: (api, ctx) => (api as any).edgePredicateKey(ctx.from, ctx.to, ctx.index),
    assert: (r) => r === "x__y__-1",
  },
  {
    name: "edgePredicateKey: result is a string",
    setup: () => ({ from: "p", to: "q", index: 7 }),
    invoke: (api, ctx) => (api as any).edgePredicateKey(ctx.from, ctx.to, ctx.index),
    assert: (r) => typeof r === "string",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5]).has(i));
