// GENERATED by `onto probe node_0124` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/kernel/graph/traversal.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { OntologyEdge, EdgeDirection, NeighborEntry, SubgraphSlice } from "./traversal.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — getNeighbors returns empty array when no edges match",
    setup: () => ({
      focalId: "A",
      edges: [{ from: "B", to: "C", type: "related" }] as OntologyEdge[],
      options: { direction: "out" as EdgeDirection }
    }),
    invoke: (api, ctx) => api.getNeighbors(ctx.focalId, ctx.edges, ctx.options),
    assert: (r: NeighborEntry[]) => r.length === 0
  },
  {
    name: "rule:2 — getNeighbors filters by edge type when provided",
    setup: () => ({
      focalId: "A",
      edges: [
        { from: "A", to: "B", type: "related" },
        { from: "A", to: "C", type: "depends" }
      ] as OntologyEdge[],
      options: { edgeTypes: ["related"] }
    }),
    invoke: (api, ctx) => api.getNeighbors(ctx.focalId, ctx.edges, ctx.options),
    assert: (r: NeighborEntry[]) => r.length === 1 && r[0].edge.type === "related"
  },
  {
    name: "rule:3 — getNeighbors includes both directions by default",
    setup: () => ({
      focalId: "A",
      edges: [
        { from: "A", to: "B", type: "related" },
        { from: "C", to: "A", type: "depends" }
      ] as OntologyEdge[]
    }),
    invoke: (api, ctx) => api.getNeighbors(ctx.focalId, ctx.edges),
    assert: (r: NeighborEntry[]) => r.length === 2 && 
      r.some(e => e.direction === "out") && 
      r.some(e => e.direction === "in")
  },
  {
    name: "rule:4 — findShortestPath returns empty array for same start/end",
    setup: () => ({
      fromId: "A",
      toId: "A",
      edges: [{ from: "A", to: "B", type: "related" }] as OntologyEdge[]
    }),
    invoke: (api, ctx) => api.findShortestPath(ctx.fromId, ctx.toId, ctx.edges),
    assert: (r: OntologyEdge[] | null) => Array.isArray(r) && r.length === 0
  },
  {
    name: "rule:5 — findShortestPath returns null when no path exists",
    setup: () => ({
      fromId: "A",
      toId: "C",
      edges: [{ from: "A", to: "B", type: "related" }] as OntologyEdge[]
    }),
    invoke: (api, ctx) => api.findShortestPath(ctx.fromId, ctx.toId, ctx.edges),
    assert: (r: OntologyEdge[] | null) => r === null
  },
  {
    name: "rule:6 — findShortestPath finds direct path",
    setup: () => ({
      fromId: "A",
      toId: "B",
      edges: [{ from: "A", to: "B", type: "related" }] as OntologyEdge[]
    }),
    invoke: (api, ctx) => api.findShortestPath(ctx.fromId, ctx.toId, ctx.edges),
    assert: (r: OntologyEdge[] | null) => 
      r !== null && r.length === 1 && r[0].from === "A" && r[0].to === "B"
  },
  {
    name: "rule:7 — extractSubgraph includes focal node even with zero depth",
    setup: () => ({
      focalId: "A",
      edges: [{ from: "A", to: "B", type: "related" }] as OntologyEdge[],
      options: { depth: 0 }
    }),
    invoke: (api, ctx) => api.extractSubgraph(ctx.focalId, ctx.edges, ctx.options),
    assert: (r: SubgraphSlice) => 
      r.nodeIds.length === 1 && r.nodeIds[0] === "A" && r.edges.length === 0
  },
  {
    name: "rule:8 — extractSubgraph respects edge type filter",
    setup: () => ({
      focalId: "A",
      edges: [
        { from: "A", to: "B", type: "related" },
        { from: "A", to: "C", type: "depends" }
      ] as OntologyEdge[],
      options: { edgeTypes: ["related"] }
    }),
    invoke: (api, ctx) => api.extractSubgraph(ctx.focalId, ctx.edges, ctx.options),
    assert: (r: SubgraphSlice) => 
      r.nodeIds.includes("A") && 
      r.nodeIds.includes("B") && 
      !r.nodeIds.includes("C") &&
      r.edges.length === 1 && r.edges[0].type === "related"
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
