// GENERATED by `onto probe node_0138` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 16 self-validated case(s)
// (each matched the source src/laws/render-ascii.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — clamp01 returns 0 for NaN",
    setup: () => NaN,
    invoke: (api, ctx) => (api as any).clamp01(ctx),
    assert: (r) => r === 0,
  },
  {
    name: "rule:1 — clamp01 clamps negative numbers to 0",
    setup: () => -0.5,
    invoke: (api, ctx) => (api as any).clamp01(ctx),
    assert: (r) => r === 0,
  },
  {
    name: "rule:1 — clamp01 clamps values over 1 to 1",
    setup: () => 1.5,
    invoke: (api, ctx) => (api as any).clamp01(ctx),
    assert: (r) => r === 1,
  },
  {
    name: "rule:1 — clamp01 passes through valid values",
    setup: () => 0.5,
    invoke: (api, ctx) => (api as any).clamp01(ctx),
    assert: (r) => r === 0.5,
  },
  {
    name: "rule:2 — sparkline returns empty string for empty input",
    setup: () => [],
    invoke: (api, ctx) => api.sparkline(ctx),
    assert: (r) => r === "",
  },
  {
    name: "rule:2 — sparkline uses middle block for all-equal values",
    setup: () => [5, 5, 5],
    invoke: (api, ctx) => api.sparkline(ctx),
    assert: (r) => r === "▄▄▄",
  },
  {
    name: "rule:2 — sparkline maps finite values to BLOCKS_V",
    setup: () => [0, 0.5, 1],
    invoke: (api, ctx) => api.sparkline(ctx),
    assert: (r) => r === "▁▄█",
  },
  {
    name: "rule:2 — sparkline treats non-finite values as zero",
    setup: () => [0, NaN, Infinity, -Infinity, 1],
    invoke: (api, ctx) => api.sparkline(ctx),
    assert: (r) => r === "▁▁▁▁█",
  },
  {
    name: "rule:3 — bar returns empty string for non-positive width",
    setup: () => ({ value: 0.5, width: 0 }),
    invoke: (api, ctx) => api.bar(ctx.value, ctx.width),
    assert: (r) => r === "",
  },
  {
    name: "rule:3 — bar renders correct fill and empty blocks",
    setup: () => ({ value: 0.6, width: 10 }),
    invoke: (api, ctx) => api.bar(ctx.value, ctx.width),
    assert: (r) => r === "██████░░░░",
  },
  {
    name: "rule:3 — bar clamps NaN to 0",
    setup: () => ({ value: NaN, width: 5 }),
    invoke: (api, ctx) => api.bar(ctx.value, ctx.width),
    assert: (r) => r === "░░░░░",
  },
  {
    name: "rule:4 — barOutOf returns all-empty bar for total <= 0",
    setup: () => ({ count: 5, total: 0, width: 10 }),
    invoke: (api, ctx) => api.barOutOf(ctx.count, ctx.total, ctx.width),
    assert: (r) => r === "░░░░░░░░░░",
  },
  {
    name: "rule:4 — barOutOf divides count by total and calls bar",
    setup: () => ({ count: 6, total: 10, width: 10 }),
    invoke: (api, ctx) => api.barOutOf(ctx.count, ctx.total, ctx.width),
    assert: (r) => r === "██████░░░░",
  },
  {
    name: "rule:5 — barChart returns empty string for no entries",
    setup: () => ({ entries: [], total: 10 }),
    invoke: (api, ctx) => api.barChart(ctx.entries, ctx.total),
    assert: (r) => r === "",
  },
  {
    name: "rule:5 — barChart formats entries with aligned bars",
    setup: () => ({
      entries: [
        { label: "a", count: 5 },
        { label: "long", count: 10 },
      ],
      total: 10,
    }),
    invoke: (api, ctx) => api.barChart(ctx.entries, ctx.total, 10),
    assert: (r) => r === "a     █████░░░░░ 5\nlong  ██████████ 10",
  },
  {
    name: "rule:6 — histogram returns empty for no values",
    setup: () => ({ values: [], nBuckets: 5 }),
    invoke: (api, ctx) => api.histogram(ctx.values, ctx.nBuckets),
    assert: (r) => r.bars === "" && r.axis === "" && r.min === 0 && r.max === 0 && r.total === 0,
  },
  {
    name: "rule:6 — histogram returns full blocks for all-equal values",
    setup: () => ({ values: [3, 3, 3], nBuckets: 4 }),
    invoke: (api, ctx) => api.histogram(ctx.values, ctx.nBuckets),
    assert: (r) => r.bars === "████" && r.axis === "3.00─3.00" && r.min === 3 && r.max === 3 && r.total === 3,
  },
  {
    name: "rule:6 — histogram buckets values correctly",
    setup: () => ({ values: [0, 1, 2, 3, 4], nBuckets: 5 }),
    invoke: (api, ctx) => api.histogram(ctx.values, ctx.nBuckets),
    assert: (r) => r.bars === "█████" && r.axis === "0.00─4.00" && r.min === 0 && r.max === 4 && r.total === 5,
  },
  {
    name: "rule:6 — histogram ignores non-finite values",
    setup: () => ({ values: [1, NaN, 2, Infinity, 3], nBuckets: 3 }),
    invoke: (api, ctx) => api.histogram(ctx.values, ctx.nBuckets),
    assert: (r) => r.bars === "█░░" && r.axis === "1.00─3.00" && r.min === 1 && r.max === 3 && r.total === 3,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17]).has(i));
