// GENERATED by `onto probe node_0170` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 1 self-validated case(s)
// (each matched the source src/forward/templates/schema.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — TemplateNodeSchema validates correct node structure",
    setup: () => ({
      key: "node1",
      level: "concrete",
      kind: "problem",
      prompt: "Example prompt",
      label: "Example Label",
      manifestation: "text",
      language: "typescript",
      requires: ["dep1"],
      provides: ["feature1"],
      forbids: ["badThing"],
      rules: ["rule1"],
      literal: "literal value",
      parent: "canon",
    }),
    invoke: (api, ctx) => api.TemplateNodeSchema.safeParse(ctx),
    assert: (r) => r.success === true,
  },
  {
    name: "rule:2 — TemplateEdgeSchema validates correct edge structure",
    setup: () => ({
      from: "node1",
      to: "node2",
      type: "refines",
    }),
    invoke: (api, ctx) => api.TemplateEdgeSchema.safeParse(ctx),
    assert: (r) => r.success === true,
  },
  {
    name: "rule:3 — TemplateSchema validates correct template structure",
    setup: () => ({
      name: "example-template",
      description: "An example template",
      nodes: [
        {
          key: "node1",
          level: "concrete",
          kind: "problem",
          prompt: "Example prompt",
        },
      ],
      edges: [
        {
          from: "node1",
          to: "canon",
          type: "refines",
        },
      ],
    }),
    invoke: (api, ctx) => api.TemplateSchema.safeParse(ctx),
    assert: (r) => r.success === true,
  },
  {
    name: "TemplateNodeSchema rejects extra properties",
    setup: () => ({
      key: "node1",
      level: "concrete",
      kind: "problem",
      prompt: "Example prompt",
      invalidProp: "should not be here",
    }),
    invoke: (api, ctx) => api.TemplateNodeSchema.safeParse(ctx),
    assert: (r) => r.success === false,
  },
  {
    name: "TemplateEdgeSchema rejects extra properties",
    setup: () => ({
      from: "node1",
      to: "node2",
      type: "refines",
      extra: "not allowed",
    }),
    invoke: (api, ctx) => api.TemplateEdgeSchema.safeParse(ctx),
    assert: (r) => r.success === false,
  },
  {
    name: "TemplateSchema rejects extra properties",
    setup: () => ({
      name: "example-template",
      description: "An example template",
      nodes: [
        {
          key: "node1",
          level: "concrete",
          kind: "problem",
          prompt: "Example prompt",
        },
      ],
      invalidField: "not allowed",
    }),
    invoke: (api, ctx) => api.TemplateSchema.safeParse(ctx),
    assert: (r) => r.success === false,
  },
  {
    name: "TemplateNodeSchema allows minimal valid node",
    setup: () => ({
      key: "minimal",
      level: "concrete",
      kind: "problem",
      prompt: "Minimal prompt",
    }),
    invoke: (api, ctx) => api.TemplateNodeSchema.safeParse(ctx),
    assert: (r) => r.success === true,
  },
  {
    name: "TemplateSchema allows empty edges array",
    setup: () => ({
      name: "minimal-template",
      description: "A minimal template",
      nodes: [
        {
          key: "node1",
          level: "concrete",
          kind: "problem",
          prompt: "Example prompt",
        },
      ],
      edges: [],
    }),
    invoke: (api, ctx) => api.TemplateSchema.safeParse(ctx),
    assert: (r) => r.success === true,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([1]).has(i));
