// GENERATED by `onto probe node_0173` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/laws/topos/predicate.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — atomProvides constructs an atom with tag 'provides'",
    setup: () => ("testToken"),
    invoke: (api, ctx) => api.atomProvides(ctx),
    assert: (r) => r.tag === "atom" && r.atom.tag === "provides" && r.atom.token === "testToken",
  },
  {
    name: "rule:2 — atomRequires constructs an atom with tag 'requires'",
    setup: () => ("requiredToken"),
    invoke: (api, ctx) => api.atomRequires(ctx),
    assert: (r) => r.tag === "atom" && r.atom.tag === "requires" && r.atom.token === "requiredToken",
  },
  {
    name: "rule:3 — atomForbids constructs an atom with tag 'forbids'",
    setup: () => ("forbiddenToken"),
    invoke: (api, ctx) => api.atomForbids(ctx),
    assert: (r) => r.tag === "atom" && r.atom.tag === "forbids" && r.atom.token === "forbiddenToken",
  },
  {
    name: "pAnd simplifies with left true",
    setup: () => ({ left: { tag: "true" }, right: { tag: "atom", atom: { tag: "provides", token: "x" } } }),
    invoke: (api, ctx) => api.pAnd(ctx.left, ctx.right),
    assert: (r) => r.tag === "atom" && r.atom.tag === "provides" && r.atom.token === "x",
  },
  {
    name: "pAnd simplifies with right true",
    setup: () => ({ left: { tag: "atom", atom: { tag: "requires", token: "y" } }, right: { tag: "true" } }),
    invoke: (api, ctx) => api.pAnd(ctx.left, ctx.right),
    assert: (r) => r.tag === "atom" && r.atom.tag === "requires" && r.atom.token === "y",
  },
  {
    name: "pAnd returns false when either operand is false",
    setup: () => ({ left: { tag: "false" }, right: { tag: "atom", atom: { tag: "forbids", token: "z" } } }),
    invoke: (api, ctx) => api.pAnd(ctx.left, ctx.right),
    assert: (r) => r.tag === "false",
  },
  {
    name: "pOr simplifies with left false",
    setup: () => ({ left: { tag: "false" }, right: { tag: "atom", atom: { tag: "provides", token: "a" } } }),
    invoke: (api, ctx) => api.pOr(ctx.left, ctx.right),
    assert: (r) => r.tag === "atom" && r.atom.tag === "provides" && r.atom.token === "a",
  },
  {
    name: "pNot eliminates double negation",
    setup: () => ({ inner: { tag: "not", inner: { tag: "atom", atom: { tag: "requires", token: "b" } } } }),
    invoke: (api, ctx) => api.pNot(ctx.inner),
    assert: (r) => r.tag === "atom" && r.atom.tag === "requires" && r.atom.token === "b",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
