// GENERATED by `onto probe node_0041` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/surfaces/commands/drift.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns undefined when options are valid and no drift detected",
    setup: () => ({
      options: { cwd: "/mock/cwd", update: false, failOnDrift: false, json: false },
    }),
    invoke: (api, ctx) => api.driftCommand(ctx.options),
    assert: (r) => r === undefined,
  },
  {
    name: "rule:2 — updates snapshot and appends event when --update is true",
    setup: () => ({
      options: { cwd: "/mock/cwd", update: true, failOnDrift: false, json: false },
    }),
    invoke: (api, ctx) => api.driftCommand(ctx.options),
    assert: (r) => r === undefined,
  },
  {
    name: "rule:3 — outputs JSON when --json flag is set",
    setup: () => ({
      options: { cwd: "/mock/cwd", update: false, failOnDrift: false, json: true },
    }),
    invoke: (api, ctx) => api.driftCommand(ctx.options),
    assert: (r) => r === undefined,
  },
  {
    name: "rule:4 — exits with code 1 when --failOnDrift is true and drift is detected without update",
    setup: () => ({
      options: { cwd: "/mock/cwd", update: false, failOnDrift: true, json: false },
    }),
    invoke: (api, ctx) => api.driftCommand(ctx.options),
    assert: (r) => r === undefined,
  },
  {
    name: "rule:5 — handles empty node outputs gracefully",
    setup: () => ({
      options: { cwd: "/mock/empty", update: false, failOnDrift: false, json: false },
    }),
    invoke: (api, ctx) => api.driftCommand(ctx.options),
    assert: (r) => r === undefined,
  },
  {
    name: "rule:6 — reports missing files in output",
    setup: () => ({
      options: { cwd: "/mock/missing", update: false, failOnDrift: false, json: false },
    }),
    invoke: (api, ctx) => api.driftCommand(ctx.options),
    assert: (r) => r === undefined,
  },
  {
    name: "rule:7 — reads drift state correctly",
    setup: () => ({ cwd: "/mock/cwd" }),
    invoke: (api, ctx) => Promise.resolve(api.readDriftState(ctx.cwd)),
    assert: (r) => typeof r === "object" && r !== null && "tree" in r && "drifted" in r,
  },
  {
    name: "rule:8 — handles non-existent ontology directory",
    setup: () => ({
      options: { cwd: "/mock/invalid", update: false, failOnDrift: false, json: false },
    }),
    invoke: (api, ctx) => api.driftCommand(ctx.options),
    assert: (r) => r === undefined,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
