// GENERATED by `onto probe node_0128` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/laws/contract-checker.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { ContractCheckResult } from "./contract-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns no_regen when regenText is undefined",
    setup: () => ({
      nodeId: "node1",
      declared: [{ key: "foo" }],
      regenText: undefined,
      regenFileName: "test.ts",
    }),
    invoke: (api, ctx) => api.checkContract(ctx),
    assert: (r: ContractCheckResult) => r.reason === "no_regen" && r.state === "not-measured",
  },
  {
    name: "rule:2 — returns no_declared_contract when declared is empty",
    setup: () => ({
      nodeId: "node2",
      declared: [],
      regenText: "export const foo = 1;",
      regenFileName: "test.ts",
    }),
    invoke: (api, ctx) => api.checkContract(ctx),
    assert: (r: ContractCheckResult) => r.reason === "no_declared_contract" && r.state === "unknown",
  },
  {
    name: "rule:3 — returns unparseable_language for unsupported file extension",
    setup: () => ({
      nodeId: "node3",
      declared: [{ key: "foo" }],
      regenText: "export const foo = 1;",
      regenFileName: "test.xyz",
    }),
    invoke: (api, ctx) => api.checkContract(ctx),
    assert: (r: ContractCheckResult) => r.reason === "unparseable_language" && r.state === "unknown",
  },
  {
    name: "rule:4 — returns parse_failed for invalid TypeScript syntax",
    setup: () => ({
      nodeId: "node4",
      declared: [{ key: "foo" }],
      regenText: "export const foo = ;", // Invalid syntax
      regenFileName: "test.ts",
    }),
    invoke: (api, ctx) => api.checkContract(ctx),
    assert: (r: ContractCheckResult) => r.reason === "parse_failed" && r.state === "unknown",
  },
  {
    name: "rule:5 — returns satisfied when all keys match with correct signatures",
    setup: () => ({
      nodeId: "node5",
      declared: [{ key: "foo", signature: "number" }],
      regenText: "export const foo: number = 1;",
      regenFileName: "test.ts",
    }),
    invoke: (api, ctx) => api.checkContract(ctx),
    assert: (r: ContractCheckResult) => r.reason === "satisfied" && r.state === "pass",
  },
  {
    name: "rule:6 — returns missing_keys when declared key is absent",
    setup: () => ({
      nodeId: "node6",
      declared: [{ key: "foo", signature: "number" }],
      regenText: "export const bar = 1;",
      regenFileName: "test.ts",
    }),
    invoke: (api, ctx) => api.checkContract(ctx),
    assert: (r: ContractCheckResult) => r.reason === "missing_keys" && r.state === "fail" && r.missingKeys.includes("foo"),
  },
  {
    name: "rule:7 — returns signature_drift when signatures differ",
    setup: () => ({
      nodeId: "node7",
      declared: [{ key: "foo", signature: "string" }],
      regenText: "export const foo: number = 1;",
      regenFileName: "test.ts",
    }),
    invoke: (api, ctx) => api.checkContract(ctx),
    assert: (r: ContractCheckResult) => r.reason === "signature_drift" && r.state === "fail" && r.driftedKeys.length > 0,
  },
  {
    name: "rule:8 — returns missing_keys+signature_drift when both issues occur",
    setup: () => ({
      nodeId: "node8",
      declared: [
        { key: "foo", signature: "string" },
        { key: "bar", signature: "boolean" },
      ],
      regenText: "export const foo: number = 1;", // Wrong signature for foo, missing bar
      regenFileName: "test.ts",
    }),
    invoke: (api, ctx) => api.checkContract(ctx),
    assert: (r: ContractCheckResult) => r.reason === "missing_keys+signature_drift" && r.state === "fail" && r.missingKeys.includes("bar") && r.driftedKeys.length > 0,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 4, 5, 6, 7]).has(i));
