// GENERATED by `onto probe node_0132` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 7 self-validated case(s)
// (each matched the source src/inverse/intent-narration.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type { NeighborhoodFile } from "../../src/inverse/intent-narration.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — single file prompt starts and ends correctly",
    setup: () => ({
      files: [
        { path: "src/test.ts", content: "export const x = 42;" }
      ] as NeighborhoodFile[]
    }),
    invoke: (api, ctx) => api.buildIntentNeighborhoodPrompt(ctx.files),
    assert: (r: string) => r.startsWith("Narrate the intent of this file") && r.endsWith("Output the IntentNarration JSON only."),
  },
  {
    name: "rule:2 — multiple files prompt includes composed intent instruction",
    setup: () => ({
      files: [
        { path: "src/a.ts", content: "export const a = 1;" },
        { path: "src/b.ts", content: "export const b = 2;" }
      ] as NeighborhoodFile[]
    }),
    invoke: (api, ctx) => api.buildIntentNeighborhoodPrompt(ctx.files),
    assert: (r: string) => r.includes("Narrate the COMPOSED intent of the subsystem they form together") && r.includes("Output a single IntentNarration JSON for the composed subsystem only."),
  },
  {
    name: "rule:3 — throws when files array is empty",
    setup: () => ({ files: [] as NeighborhoodFile[] }),
    invoke: (api, ctx) => {
      try {
        return api.buildIntentNeighborhoodPrompt(ctx.files);
      } catch (e) {
        return e;
      }
    },
    assert: (r: unknown) => r instanceof Error && r.message === "buildIntentNeighborhoodPrompt: at least one file is required",
  },
  {
    name: "rule:4 — includes framed file content for single file",
    setup: () => ({
      files: [
        { path: "example.ts", content: "console.log('hello');" }
      ] as NeighborhoodFile[]
    }),
    invoke: (api, ctx) => api.buildIntentNeighborhoodPrompt(ctx.files),
    assert: (r: string) => r.includes("File: example.ts") && r.includes("console.log('hello');") && r.includes("--- BEGIN FILE ---") && r.includes("--- END FILE ---"),
  },
  {
    name: "rule:5 — includes all files framed for multiple files",
    setup: () => ({
      files: [
        { path: "a.ts", content: "const a = 1;" },
        { path: "b.ts", content: "const b = 2;" }
      ] as NeighborhoodFile[]
    }),
    invoke: (api, ctx) => api.buildIntentNeighborhoodPrompt(ctx.files),
    assert: (r: string) => r.includes("File: a.ts") && r.includes("File: b.ts") && r.includes("const a = 1;") && r.includes("const b = 2;"),
  },
  {
    name: "rule:6 — uses correct language hint for TypeScript file",
    setup: () => ({
      files: [
        { path: "test.ts", content: "let x = 0;" }
      ] as NeighborhoodFile[]
    }),
    invoke: (api, ctx) => api.buildIntentNeighborhoodPrompt(ctx.files),
    assert: (r: string) => r.includes("Language hint (from extension): typescript"),
  },
  {
    name: "rule:7 — uses correct language hint for Python file",
    setup: () => ({
      files: [
        { path: "script.py", content: "print('hello')" }
      ] as NeighborhoodFile[]
    }),
    invoke: (api, ctx) => api.buildIntentNeighborhoodPrompt(ctx.files),
    assert: (r: string) => r.includes("Language hint (from extension): python"),
  },
  {
    name: "rule:8 — unknown extension gets unknown language hint",
    setup: () => ({
      files: [
        { path: "data.xyz", content: "arbitrary content" }
      ] as NeighborhoodFile[]
    }),
    invoke: (api, ctx) => api.buildIntentNeighborhoodPrompt(ctx.files),
    assert: (r: string) => r.includes("Language hint (from extension): unknown"),
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 2, 3, 4, 5, 6, 7]).has(i));
