// GENERATED by `onto probe node_0217` (model: frontier-subagent). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/walker/state/shadow-status.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/runtime/legend/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "shadowReport: empty outputs.files yields no_shadow with empty arrays",
    setup: () => ({
      node: { outputs: { files: [] } } as any,
      cwd: "/tmp/nonexistent-onto-cwd-xyz",
    }),
    invoke: (api, ctx) => (api as any).shadowReport(ctx.node, ctx.cwd),
    assert: (r) =>
      r.status === "no_shadow" &&
      Array.isArray(r.files) &&
      r.files.length === 0 &&
      Array.isArray(r.driftedFiles) &&
      r.driftedFiles.length === 0,
  },
  {
    name: "shadowReport: returns an object with status/files/driftedFiles shape",
    setup: () => ({
      node: { outputs: { files: [] } } as any,
      cwd: "/tmp/nonexistent-onto-cwd-xyz",
    }),
    invoke: (api, ctx) => (api as any).shadowReport(ctx.node, ctx.cwd),
    assert: (r) =>
      typeof r === "object" &&
      r !== null &&
      "status" in r &&
      "files" in r &&
      "driftedFiles" in r,
  },
  {
    name: "readArtifactPreview: no shadow file yields null file, empty preview",
    setup: () => ({
      node: { outputs: { files: [] } } as any,
      cwd: "/tmp/nonexistent-onto-cwd-xyz",
    }),
    invoke: (api, ctx) => (api as any).readArtifactPreview(ctx.node, ctx.cwd),
    assert: (r) =>
      r.file === null &&
      Array.isArray(r.lines) &&
      r.lines.length === 0 &&
      r.totalLines === 0 &&
      r.truncated === false &&
      r.error === undefined,
  },
  {
    name: "readArtifactPreview: empty files returns object with required keys",
    setup: () => ({
      node: { outputs: { files: [] } } as any,
      cwd: "/tmp/nonexistent-onto-cwd-xyz",
    }),
    invoke: (api, ctx) => (api as any).readArtifactPreview(ctx.node, ctx.cwd),
    assert: (r) =>
      "file" in r && "lines" in r && "totalLines" in r && "truncated" in r,
  },
  {
    name: "nodesOwningFile: returns empty array when no node owns the file",
    setup: () => ({
      nodes: [
        { outputs: { files: ["src/a.ts"] } },
        { outputs: { files: ["src/b.ts"] } },
      ] as any[],
      fileArg: "src/zzz-not-present.ts",
      cwd: "/tmp/nonexistent-onto-cwd-xyz",
    }),
    invoke: (api, ctx) =>
      (api as any).nodesOwningFile(ctx.nodes, ctx.fileArg, ctx.cwd),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
  {
    name: "nodesOwningFile: matches the single node owning the relative path",
    setup: () => ({
      nodes: [
        { id: "n0", outputs: { files: ["src/a.ts"] } },
        { id: "n1", outputs: { files: ["src/b.ts"] } },
      ] as any[],
      fileArg: "src/b.ts",
      cwd: "/tmp/nonexistent-onto-cwd-xyz",
    }),
    invoke: (api, ctx) =>
      (api as any).nodesOwningFile(ctx.nodes, ctx.fileArg, ctx.cwd),
    assert: (r) =>
      Array.isArray(r) && r.length === 1 && r[0].id === "n1",
  },
  {
    name: "nodesOwningFile: returns every node whose shadow contains the path",
    setup: () => ({
      nodes: [
        { id: "n0", outputs: { files: ["src/shared.ts", "src/a.ts"] } },
        { id: "n1", outputs: { files: ["src/b.ts"] } },
        { id: "n2", outputs: { files: ["src/shared.ts"] } },
      ] as any[],
      fileArg: "src/shared.ts",
      cwd: "/tmp/nonexistent-onto-cwd-xyz",
    }),
    invoke: (api, ctx) =>
      (api as any).nodesOwningFile(ctx.nodes, ctx.fileArg, ctx.cwd),
    assert: (r) =>
      Array.isArray(r) &&
      r.length === 2 &&
      r[0].id === "n0" &&
      r[1].id === "n2",
  },
  {
    name: "nodesOwningFile: empty node list yields empty result",
    setup: () => ({
      nodes: [] as any[],
      fileArg: "src/a.ts",
      cwd: "/tmp/nonexistent-onto-cwd-xyz",
    }),
    invoke: (api, ctx) =>
      (api as any).nodesOwningFile(ctx.nodes, ctx.fileArg, ctx.cwd),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
