// GENERATED by `onto probe node_0112` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/laws/fibration/branch-fiber.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — listBranches returns unique branches sorted lexicographically",
    setup: () => ({
      nodes: [
        { id: "1", coordinates: { branch: "zebra" } },
        { id: "2", coordinates: { branch: "apple" } },
        { id: "3", coordinates: { branch: "zebra" } },
        { id: "4", coordinates: { branch: "apple" } },
      ],
      edges: [],
    }),
    invoke: (api, ctx) => api.listBranches(ctx),
    assert: (r) => Array.isArray(r) && r.length === 2 && r[0] === "apple" && r[1] === "zebra",
  },
  {
    name: "rule:2 — computeBranchFiber filters nodes and edges by branch",
    setup: () => ({
      nodes: [
        { id: "a", coordinates: { branch: "main" } },
        { id: "b", coordinates: { branch: "dev" } },
        { id: "c", coordinates: { branch: "main" } },
      ],
      edges: [
        { from: "a", to: "c" },
        { from: "a", to: "b" },
      ],
    }),
    invoke: (api, ctx) => api.computeBranchFiber(ctx, "main"),
    assert: (r) =>
      r.branch === "main" &&
      r.nodes.length === 2 &&
      r.edges.length === 1 &&
      r.size.nodes === 2 &&
      r.size.edges === 1,
  },
  {
    name: "rule:3 — computeAllFibers partitions all nodes across branches",
    setup: () => ({
      nodes: [
        { id: "x", coordinates: { branch: "beta" } },
        { id: "y", coordinates: { branch: "alpha" } },
        { id: "z", coordinates: { branch: "beta" } },
      ],
      edges: [],
    }),
    invoke: (api, ctx) => api.computeAllFibers(ctx),
    assert: (r) =>
      r.branches.length === 2 &&
      r.fibers.length === 2 &&
      r.fibers.flatMap((f) => f.nodes).length === 3,
  },
  {
    name: "rule:4 — describeCartesianLift generates correct proposal shape",
    setup: () => ({
      node: {
        id: "node_123",
        coordinates: { branch: "source" },
        kind: "artifact",
        abstraction: "file",
        manifestation: "txt",
        outputs: { files: [] },
      },
      targetBranch: "target",
    }),
    invoke: (api, ctx) => api.describeCartesianLift(ctx.node, ctx.targetBranch),
    assert: (r) =>
      r.source.branch === "source" &&
      r.targetBranch === "target" &&
      r.proposed.id === "node_123@target" &&
      r.proposed.coordinates.branch === "target" &&
      r.preserves.kind === true &&
      r.preserves.abstraction === true &&
      r.preserves.manifestation === true,
  },
  {
    name: "rule:5 — computeBranchFiberFromArrays calls computeBranchFiber correctly",
    setup: () => ({
      nodes: [{ id: "n1", coordinates: { branch: "test" } }],
      edges: [],
      branch: "test",
    }),
    invoke: (api, ctx) => api.computeBranchFiberFromArrays(ctx.nodes, ctx.edges, ctx.branch),
    assert: (r) =>
      r.branch === "test" &&
      r.nodes.length === 1 &&
      r.edges.length === 0 &&
      r.size.nodes === 1 &&
      r.size.edges === 0,
  },
  {
    name: "rule:6 — computeFiberBy groups nodes and edges by projection result",
    setup: () => ({
      input: {
        nodes: [
          { id: "1", outputs: { files: ["dir1/file.ts"] } },
          { id: "2", outputs: { files: ["dir2/file.ts"] } },
          { id: "3", outputs: { files: ["dir1/other.ts"] } },
        ],
        edges: [
          { from: "1", to: "3" },
          { from: "1", to: "2" },
        ],
      },
      projection: (node: any) => node.outputs?.files?.[0]?.split("/")[0],
    }),
    invoke: (api, ctx) => api.computeFiberBy(ctx.input, ctx.projection),
    assert: (r) => r instanceof Map && r.size === 2,
  },
  {
    name: "rule:7 — pathProjection returns parent directory of first output file",
    setup: () => ({
      node: {
        id: "test",
        outputs: { files: ["src/components/button.ts"] },
      },
    }),
    invoke: (api, ctx) => api.pathProjection(ctx.node),
    assert: (r) => r === "src/components",
  },
  {
    name: "rule:8 — pathProjection returns undefined when no outputs or empty first entry",
    setup: () => ({
      node1: { id: "a", outputs: { files: [] } },
      node2: { id: "b", outputs: { files: [""] } },
      node3: { id: "c" },
    }),
    invoke: (api, ctx) => [
      api.pathProjection(ctx.node1),
      api.pathProjection(ctx.node2),
      api.pathProjection(ctx.node3),
    ],
    assert: (r) => Array.isArray(r) && r.every((v) => v === undefined),
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
