// GENERATED by `onto probe node_0018` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 4 self-validated case(s)
// (each matched the source src/kernel/core/nodes/remove-node.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — refuses removal when node has incident edges",
    setup: () => ({
      options: {
        id: "node_0001",
        cwd: "/mock/cwd",
        eventMetadata: { source: "test" },
      },
      mockFsExists: true,
      mockEdges: [
          { from: "node_0001", to: "node_0002", label: "related_to" },
      ],
    }),
    invoke: (api, ctx) => {
      // Simulate refusal due to incident edges
      try {
        return (api as any).removeNode(ctx.options);
      } catch (e) {
        return e;
      }
    },
    assert: (r) => r instanceof (global as any).NodeHasEdgesError && r.nodeId === "node_0001" && r.edges.length === 1,
  },
  {
    name: "rule:2 — throws error if node file does not exist",
    setup: () => ({
      options: {
        id: "nonexistent_node",
        cwd: "/mock/cwd",
      },
      mockFsExists: false,
    }),
    invoke: (api, ctx) => {
      try {
        return (api as any).removeNode(ctx.options);
      } catch (e) {
        return e;
      }
    },
    assert: (r) => r instanceof Error && r.message.includes("Node not found"),
  },
  {
    name: "rule:3 — returns event on successful node removal",
    setup: () => ({
      options: {
        id: "node_0002",
        cwd: "/mock/cwd",
        eventMetadata: { reason: "obsolete" },
      },
      mockFsExists: true,
      mockEdges: [],
    }),
    invoke: (api, ctx) => {
      return (api as any).removeNode(ctx.options);
    },
    assert: (r) => r && typeof r === "object" && r.event && r.event.eventType === "node_removed",
  },
  {
    name: "rule:4 — NodeHasEdgesError correctly formats message with edge count",
    setup: () => ({
      nodeId: "test_node",
      edges: [
        { from: "test_node", to: "other_node", label: "connected_to" },
        { from: "another_node", to: "test_node", label: "depends_on" },
      ],
    }),
    invoke: (api, ctx) => {
      return new (api as any).NodeHasEdgesError(ctx.nodeId, ctx.edges);
    },
    assert: (r) => 
      r.message === "Node test_node has 2 incident edge(s) — remove them first with onto edge remove." &&
      r.nodeId === "test_node" &&
      r.edges.length === 2,
  },
  {
    name: "typical case with minimal options",
    setup: () => ({
      options: {
        id: "node_0003",
      },
      mockFsExists: true,
      mockEdges: [],
    }),
    invoke: (api, ctx) => {
      return (api as any).removeNode(ctx.options);
    },
    assert: (r) => r && typeof r === "object" && r.event && typeof r.event.eventId === "string",
  },
  {
    name: "empty eventMetadata handled correctly",
    setup: () => ({
      options: {
        id: "node_0004",
        cwd: "/another/cwd",
        eventMetadata: {},
      },
      mockFsExists: true,
      mockEdges: [],
    }),
    invoke: (api, ctx) => {
      return (api as any).removeNode(ctx.options);
    },
    assert: (r) => r && typeof r === "object" && r.event && typeof r.event.payload === "object",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([1, 2, 3, 5]).has(i));
