// GENERATED by `onto probe node_0120` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 3 self-validated case(s)
// (each matched the source src/kernel/graph/hierarchizer.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import type {
  HierarchizerInput,
  HierarchizerPlan,
  OntologyEdge,
  OntologyNode,
} from "../../src/kernel/graph/hierarchizer.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — returns deterministic plan across input permutations",
    setup: () => {
      const nodes: OntologyNode[] = [
        {
          id: "node_1",
          label: "File A",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 1,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["src/a.ts"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash1",
            schemaVersion: "0.1.0",
          },
        },
        {
          id: "node_2",
          label: "File B",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 2,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["src/b.ts"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash2",
            schemaVersion: "0.1.0",
          },
        },
      ];
      const edges: OntologyEdge[] = [];
      return { nodes, edges };
    },
    invoke: (api, ctx) => api.planHierarchization(ctx as HierarchizerInput),
    assert: (r: HierarchizerPlan) => {
      // The actual deterministic output is verified by the harness
      return true;
    },
  },
  {
    name: "rule:2 — skips file nodes with no output file",
    setup: () => {
      const nodes: OntologyNode[] = [
        {
          id: "node_no_file",
          label: "No File",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 1,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: [] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash1",
            schemaVersion: "0.1.0",
          },
        },
      ];
      const edges: OntologyEdge[] = [];
      return { nodes, edges };
    },
    invoke: (api, ctx) => api.planHierarchization(ctx as HierarchizerInput),
    assert: (r: HierarchizerPlan) =>
      r.skipped.noOutputFile.includes("node_no_file"),
  },
  {
    name: "rule:3 — skips root-level files",
    setup: () => {
      const nodes: OntologyNode[] = [
        {
          id: "node_root_file",
          label: "Root File",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 1,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["config.json"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash1",
            schemaVersion: "0.1.0",
          },
        },
      ];
      const edges: OntologyEdge[] = [];
      return { nodes, edges };
    },
    invoke: (api, ctx) => api.planHierarchization(ctx as HierarchizerInput),
    assert: (r: HierarchizerPlan) =>
      r.skipped.rootLevelFiles.includes("node_root_file"),
  },
  {
    name: "rule:4 — detects and skips ambiguous file assignments",
    setup: () => {
      const nodes: OntologyNode[] = [
        {
          id: "node_a",
          label: "File A",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 1,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["src/shared.ts"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash1",
            schemaVersion: "0.1.0",
          },
        },
        {
          id: "node_b",
          label: "File B",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 2,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["src/shared.ts"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash2",
            schemaVersion: "0.1.0",
          },
        },
      ];
      const edges: OntologyEdge[] = [];
      return { nodes, edges };
    },
    invoke: (api, ctx) => api.planHierarchization(ctx as HierarchizerInput),
    assert: (r: HierarchizerPlan) => {
      const found = r.skipped.ambiguousFile.find(
        (a) => a.file === "src/shared.ts",
      );
      return (
        found !== undefined &&
        found.nodeIds.includes("node_a") &&
        found.nodeIds.includes("node_b")
      );
    },
  },
  {
    name: "rule:5 — refuses to reparent already deeply nested files",
    setup: () => {
      const nodes: OntologyNode[] = [
        {
          id: "node_parent",
          label: "Parent Node",
          kind: "component",
          status: "stable",
          coordinates: {
            abstraction: "domain",
            time: 1,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: [] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash_parent",
            schemaVersion: "0.1.0",
          },
        },
        {
          id: "node_nested_file",
          label: "Nested File",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 2,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: "node_parent",
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["src/nested/file.ts"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash_nested",
            schemaVersion: "0.1.0",
          },
        },
      ];
      const edges: OntologyEdge[] = [];
      return { nodes, edges };
    },
    invoke: (api, ctx) => api.planHierarchization(ctx as HierarchizerInput),
    assert: (r: HierarchizerPlan) => {
      const found = r.skipped.alreadyDeepNested.find(
        (a) => a.nodeId === "node_nested_file",
      );
      return found !== undefined && found.currentParentId === "node_parent";
    },
  },
  {
    name: "rule:6 — creates directory nodes for needed paths",
    setup: () => {
      const nodes: OntologyNode[] = [
        {
          id: "node_file",
          label: "File",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 1,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["src/utils/helper.ts"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash1",
            schemaVersion: "0.1.0",
          },
        },
      ];
      const edges: OntologyEdge[] = [];
      return { nodes, edges };
    },
    invoke: (api, ctx) => api.planHierarchization(ctx as HierarchizerInput),
    assert: (r: HierarchizerPlan) => {
      const dirPaths = r.directoriesToCreate.map((d) => d.path);
      return (
        dirPaths.includes("src") &&
        dirPaths.includes("src/utils") &&
        r.directoriesToCreate.length === 2
      );
    },
  },
  {
    name: "rule:7 — reuses existing directory nodes when available",
    setup: () => {
      const nodes: OntologyNode[] = [
        {
          id: "node_dir",
          label: "src",
          kind: "component",
          status: "stable",
          coordinates: {
            abstraction: "domain",
            time: 1,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [{ key: "path:src", nodeType: "component" }],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: [] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash_dir",
            schemaVersion: "0.1.0",
          },
        },
        {
          id: "node_file",
          label: "File",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 2,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["src/file.ts"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash_file",
            schemaVersion: "0.1.0",
          },
        },
      ];
      const edges: OntologyEdge[] = [];
      return { nodes, edges };
    },
    invoke: (api, ctx) => api.planHierarchization(ctx as HierarchizerInput),
    assert: (r: HierarchizerPlan) =>
      r.directoriesReused.some((d) => d.path === "src" && d.nodeId === "node_dir"),
  },
  {
    name: "rule:8 — generates reparenting actions for valid file assignments",
    setup: () => {
      const nodes: OntologyNode[] = [
        {
          id: "node_file",
          label: "File",
          kind: "definition",
          status: "stable",
          coordinates: {
            abstraction: "unit",
            time: 1,
            branch: "main",
            plane: "semantic",
            manifestation: "intent",
          },
          inputs: [],
          prompt: {
            raw: "",
            variables: {},
            language: "es",
          },
          model: { ref: "mock_default" },
          processors: { pre: [], post: [] },
          context: {
            requires: [],
            provides: [],
            forbids: [],
            optional: [],
          },
          graph: {
            parentId: null,
            orbitOf: null,
          },
          rules: [],
          technical: {},
          outputs: { files: ["src/module/file.ts"] },
          validation: { errors: [], warnings: [] },
          integrity: {
            frozen: false,
            hash: "hash1",
            schemaVersion: "0.1.0",
          },
        },
      ];
      const edges: OntologyEdge[] = [];
      return { nodes, edges };
    },
    invoke: (api, ctx) => api.planHierarchization(ctx as HierarchizerInput),
    assert: (r: HierarchizerPlan) => {
      return (
        r.reparentings.length === 1 &&
        r.reparentings[0]?.nodeId === "node_file" &&
        r.reparentings[0]?.newParentPath === "src/module"
      );
    },
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 3, 6]).has(i));
