// GENERATED by `onto probe node_0103` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 6 self-validated case(s)
// (each matched the source src/forward/context/intent-validator.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — buildEvaluationContext with gluing ok",
    setup: () => ({
      input: {
        assembled: { constraints: [] },
        glued: { ok: true, conflicts: [], warnings: [] },
        candidate: { text: "hello", provider: "openai", model: "gpt-4" },
      },
    }),
    invoke: (api, ctx) => api.buildEvaluationContext(ctx.input),
    assert: (r) => r.providedTokens.has("__validator__:gluing_ok") && !r.deniedTokens.has("__validator__:gluing_ok"),
  },
  {
    name: "rule:1 — buildEvaluationContext with gluing failed",
    setup: () => ({
      input: {
        assembled: { constraints: [] },
        glued: { ok: false, conflicts: [{ type: "duplicate_definition", message: "conflict" }], warnings: [] },
        candidate: { text: "hello", provider: "openai", model: "gpt-4" },
      },
    }),
    invoke: (api, ctx) => api.buildEvaluationContext(ctx.input),
    assert: (r) => r.deniedTokens.has("__validator__:gluing_ok") && !r.providedTokens.has("__validator__:gluing_ok"),
  },
  {
    name: "rule:1 — buildEvaluationContext with non-empty candidate",
    setup: () => ({
      input: {
        assembled: { constraints: [] },
        glued: { ok: true, conflicts: [], warnings: [] },
        candidate: { text: "hello", provider: "openai", model: "gpt-4" },
      },
    }),
    invoke: (api, ctx) => api.buildEvaluationContext(ctx.input),
    assert: (r) => r.providedTokens.has("__validator__:candidate_nonempty") && !r.deniedTokens.has("__validator__:candidate_nonempty"),
  },
  {
    name: "rule:1 — buildEvaluationContext with empty candidate",
    setup: () => ({
      input: {
        assembled: { constraints: [] },
        glued: { ok: true, conflicts: [], warnings: [] },
        candidate: { text: "", provider: "openai", model: "gpt-4" },
      },
    }),
    invoke: (api, ctx) => api.buildEvaluationContext(ctx.input),
    assert: (r) => r.deniedTokens.has("__validator__:candidate_nonempty") && !r.providedTokens.has("__validator__:candidate_nonempty"),
  },
  {
    name: "rule:2 — compileValidationPredicate with forbid phrase",
    setup: () => ({
      input: {
        assembled: { constraints: ["FORBID: forbidden phrase"] },
        glued: { ok: true, conflicts: [], warnings: [] },
        candidate: { text: "hello", provider: "openai", model: "gpt-4" },
      },
    }),
    invoke: (api, ctx) => api.compileValidationPredicate(ctx.input),
    assert: (r) => r.rules.length === 3 && r.rules.some(rule => rule.id === "forbid:forbidden phrase"),
  },
  {
    name: "rule:2 — compileValidationPredicate without forbid phrase",
    setup: () => ({
      input: {
        assembled: { constraints: [] },
        glued: { ok: true, conflicts: [], warnings: [] },
        candidate: { text: "hello", provider: "openai", model: "gpt-4" },
      },
    }),
    invoke: (api, ctx) => api.compileValidationPredicate(ctx.input),
    assert: (r) => r.rules.length === 2 && r.rules.every(rule => rule.id !== "forbid:forbidden phrase"),
  },
  {
    name: "rule:3 — validateIntent with valid input",
    setup: () => ({
      input: {
        assembled: { constraints: [] },
        glued: { ok: true, conflicts: [], warnings: [] },
        candidate: { text: "hello", provider: "openai", model: "gpt-4" },
      },
    }),
    invoke: (api, ctx) => api.validateIntent(ctx.input),
    assert: (r) => r.ok === true && r.score === 1.0 && r.violations.length === 0 && r.verdict === "true",
  },
  {
    name: "rule:3 — validateIntent with forbidden phrase",
    setup: () => ({
      input: {
        assembled: { constraints: ["FORBID: forbidden"] },
        glued: { ok: true, conflicts: [], warnings: [] },
        candidate: { text: "this is forbidden", provider: "openai", model: "gpt-4" },
      },
    }),
    invoke: (api, ctx) => api.validateIntent(ctx.input),
    assert: (r) => r.ok === false && r.score === 0.5 && r.violations.includes("Forbidden phrase found: forbidden") && r.verdict === "false",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 6, 7]).has(i));
