// GENERATED by `onto probe node_0032` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 30 self-validated case(s)
// (each matched the source src/kernel/schemas/ontology.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — OntologySchemaVersion is semantically valid",
    setup: () => ({}),
    invoke: (api) => api.OntologySchemaVersion,
    assert: (r) => r === "0.1.0",
  },
  {
    name: "rule:2 — AbstractionLevelSchema enum values are correct",
    setup: () => ({}),
    invoke: (api) => (api as any).AbstractionLevelSchema._def.values,
    assert: (r) => Array.isArray(r) && r.length === 11,
  },
  {
    name: "rule:3 — PlaneSchema enum values are correct",
    setup: () => ({}),
    invoke: (api) => (api as any).PlaneSchema._def.values,
    assert: (r) => Array.isArray(r) && r.length === 8,
  },
  {
    name: "rule:4 — ManifestationSchema enum values are correct",
    setup: () => ({}),
    invoke: (api) => (api as any).ManifestationSchema._def.values,
    assert: (r) => Array.isArray(r) && r.length === 6,
  },
  {
    name: "rule:5 — NodeKindSchema enum values are correct",
    setup: () => ({}),
    invoke: (api) => (api as any).NodeKindSchema._def.values,
    assert: (r) => Array.isArray(r) && r.length === 13,
  },
  {
    name: "rule:6 — NodeStatusSchema enum values are correct",
    setup: () => ({}),
    invoke: (api) => (api as any).NodeStatusSchema._def.values,
    assert: (r) => Array.isArray(r) && r.length === 7,
  },
  {
    name: "rule:7 — EdgeTypeSchema enum values are correct",
    setup: () => ({}),
    invoke: (api) => (api as any).EdgeTypeSchema._def.values,
    assert: (r) => Array.isArray(r) && r.length === 18,
  },
  {
    name: "rule:8 — NodeCoordinatesSchema validates with defaults",
    setup: () => ({
      abstraction: "project",
      time: 0,
    }),
    invoke: (api, ctx) => (api as any).NodeCoordinatesSchema.parse(ctx),
    assert: (r) => r.branch === "main" && r.plane === "semantic" && r.manifestation === "intent",
  },
  {
    name: "rule:9 — NodeInputSchema handles text input with default role",
    setup: () => ({
      type: "text",
      value: "test",
    }),
    invoke: (api, ctx) => (api as any).NodeInputSchema.parse(ctx),
    assert: (r) => r.role === "source",
  },
  {
    name: "rule:10 — NodeInputSchema handles asset_ref input with default role",
    setup: () => ({
      type: "asset_ref",
      assetId: "asset_123",
    }),
    invoke: (api, ctx) => (api as any).NodeInputSchema.parse(ctx),
    assert: (r) => r.role === "source",
  },
  {
    name: "rule:11 — NodeInputSchema handles url input with default role",
    setup: () => ({
      type: "url",
      url: "https://example.com",
    }),
    invoke: (api, ctx) => (api as any).NodeInputSchema.parse(ctx),
    assert: (r) => r.role === "reference",
  },
  {
    name: "rule:12 — ContextContractSchema provides default arrays",
    setup: () => ({}),
    invoke: (api, ctx) => (api as any).ContextContractSchema.parse(ctx),
    assert: (r) => Array.isArray(r.requires) && Array.isArray(r.provides) && Array.isArray(r.forbids) && Array.isArray(r.optional),
  },
  {
    name: "rule:13 — NodeModelRefSchema defaults to mock_default",
    setup: () => ({}),
    invoke: (api, ctx) => (api as any).NodeModelRefSchema.parse(ctx),
    assert: (r) => r.ref === "mock_default",
  },
  {
    name: "rule:14 — NodeProcessorsSchema provides default arrays",
    setup: () => ({}),
    invoke: (api, ctx) => (api as any).NodeProcessorsSchema.parse(ctx),
    assert: (r) => Array.isArray(r.pre) && Array.isArray(r.post),
  },
  {
    name: "rule:15 — TechnicalDescriptorSchema provides default object",
    setup: () => ({}),
    invoke: (api, ctx) => (api as any).TechnicalDescriptorSchema.parse(ctx),
    assert: (r) => typeof r === "object",
  },
  {
    name: "rule:16 — OntologyNodeSchema provides defaults for status and other fields",
    setup: () => ({
      id: "node_123",
      label: "test",
      kind: "function",
      coordinates: {
        abstraction: "project",
        time: 0,
      },
      context: {},
      integrity: {
        hash: "hash123",
        schemaVersion: "0.1.0",
      },
    }),
    invoke: (api, ctx) => (api as any).OntologyNodeSchema.parse(ctx),
    assert: (r) => r.status === "draft" && Array.isArray(r.inputs) && r.model.ref === "mock_default",
  },
  {
    name: "rule:17 — OntologyEdgeSchema validates with defaults",
    setup: () => ({
      edgeId: "edge_123",
      from: "node_1",
      to: "node_2",
      type: "inherits_from",
      createdAt: "2023-01-01",
      createdByEventId: "evt_123",
      integrity: {
        hash: "hash123",
        schemaVersion: "0.1.0",
      },
    }),
    invoke: (api, ctx) => (api as any).OntologyEdgeSchema.parse(ctx),
    assert: (r) => r.branch === "main",
  },
  {
    name: "rule:18 — OntologyEventSchema validates with defaults",
    setup: () => ({
      eventId: "evt_123",
      sequence: 0,
      timestamp: "2023-01-01",
      eventType: "system_init",
    }),
    invoke: (api, ctx) => (api as any).OntologyEventSchema.parse(ctx),
    assert: (r) => r.branch === "main" && r.previousEventId === null,
  },
  {
    name: "rule:19 — OntologyAssetSchema validates required fields",
    setup: () => ({
      assetId: "asset_123",
      type: "file",
      originalPath: "/path",
      storedPath: "/stored",
      role: "test",
      createdAt: "2023-01-01",
    }),
    invoke: (api, ctx) => (api as any).OntologyAssetSchema.parse(ctx),
    assert: (r) => r.assetId === "asset_123" && r.type === "file",
  },
  {
    name: "rule:20 — OntologyModelSchema provides defaults for temperature and multimodal",
    setup: () => ({
      id: "model_123",
      provider: "mock",
      name: "test-model",
    }),
    invoke: (api, ctx) => (api as any).OntologyModelSchema.parse(ctx),
    assert: (r) => r.temperature === 0.2 && r.multimodal === false,
  },
  {
    name: "rule:21 — OntologyProcessorSchema defaults enabled to true",
    setup: () => ({
      id: "proc_123",
      phase: "pre",
      description: "test processor",
    }),
    invoke: (api, ctx) => (api as any).OntologyProcessorSchema.parse(ctx),
    assert: (r) => r.enabled === true,
  },
  {
    name: "rule:22 — PersistedRunInputSchema provides defaults for nullable fields",
    setup: () => ({
      promptHash: "prompt:hash:123",
      task: "test-task",
    }),
    invoke: (api, ctx) => (api as any).PersistedRunInputSchema.parse(ctx),
    assert: (r) => r.contextHash === null && r.targetNodeId === null && r.branch === null && r.time === null,
  },
  {
    name: "rule:23 — PersistedRunSchema provides defaults for validation",
    setup: () => ({
      id: "run_123",
      createdAt: 1234567890,
      kind: "prompt",
      input: {
        promptHash: "prompt:hash:123",
        task: "test-task",
      },
      model: {
        provider: "mock",
        model: "test-model",
      },
      output: {
        text: "test output",
      },
      duration_ms: 1000,
      hash: "run:hash:123",
    }),
    invoke: (api, ctx) => (api as any).PersistedRunSchema.parse(ctx),
    assert: (r) => r.validation === null,
  },
  {
    name: "rule:24 — WorkflowRunRecordSchema validates with defaults",
    setup: () => ({
      id: "wfrun_123",
      createdAt: 1234567890,
      graph: {
        file: "test.graph",
        graphHash: "wfgraph:hash:123",
      },
      inputHash: "wfinput:hash:123",
      result: {
        verdict: "accept",
        stepCount: 1,
        durationMs: 1000,
      },
      steps: [],
      hash: "wfrun:hash:123",
    }),
    invoke: (api, ctx) => (api as any).WorkflowRunRecordSchema.parse(ctx),
    assert: (r) => r.graph.name === null && r.model.provider === null && r.model.model === null,
  },
  {
    name: "rule:25 — ProposalNodeCreatePayloadSchema provides default label",
    setup: () => ({
      level: "project",
      kind: "function",
      prompt: "test prompt",
      parentNodeId: "node_123",
    }),
    invoke: (api, ctx) => (api as any).ProposalNodeCreatePayloadSchema.parse(ctx),
    assert: (r) => r.label === null,
  },
  {
    name: "rule:26 — ProposalEdgeCreatePayloadSchema provides default branch",
    setup: () => ({
      from: "node_1",
      to: "node_2",
      type: "inherits_from",
    }),
    invoke: (api, ctx) => (api as any).ProposalEdgeCreatePayloadSchema.parse(ctx),
    assert: (r) => r.branch === null,
  },
  {
    name: "rule:27 — ProposalValidationSnapshotSchema provides default arrays",
    setup: () => ({
      ok: true,
      score: 1.0,
    }),
    invoke: (api, ctx) => (api as any).ProposalValidationSnapshotSchema.parse(ctx),
    assert: (r) => Array.isArray(r.violations) && Array.isArray(r.warnings),
  },
  {
    name: "rule:28 — ProposalProvenanceSchema provides default arrays",
    setup: () => ({}),
    invoke: (api, ctx) => (api as any).ProposalProvenanceSchema.parse(ctx),
    assert: (r) => Array.isArray(r.derivedFrom) && r.rationale === null,
  },
  {
    name: "rule:29 — NodeDraftSchema validates required fields",
    setup: () => ({
      focalNodeId: "node_123",
      draftPrompt: "test draft",
      createdAt: 1234567890,
      updatedAt: 1234567890,
    }),
    invoke: (api, ctx) => (api as any).NodeDraftSchema.parse(ctx),
    assert: (r) => r.focalNodeId === "node_123" && r.draftPrompt === "test draft",
  },
  {
    name: "rule:30 — OntologyStateSchema provides default activeBranch",
    setup: () => ({
      initialized: true,
      schemaVersion: "0.1.0",
      projectName: "test-project",
      rootNodeId: "node_123",
      nodeCount: 1,
      edgeCount: 1,
      eventCount: 1,
      lastEventId: "evt_123",
      createdAt: "2023-01-01",
      updatedAt: "2023-01-01",
    }),
    invoke: (api, ctx) => (api as any).OntologyStateSchema.parse(ctx),
    assert: (r) => r.activeBranch === "main",
  },
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]).has(i));
