// GENERATED by `onto probe node_0016` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 11 self-validated case(s)
// (each matched the source src/kernel/core/nodes/create-node.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — node id is sequential from nodeCount",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Create a new artifact node",
        label: "Test Artifact Node"
      },
      mockState: {
        nodeCount: 5,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 10,
        lastEventId: "evt_prev1234",
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      // Mocking the state read to return our fixed state
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => r.node.id === "node_0000000000000005",
  },
  {
    name: "rule:2 — event ID is UUID formatted string",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Create a new artifact node"
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => typeof r.event.eventId === "string" && r.event.eventId.startsWith("evt_") && r.event.eventId.length > 8,
  },
  {
    name: "rule:3 — computed label is derived from prompt when not provided",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "This is a very long prompt that should be trimmed to 64 characters or less for the label generation process",
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => r.node.label === "This is a very long prompt that should be trimmed to 64 characters or less for the label gene",
  },
  {
    name: "rule:4 — parentNodeId defaults to project root when not provided",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Node with default parent",
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => r.node.graph.parentId === "root_0000000000000000",
  },
  {
    name: "rule:5 — requires array maps each source to declared type",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Node with requirements",
        requires: ["type1", "type2"]
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => 
      r.node.context.requires.length === 2 &&
      r.node.context.requires[0].source === "type1" &&
      r.node.context.requires[0].nodeType === "declared" &&
      r.node.context.requires[1].source === "type2" &&
      r.node.context.requires[1].nodeType === "declared",
  },
  {
    name: "rule:6 — provides array maps each key to declared type with optional signature",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Node with provisions",
        provides: ["key1", "key2"],
        provideSignatures: {
          key1: "signature1"
        }
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => 
      r.node.context.provides.length === 2 &&
      r.node.context.provides[0].key === "key1" &&
      r.node.context.provides[0].nodeType === "declared" &&
      r.node.context.provides[0].signature === "signature1" &&
      r.node.context.provides[1].key === "key2" &&
      r.node.context.provides[1].nodeType === "declared" &&
      r.node.context.provides[1].signature === undefined,
  },
  {
    name: "rule:7 — forbids array maps each source to declared type",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Node with forbidden types",
        forbids: ["forbid1", "forbid2"]
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => 
      r.node.context.forbids.length === 2 &&
      r.node.context.forbids[0].source === "forbid1" &&
      r.node.context.forbids[0].nodeType === "declared" &&
      r.node.context.forbids[1].source === "forbid2" &&
      r.node.context.forbids[1].nodeType === "declared",
  },
  {
    name: "rule:8 — rules array contains valid FORBID/REQUIRE strings if provided",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Node with rules",
        rules: ["FORBID: unsafe operations", "REQUIRE: validation checks"]
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => 
      r.node.rules.length === 2 &&
      r.node.rules[0] === "FORBID: unsafe operations" &&
      r.node.rules[1] === "REQUIRE: validation checks",
  },
  {
    name: "rule:9 — literal text is emitted verbatim if specified",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Node with literal text",
        literal: "This is literal text that should be preserved exactly as is."
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => r.node.literal === "This is literal text that should be preserved exactly as is.",
  },
  {
    name: "rule:10 — outputs.files includes source file paths if provided",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Node with source files",
        sourceFiles: ["/path/to/file1.ts", "/path/to/file2.ts"]
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => 
      r.node.outputs.files.length === 2 &&
      r.node.outputs.files[0] === "/path/to/file1.ts" &&
      r.node.outputs.files[1] === "/path/to/file2.ts",
  },
  {
    name: "rule:11 — node integrity hash is calculated and included",
    setup: () => ({
      options: {
        level: "system",
        kind: "artifact",
        prompt: "Node with integrity hash",
        label: "Test Node"
      },
      mockState: {
        nodeCount: 1,
        rootNodeId: "root_0000000000000000",
        activeBranch: "main",
        eventCount: 1,
        lastEventId: null,
        updatedAt: "2023-01-01T00:00:00.000Z"
      }
    }),
    invoke: (api, ctx) => {
      (api as any).readState = () => ctx.mockState;
      return (api as any).createNode(ctx.options);
    },
    assert: (r) => 
      typeof r.node.integrity.hash === "string" &&
      r.node.integrity.hash.length > 0 &&
      r.node.integrity.schemaVersion !== undefined,
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).has(i));
