// GENERATED by `onto probe node_0012` (model: qwen3-coder:480b-cloud). Do not hand-edit;
// re-run probe to regenerate. 8 self-validated case(s)
// (each matched the source src/kernel/core/fs/json.ts under the behaviour-checker).
import type { BehaviorCase } from "../../src/laws/behavior-checker.js";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function createTempDir(): string {
  const dir = path.join(tmpdir(), `json-test-${Date.now()}-${Math.random().toString(36).substring(2, 15)}`);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return dir;
}

const __generatedCases: BehaviorCase[] = [
  {
    name: "rule:1 — ensureDir creates directory if it doesn't exist",
    setup: () => {
      const tempDir = createTempDir();
      const newDir = path.join(tempDir, "new-directory");
      return { tempDir, newDir };
    },
    invoke: (api, ctx) => {
      api.ensureDir(ctx.newDir);
      return fs.existsSync(ctx.newDir);
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:2 — ensureDir does not fail if directory already exists",
    setup: () => {
      const tempDir = createTempDir();
      fs.mkdirSync(tempDir, { recursive: true });
      return { tempDir };
    },
    invoke: (api, ctx) => {
      api.ensureDir(ctx.tempDir);
      return fs.existsSync(ctx.tempDir);
    },
    assert: (r) => r === true,
  },
  {
    name: "rule:3 — writeJson creates file with correct content",
    setup: () => {
      const tempDir = createTempDir();
      const filePath = path.join(tempDir, "test.json");
      const value = { hello: "world", nested: { value: 42 } };
      return { tempDir, filePath, value };
    },
    invoke: (api, ctx) => {
      api.writeJson(ctx.filePath, ctx.value);
      const content = fs.readFileSync(ctx.filePath, "utf-8");
      return JSON.parse(content);
    },
    assert: (r) => r.hello === "world" && r.nested.value === 42,
  },
  {
    name: "rule:4 — readJson parses JSON correctly",
    setup: () => {
      const tempDir = createTempDir();
      const filePath = path.join(tempDir, "test.json");
      const value = { foo: "bar", count: 123 };
      fs.writeFileSync(filePath, JSON.stringify(value, null, 2) + "\n", "utf-8");
      return { filePath, value };
    },
    invoke: (api, ctx) => api.readJson(ctx.filePath),
    assert: (r) => r.foo === "bar" && r.count === 123,
  },
  {
    name: "rule:5 — appendJsonl appends line correctly",
    setup: () => {
      const tempDir = createTempDir();
      const filePath = path.join(tempDir, "test.jsonl");
      const value = { event: "test", id: 1 };
      return { tempDir, filePath, value };
    },
    invoke: (api, ctx) => {
      api.appendJsonl(ctx.filePath, ctx.value);
      const content = fs.readFileSync(ctx.filePath, "utf-8");
      return content.trim();
    },
    assert: (r) => r === JSON.stringify({ event: "test", id: 1 }),
  },
  {
    name: "rule:6 — readJsonl reads all lines correctly",
    setup: () => {
      const tempDir = createTempDir();
      const filePath = path.join(tempDir, "test.jsonl");
      const values = [
        { event: "start", ts: 1000 },
        { event: "end", ts: 2000 }
      ];
      const content = values.map(v => JSON.stringify(v)).join("\n") + "\n";
      fs.writeFileSync(filePath, content, "utf-8");
      return { filePath, values };
    },
    invoke: (api, ctx) => api.readJsonl(ctx.filePath),
    assert: (r) => 
      Array.isArray(r) && 
      r.length === 2 && 
      r[0].event === "start" && 
      r[1].event === "end",
  },
  {
    name: "rule:7 — readJsonl returns empty array for missing file",
    setup: () => {
      const tempDir = createTempDir();
      const filePath = path.join(tempDir, "missing.jsonl");
      return { filePath };
    },
    invoke: (api, ctx) => api.readJsonl(ctx.filePath),
    assert: (r) => Array.isArray(r) && r.length === 0,
  },
  {
    name: "rule:8 — writeJson overwrites existing file atomically",
    setup: () => {
      const tempDir = createTempDir();
      const filePath = path.join(tempDir, "overwrite.json");
      fs.writeFileSync(filePath, '{"old": true}', "utf-8");
      const newValue = { new: "data" };
      return { tempDir, filePath, newValue };
    },
    invoke: (api, ctx) => {
      api.writeJson(ctx.filePath, ctx.newValue);
      const content = fs.readFileSync(ctx.filePath, "utf-8");
      return JSON.parse(content);
    },
    assert: (r) => r.new === "data",
  }
];
// Only the cases that self-validated against the source are exported.
export const cases = __generatedCases.filter((_, i) => new Set([0, 1, 2, 3, 4, 5, 6, 7]).has(i));
