import { dirname, join, relative, basename } from 'node:path';

import { Project, QuoteKind } from 'ts-morph';

import type { ComponentRegistryEntry, RenderAST, RenderNode } from '../schemas/index.js';

export async function generateReactComponent(
  ast: RenderAST,
  componentsRegistry: Record<string, ComponentRegistryEntry>,
  outputPath: string,
  root: string
): Promise<void> {
  const project = new Project({
    manipulationSettings: {
      quoteKind: QuoteKind.Single
    }
  });

  const sourceFile = project.createSourceFile(outputPath, '', { overwrite: true });

  sourceFile.insertText(0, '// GENERATED BY ONTOLOGY. DO NOT EDIT MANUALLY.\n');

  const usedComponents = new Set<string>();

  function collectComponents(node: RenderNode) {
    usedComponents.add(node.component);
    if (node.children) {
      for (const child of node.children) {
        collectComponents(child);
      }
    }
  }

  for (const node of ast.nodes) {
    collectComponents(node);
  }

  const outputDir = dirname(outputPath);

  for (const componentId of Array.from(usedComponents).sort()) {
    const registryEntry = componentsRegistry[componentId];
    if (!registryEntry) {
      throw new Error(`Component ${componentId} not found in registry`);
    }

    const implPath = join(root, registryEntry.implementationPath);
    let relPath = relative(outputDir, implPath);

    if (!relPath.startsWith('.')) {
      relPath = `./${relPath}`;
    }

    relPath = relPath.replace(/\.tsx?$/, '');

    sourceFile.addImportDeclaration({
      moduleSpecifier: relPath,
      namedImports: [componentId]
    });
  }

  function generateJsx(node: RenderNode, indentLevel: number): string {
    const indent = '  '.repeat(indentLevel);
    let jsx = `${indent}<${node.component}`;

    for (const [key, value] of Object.entries(node.props)) {
      if (typeof value === 'string') {
        // string literals: attr="value"
        jsx += ` ${key}="${value}"`;
      } else {
        // boolean, number, object: attr={value}
        jsx += ` ${key}={${JSON.stringify(value)}}`;
      }
    }

    if (!node.children || node.children.length === 0) {
      jsx += ' />';
    } else {
      jsx += '>\n';
      for (const child of node.children) {
        jsx += generateJsx(child, indentLevel + 1) + '\n';
      }
      jsx += `${indent}</${node.component}>`;
    }

    return jsx;
  }

  let functionBody = '  return (\n';
  if (ast.nodes.length === 1) {
    functionBody += generateJsx(ast.nodes[0]!, 2) + '\n';
  } else {
    functionBody += '    <>\n';
    for (const node of ast.nodes) {
      functionBody += generateJsx(node, 3) + '\n';
    }
    functionBody += '    </>\n';
  }
  functionBody += '  );\n';

  sourceFile.addFunction({
    isExported: true,
    name: ast.viewId,
    statements: functionBody
  });

  await sourceFile.save();
}
