import { Project, QuoteKind } from 'ts-morph';
import type { MachineAST, MachineState, MachineTransition } from '../schemas/index.js';
import { dirname } from 'node:path';
import { mkdirSync } from 'node:fs';

function generateContextType(contextSchema: any): string {
  if (!contextSchema || typeof contextSchema !== 'object') {
    return 'Record<string, any>';
  }

  // Simple basic extraction if it's a JSON schema object
  if (contextSchema.type === 'object' && contextSchema.properties) {
    const props = Object.entries(contextSchema.properties)
      .map(([key, val]: [string, any]) => {
        let tsType = 'any';
        if (val.type === 'string') tsType = 'string';
        else if (val.type === 'number' || val.type === 'integer') tsType = 'number';
        else if (val.type === 'boolean') tsType = 'boolean';
        return `${key}: ${tsType}`;
      })
      .join('; ');
    return `{ ${props} }`;
  }

  return 'Record<string, any>';
}

export async function generateXStateMachine(
  ast: MachineAST,
  viewName: string,
  outputPath: string
): Promise<void> {
  const project = new Project({
    manipulationSettings: {
      quoteKind: QuoteKind.Single
    }
  });

  mkdirSync(dirname(outputPath), { recursive: true });

  const sourceFile = project.createSourceFile(outputPath, '', { overwrite: true });

  sourceFile.insertText(0, '// GENERATED BY ONTOLOGY. DO NOT EDIT MANUALLY.\n');

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'xstate',
    namedImports: ['setup', 'assign']
  });

  // Extract events for typing
  let eventsType = 'any';
  if (ast.events && ast.events.length > 0) {
    eventsType = ast.events
      .map(event => {
        if (event.payload) {
          const payloadType = generateContextType(event.payload);
          return `{ type: '${event.name}'; payload: ${payloadType} }`;
        }
        return `{ type: '${event.name}' }`;
      })
      .join(' | ');
  }

  const contextType = generateContextType(ast.context);

  // Reconstruct states with accurate string mapping for actions and guards
  function processState(state: MachineState): any {
    const result: any = {};
    if (state.type) result.type = state.type;
    if (state.initial) result.initial = state.initial;
    if (state.description) result.description = state.description;

    if (state.entry) {
      result.entry = state.entry.map(e => {
         const effectAst = ast.effects.find(eff => eff.name === e);
         if (effectAst?.kind === 'assignment') {
            return `assign({ /* Assignment for ${e} */ })`;
         }
         return `'${e}'`;
      });
    }

    if (state.exit) {
      result.exit = state.exit.map(e => {
         const effectAst = ast.effects.find(eff => eff.name === e);
         if (effectAst?.kind === 'assignment') {
            return `assign({ /* Assignment for ${e} */ })`;
         }
         return `'${e}'`;
      });
    }

    if (state.on) {
      result.on = {};
      for (const [eventName, transitions] of Object.entries(state.on)) {
        const transArr = Array.isArray(transitions) ? transitions : [transitions];
        result.on[eventName] = transArr.map(t => {
          const transResult: any = { target: t.target };
          if (t.guard) transResult.guard = `'${t.guard}'`;
          if (t.effects && t.effects.length > 0) {
            transResult.actions = t.effects.map(e => {
              const effectAst = ast.effects.find(eff => eff.name === e);
              if (effectAst?.kind === 'assignment') {
                 return `assign({ /* Assignment for ${e} */ })`;
              }
              return `'${e}'`;
            });
          }
          if (t.description) transResult.description = t.description;
          return transResult;
        });
      }
    }

    if (state.states) {
      result.states = {};
      for (const [stateName, childState] of Object.entries(state.states)) {
        result.states[stateName] = processState(childState);
      }
    }

    return result;
  }

  const statesObj: Record<string, any> = {};
  for (const [stateName, stateDef] of Object.entries(ast.states)) {
    statesObj[stateName] = processState(stateDef);
  }

  // Need to format the object properly to avoid quotes around functions/strings where we want raw output
  function stringifyWithRaw(obj: any, indentLevel = 1): string {
    if (Array.isArray(obj)) {
      if (obj.length === 0) return '[]';
      const items = obj.map(item => {
        if (typeof item === 'string') {
          // If it's a string that starts with assign(, it's raw
          if (item.startsWith('assign(')) return item;
          // If it's a raw string reference like 'action', it already has quotes from our mapping
          if (item.startsWith("'") && item.endsWith("'")) return item;
          return `'${item}'`;
        }
        return stringifyWithRaw(item, indentLevel + 1);
      });
      // Single element arrays can be inline or inline array
      if (items.length === 1) return `[${items[0]}]`;
      const indent = '  '.repeat(indentLevel);
      return `[\n${indent}  ${items.join(`, \n${indent}  `)}\n${indent}]`;
    }

    if (typeof obj === 'object' && obj !== null) {
      const keys = Object.keys(obj);
      if (keys.length === 0) return '{}';
      const indent = '  '.repeat(indentLevel);
      const props = keys.map(key => {
        const val = stringifyWithRaw(obj[key], indentLevel + 1);
        // quotes around key if needed
        const formattedKey = /^[a-zA-Z_$][0-9a-zA-Z_$]*$/.test(key) ? key : `'${key}'`;
        return `${indent}  ${formattedKey}: ${val}`;
      });
      return `{\n${props.join(',\n')}\n${indent}}`;
    }

    if (typeof obj === 'string') {
      if (obj.startsWith("'") && obj.endsWith("'")) return obj;
      if (obj.startsWith('assign(')) return obj;
      return `'${obj}'`;
    }

    return String(obj);
  }

  const statesString = stringifyWithRaw(statesObj);

  // We write the setup structure manually
  const machineCode = `
export const machine = setup({
  types: {} as {
    context: ${contextType};
    events: ${eventsType};
  }
}).createMachine({
  id: '${viewName}',
  initial: '${ast.initial}',
  context: {}, // Initialize from context type later or empty object
  states: ${statesString}
});
`;

  sourceFile.addStatements(machineCode);
  await sourceFile.save();
}
